export type JourneyState =
  | 'EMS_DISPATCHED'
  | 'EMS_ON_SCENE'
  | 'EMS_EN_ROUTE'
  | 'ARRIVAL'
  | 'REGISTRATION'
  | 'TRIAGE'
  | 'WAITING'
  | 'ASSESSMENT'
  | 'ORDERS'
  | 'RESULTS'
  | 'DISPOSITION'
  | 'ADMISSION'
  | 'DISCHARGE';

export const JourneyTransitions: Record<JourneyState, JourneyState[]> = {
  EMS_DISPATCHED: ['EMS_ON_SCENE', 'ARRIVAL'],
  EMS_ON_SCENE: ['EMS_EN_ROUTE', 'ARRIVAL'],
  EMS_EN_ROUTE: ['ARRIVAL'],
  ARRIVAL: ['REGISTRATION'],
  REGISTRATION: ['TRIAGE'],
  TRIAGE: ['WAITING', 'ASSESSMENT'],
  WAITING: ['ASSESSMENT'],
  ASSESSMENT: ['ORDERS', 'DISPOSITION'],
  ORDERS: ['RESULTS'],
  RESULTS: ['DISPOSITION'],
  DISPOSITION: ['ADMISSION', 'DISCHARGE'],
  ADMISSION: ['DISCHARGE'],
  DISCHARGE: [],
};
