import { PrimaryIntent } from '../medical-control-plane/intent-classifier/dto/intent-classification.dto';
import { MoEExpertDescriptor, MoEExpertId, experts } from './moe-router.types';

export { experts };

export const COST_FLOOR = 0.01;

export const BACKEND_EXECUTOR_TOOL_IDS = ['sofa-calculator', 'drug-interactions', 'lab-interpreter'];

export const MOE_EXPERT_DESCRIPTORS: MoEExpertDescriptor[] = [
  {
    id: 'emergency',
    label: 'Emergency expert',
    clinical: true,
    intents: [PrimaryIntent.EMERGENCY, PrimaryIntent.CLINICAL_TOOL],
    keywords: [
      'acute',
      'acls',
      'arrest',
      'bleeding',
      'chest pain',
      'critical',
      'crisis',
      'hypotension',
      'sepsis',
      'shock',
      'sofa',
      'stroke',
      'suicide',
      'trauma',
      'unstable',
    ],
    toolHints: ['sofa-calculator', 'sofa-score', 'acls-protocol', 'atls-protocol'],
    featureHints: ['emergency', 'triage', 'critical-care'],
    sourceSurfaces: ['emergency', 'assistant-chat'],
    retrievalPolicy: 'guideline',
    estimatedCost: 0.08,
    defaultRelevance: 0.95,
    requiresHumanReview: true,
    emergencyAware: true,
    reason: 'Emergency and escalation-aware routing has safety priority.',
  },
  {
    id: 'cardiology',
    label: 'Cardiology expert',
    clinical: true,
    intents: [PrimaryIntent.CLINICAL_TOOL, PrimaryIntent.MEDICAL_REFERENCE],
    keywords: [
      'acs',
      'afib',
      'angina',
      'anticoagulation',
      'arrhythmia',
      'cardiac',
      'chads',
      'chest pain',
      'ecg',
      'ekg',
      'heart',
      'heart failure',
      'troponin',
    ],
    toolHints: ['heart-score', 'grace-acs', 'cha2ds2vasc-calculator', 'has-bled'],
    featureHints: ['cardiology', 'cardiac'],
    sourceSurfaces: ['cardiology', 'assistant-chat'],
    retrievalPolicy: 'guideline',
    estimatedCost: 0.12,
    defaultRelevance: 0.92,
    requiresHumanReview: true,
    emergencyAware: true,
    reason: 'Cardiology signals were present in symptoms, tools, or feature hints.',
  },
  {
    id: 'pulmonology',
    label: 'Pulmonology expert',
    clinical: true,
    intents: [PrimaryIntent.CLINICAL_TOOL, PrimaryIntent.MEDICAL_REFERENCE],
    keywords: [
      'abg',
      'asthma',
      'copd',
      'dyspnea',
      'fio2',
      'hypoxemia',
      'oxygen',
      'pao2',
      'pneumonia',
      'pulmonary',
      'respiratory',
      'shortness of breath',
      'ventilation',
    ],
    toolHints: ['abg-interpreter', 'copd-gold', 'copd-gold-assessment', 'asthma-exacerbation-assistant'],
    featureHints: ['pulmonology', 'respiratory'],
    sourceSurfaces: ['pulmonology', 'assistant-chat'],
    retrievalPolicy: 'guideline',
    estimatedCost: 0.1,
    defaultRelevance: 0.9,
    requiresHumanReview: true,
    emergencyAware: true,
    reason: 'Pulmonary or oxygenation signals were detected.',
  },
  {
    id: 'nephrology',
    label: 'Nephrology expert',
    clinical: true,
    intents: [PrimaryIntent.CLINICAL_TOOL, PrimaryIntent.MEDICAL_REFERENCE],
    keywords: [
      'aki',
      'bun',
      'ckd',
      'creatinine',
      'dialysis',
      'egfr',
      'electrolyte',
      'fluid balance',
      'kidney',
      'nephrology',
      'potassium',
      'renal',
      'sodium',
    ],
    toolHints: ['aki-staging-assistant', 'ckd-progression-predictor', 'ckd-staging', 'egfr-ckd-epi', 'fena', 'lab-interpreter'],
    featureHints: ['nephrology', 'renal'],
    sourceSurfaces: ['nephrology', 'assistant-chat'],
    retrievalPolicy: 'guideline',
    estimatedCost: 0.1,
    defaultRelevance: 0.9,
    requiresHumanReview: true,
    emergencyAware: true,
    reason: 'Renal, electrolyte, or kidney workflow signals were detected.',
  },
  {
    id: 'gastroenterology',
    label: 'Gastroenterology expert',
    clinical: true,
    intents: [PrimaryIntent.CLINICAL_TOOL, PrimaryIntent.MEDICAL_REFERENCE],
    keywords: [
      'abdominal pain',
      'ascites',
      'bilirubin',
      'colitis',
      'endoscopy',
      'gastroenterology',
      'gi bleed',
      'hepatic',
      'hepatitis',
      'ibd',
      'jaundice',
      'liver',
      'pancreatitis',
      'varices',
    ],
    toolHints: ['gi-bleed-risk', 'meld-score', 'child-pugh', 'gastroenterology-command-center'],
    featureHints: ['gastroenterology', 'gi', 'hepatology'],
    sourceSurfaces: ['gastroenterology', 'assistant-chat'],
    retrievalPolicy: 'guideline',
    estimatedCost: 0.1,
    defaultRelevance: 0.89,
    requiresHumanReview: true,
    emergencyAware: true,
    reason: 'GI, liver, or abdominal workflow signals were detected.',
  },
  {
    id: 'neurology',
    label: 'Neurology expert',
    clinical: true,
    intents: [PrimaryIntent.CLINICAL_TOOL, PrimaryIntent.MEDICAL_REFERENCE, PrimaryIntent.EMERGENCY],
    keywords: [
      'aphasia',
      'eeg',
      'headache',
      'intracranial',
      'migraine',
      'neuro',
      'neurology',
      'nihss',
      'seizure',
      'stroke',
      'syncope',
      'tia',
      'weakness',
    ],
    toolHints: ['nihss', 'stroke-triage', 'neurology-timeline-ai', 'neuro-telemetry-dashboard'],
    featureHints: ['neurology', 'neuro', 'stroke'],
    sourceSurfaces: ['neurology', 'assistant-chat'],
    retrievalPolicy: 'guideline',
    estimatedCost: 0.11,
    defaultRelevance: 0.9,
    requiresHumanReview: true,
    emergencyAware: true,
    reason: 'Neurologic symptoms, stroke, seizure, or neuro-monitoring signals were detected.',
  },
  {
    id: 'psychiatry',
    label: 'Psychiatry expert',
    clinical: true,
    intents: [PrimaryIntent.CLINICAL_TOOL, PrimaryIntent.MEDICAL_REFERENCE, PrimaryIntent.EMERGENCY],
    keywords: [
      'agitation',
      'anxiety',
      'behavioral',
      'cage',
      'depression',
      'gad7',
      'mental health',
      'phq',
      'psychiatry',
      'psychosis',
      'suicide',
      'withdrawal',
    ],
    toolHints: ['gad7', 'phq9', 'cage', 'columbia-suicide-severity-workflow', 'mental-health-screening-assistant'],
    featureHints: ['psychiatry', 'behavioral-health'],
    sourceSurfaces: ['psychiatry', 'assistant-chat'],
    retrievalPolicy: 'guideline',
    estimatedCost: 0.1,
    defaultRelevance: 0.9,
    requiresHumanReview: true,
    emergencyAware: true,
    reason: 'Behavioral health or crisis-screening signals were detected.',
  },
  {
    id: 'fleet',
    label: 'Fleet expert',
    clinical: false,
    intents: [PrimaryIntent.ADMINISTRATIVE, PrimaryIntent.GENERAL_QUERY],
    keywords: ['ambulance', 'asset', 'dispatch', 'fleet', 'route optimizer', 'transport', 'vehicle'],
    toolHints: ['fleet-command', 'dispatch-ai', 'route-optimizer'],
    featureHints: ['fleet', 'dispatch'],
    sourceSurfaces: ['fleet', 'assistant-chat'],
    retrievalPolicy: 'operational',
    estimatedCost: 0.06,
    defaultRelevance: 0.88,
    requiresHumanReview: false,
    emergencyAware: false,
    reason: 'Fleet, dispatch, or transport operations signals were detected.',
  },
  {
    id: 'hospital-map',
    label: 'Hospital-map expert',
    clinical: false,
    intents: [PrimaryIntent.ADMINISTRATIVE, PrimaryIntent.GENERAL_QUERY],
    keywords: ['floor', 'hospital map', 'indoor', 'location', 'map', 'nearest', 'unit', 'wayfinding', 'zone'],
    toolHints: ['hospital-map', 'live-tracking-map'],
    featureHints: ['hospital-map', 'map', 'live-tracking'],
    sourceSurfaces: ['hospital-map', 'live-tracking', 'assistant-chat'],
    retrievalPolicy: 'operational',
    estimatedCost: 0.05,
    defaultRelevance: 0.85,
    requiresHumanReview: false,
    emergencyAware: false,
    reason: 'Map, location, or wayfinding signals were detected.',
  },
  {
    id: 'medical-iot',
    label: 'Medical IoT expert',
    clinical: false,
    intents: [PrimaryIntent.ADMINISTRATIVE, PrimaryIntent.GENERAL_QUERY],
    keywords: ['device', 'iot', 'offline', 'sensor', 'signal', 'telemetry', 'wearable'],
    toolHints: ['device-recommendation-assistant', 'glucose-telemetry-dashboard', 'neuro-telemetry-dashboard'],
    featureHints: ['iot', 'medical-iot', 'device-fleet', 'telemetry'],
    sourceSurfaces: ['iot', 'medical-iot', 'assistant-chat'],
    retrievalPolicy: 'operational',
    estimatedCost: 0.05,
    defaultRelevance: 0.86,
    requiresHumanReview: false,
    emergencyAware: false,
    reason: 'Device telemetry or medical IoT operations signals were detected.',
  },
  {
    id: 'operations',
    label: 'Operations expert',
    clinical: false,
    intents: [PrimaryIntent.ADMINISTRATIVE, PrimaryIntent.GENERAL_QUERY],
    keywords: ['bed', 'capacity', 'command center', 'hospital command', 'operations', 'staffing', 'throughput'],
    toolHints: ['hospital-command-assistant', 'bed-occupancy-calculator'],
    featureHints: ['operations', 'hospital-operations'],
    sourceSurfaces: ['operations', 'assistant-chat'],
    retrievalPolicy: 'operational',
    estimatedCost: 0.06,
    defaultRelevance: 0.86,
    requiresHumanReview: false,
    emergencyAware: false,
    reason: 'Hospital operations or resource-management signals were detected.',
  },
  {
    id: 'documentation',
    label: 'Documentation expert',
    clinical: true,
    intents: [PrimaryIntent.GENERAL_QUERY, PrimaryIntent.ADMINISTRATIVE, PrimaryIntent.MEDICAL_REFERENCE],
    keywords: ['ambient', 'discharge', 'documentation', 'handoff', 'note', 'soap', 'scribe', 'summary'],
    toolHints: ['ambient-scribe', 'patient-summary-ai', 'timeline-ai'],
    featureHints: ['ambient-scribe', 'documentation', 'patient-summary-ai', 'timeline-ai'],
    sourceSurfaces: ['documentation', 'assistant-chat'],
    retrievalPolicy: 'patient_scoped',
    estimatedCost: 0.07,
    defaultRelevance: 0.84,
    requiresHumanReview: true,
    emergencyAware: false,
    reason: 'Clinical documentation or summary generation signals were detected.',
  },
];

export const MOE_EXPERT_DESCRIPTOR_BY_ID = MOE_EXPERT_DESCRIPTORS.reduce<
  Record<MoEExpertId, MoEExpertDescriptor>
>((acc, descriptor) => {
  acc[descriptor.id] = descriptor;
  return acc;
}, {} as Record<MoEExpertId, MoEExpertDescriptor>);
