/**
 * Operational copy for the Reception workspace — plain language for front-desk staff.
 * Prefer these labels over product or technical terms (Smart Intake, MPI, OCR, etc.).
 */

export const RECEPTION_COPY = Object.freeze({
  workspace: {
    title: 'Reception',
    description: 'Register patients, confirm who they are, and send them to the triage nurse.',
    deskDescription: 'Register patients and send them to the triage nurse.',
    actionsLabel: 'Register a patient',
    registerWalkIn: 'Register walk-in',
    checkIdentity: 'Check ID & documents',
    otherArrivals: 'Other arrivals',
    sentToTriage: 'ready for the triage nurse',
    seeInList: 'See in waiting list',
    registerNext: 'Register next patient',
  },
  search: {
    idle: 'Search patient, encounter, referral, EMS, or queue in the bar above — press',
    filtering: 'Showing results for',
    filteringSuffix: '— use the search bar above for patient actions.',
    focus: 'Go to search',
    refine: 'Refine search',
  },
  chooser: {
    eyebrow: 'Other arrival types',
    title: 'How is this patient arriving?',
    description: 'Use these when the main register button is not the right fit.',
    fullIdentity: 'Full identity check',
    fullIdentityHint: 'Match records, review documents, allergies, and medications',
    scanId: 'Scan ID card',
    scanIdHint: 'Take a photo of ID or health card',
    walkIn: 'Register walk-in',
    walkInHint: 'Name, date of birth, and reason for visit — fastest option',
    withSymptoms: 'Register with symptoms',
    withSymptomsHint: 'Add complaint, vitals, and urgency before sending to nurse',
    unknown: 'Patient unknown',
    unknownHint: 'Send to triage nurse while identity is still being sorted out',
  },
  queues: {
    sectionTitle: 'Arrivals & waiting lists',
    listsTitle: "Today's lists",
    tabs: Object.freeze({
      ems: 'Ambulance arrivals',
      verification: 'Need ID check',
      pretriage: 'Waiting for nurse',
    }),
    empty: Object.freeze({
      ems: 'No ambulance patients waiting to register.',
      verification: 'No patients waiting for an ID check.',
      pretriage: 'No patients waiting for the triage nurse.',
    }),
    rowActionVerify: 'Check ID',
    rowActionEms: 'Ambulance',
  },
  metrics: Object.freeze({
    arrivalsToday: 'Registered today',
    awaitingVerification: 'Need ID check',
    awaitingTriage: 'Waiting for nurse',
    emsInbound: 'Ambulances coming',
    queueSize: 'On your lists',
    dataQualityRisks: 'Data gaps',
    queueOverdue: 'Overdue',
    longestWait: 'Longest wait',
  }),
  ems: {
    eyebrow: 'Ambulance updates',
    title: 'Incoming ambulances',
    description: 'See who is on the way and start their chart before they arrive.',
    refresh: 'Refresh',
    refreshing: 'Refreshing…',
    loading: 'Loading ambulance list…',
    empty: 'No ambulances on the way right now.',
    prepareChart: 'Start their chart',
    registerNow: 'Ambulance arrived — register now',
  },
  recentArrivals: {
    title: 'Just arrived',
    subtitle: 'Patients registered in the last 30 minutes.',
    empty: 'No one registered in the last 30 minutes.',
  },
  duplicate: {
    bannerTitle: 'This patient may already be here',
    bannerDescription:
      'We found a similar record. Open the existing chart before creating a new one.',
    alertTitle: 'Possible duplicate — check before registering',
    alertDescription: 'Open the existing chart or confirm this is a different person.',
    openChart: 'Open chart',
    openVerification: 'Check identity',
    identityPending: 'Identity unclear — send to nurse anyway',
    notDuplicate: 'Different person — continue',
  },
  express: {
    title: 'Register walk-in',
    subtitle: 'Tab between fields · Enter to finish · patient goes to triage nurse',
    submit: 'Register & send to nurse',
    submitting: 'Registering…',
  },
  quickCreate: {
    title: 'Register with symptoms',
    submit: 'Register & send to nurse',
    submitting: 'Registering…',
    closeLabel: 'Close registration form',
  },
  identityCheck: {
    overlayLabel: 'Check patient identity',
    title: 'Check patient identity',
    description:
      'Confirm name, date of birth, and health card. Link to an existing chart or register as new.',
    begin: 'Begin check',
    starting: 'Starting…',
    sessionActive: 'Check in progress',
    close: 'Close',
    backToReception: 'Back to Reception',
    aiHelp: 'Get help',
    aiHelpLoading: 'Getting help…',
    steps: Object.freeze([
      'Document & details',
      'Find match',
      'Confirm fields',
      'Finish',
    ]),
  },
  header: {
    register: 'Register',
    registerTitle: 'Register a walk-in patient',
    searchLabel: 'Patient search',
  },
  commandPalette: {
    newPatientClerk: 'Register walk-in',
    newPatientClerkDescription: 'Fast registration on the reception desk — sent to triage nurse.',
    newPatientOther: 'Check ID & register',
    newPatientOtherDescription: 'Identity check with document scan before registering.',
    patientLookupClerk: 'Search arriving patients',
  },
  searchResults: {
    filterQueues: 'Filter waiting lists',
    newPatient: 'Register new patient',
    noMatch: 'no match for',
  },
});
