import type {
  EmergencyAlert,
  EmergencyPatient,
  EmergencyRoom,
  EmergencyStaff,
} from './emergency-os.types';

export function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60000).toISOString();
}

export const emergencyPatientsFixture: EmergencyPatient[] = [
  {
    id: 'p1',
    mrn: 'ED-001234',
    firstName: 'Marcus',
    lastName: 'Chen',
    dob: '1965-03-14',
    age: 59,
    sex: 'M',
    arrivalTime: minutesAgo(95),
    triageTime: minutesAgo(88),
    chiefComplaint: 'Chest pain radiating to left arm',
    complaintCategory: 'Cardiac',
    state: 'Assessment',
    priority: 'P2',
    vitals: [
      {
        hr: 102,
        sbp: 148,
        dbp: 92,
        spo2: 96,
        temp: 36.8,
        rr: 18,
        gcs: 15,
        pain: 7,
        recordedAt: minutesAgo(80),
        recordedBy: 's1',
      },
    ],
    flags: ['HighRisk'],
    assignedStaffId: 's1',
    roomId: 'r3',
    notes: [],
    timeline: [
      {
        id: 'journey-p1-triage',
        from: 'Arrival',
        to: 'Triage',
        timestamp: minutesAgo(88),
        staffId: 's2',
        note: 'CTAS P2 chest pain pathway started.',
      },
    ],
  },
  {
    id: 'p3',
    mrn: 'ED-001236',
    firstName: 'Dorothy',
    lastName: 'Walsh',
    dob: '1948-11-03',
    age: 76,
    sex: 'F',
    arrivalTime: minutesAgo(180),
    triageTime: minutesAgo(170),
    chiefComplaint: 'Confusion, fever',
    complaintCategory: 'Sepsis',
    state: 'Results',
    priority: 'P2',
    vitals: [
      {
        hr: 118,
        sbp: 88,
        dbp: 54,
        spo2: 94,
        temp: 38.9,
        rr: 22,
        gcs: 13,
        pain: 3,
        recordedAt: minutesAgo(30),
        recordedBy: 's1',
      },
    ],
    flags: ['DeteriorationRisk', 'SepsisAlert'],
    assignedStaffId: 's1',
    roomId: 'r2',
    notes: [],
    timeline: [
      {
        id: 'journey-p3-results',
        from: 'Orders',
        to: 'Results',
        timestamp: minutesAgo(36),
        staffId: 's1',
        note: 'Lactate resulted; sepsis bundle review required.',
      },
    ],
  },
  {
    id: 'p4',
    mrn: 'ED-001237',
    firstName: 'James',
    lastName: 'Tremblay',
    dob: '1978-05-19',
    age: 46,
    sex: 'M',
    arrivalTime: minutesAgo(62),
    chiefComplaint: 'Abdominal pain right lower quadrant',
    complaintCategory: 'Abdominal',
    state: 'Waiting',
    priority: 'P3',
    vitals: [
      {
        hr: 96,
        sbp: 124,
        dbp: 80,
        spo2: 98,
        temp: 37.9,
        rr: 16,
        gcs: 15,
        pain: 8,
        recordedAt: minutesAgo(55),
        recordedBy: 's3',
      },
    ],
    flags: ['ReassessmentDue'],
    assignedStaffId: 's3',
    notes: [],
    timeline: [
      {
        id: 'journey-p4-waiting',
        from: 'Triage',
        to: 'Waiting',
        timestamp: minutesAgo(55),
        staffId: 's3',
        note: 'Reassess pain and vitals within 30 minutes.',
      },
    ],
  },
  {
    id: 'p12',
    mrn: 'ED-001245',
    firstName: 'Alyssa',
    lastName: 'Green',
    dob: '1999-08-11',
    age: 25,
    sex: 'F',
    arrivalTime: minutesAgo(210),
    chiefComplaint: 'Psychiatric hold, suicidal ideation, medically stable',
    complaintCategory: 'Mental Health',
    state: 'Disposition',
    priority: 'P3',
    vitals: [
      {
        hr: 90,
        sbp: 122,
        dbp: 78,
        spo2: 99,
        temp: 36.7,
        rr: 16,
        gcs: 15,
        pain: 0,
        recordedAt: minutesAgo(60),
        recordedBy: 's2',
      },
    ],
    flags: ['PendingAdmission', 'LongWait'],
    assignedStaffId: 's2',
    roomId: 'r12',
    notes: [],
    timeline: [
      {
        id: 'journey-p12-disposition',
        from: 'Results',
        to: 'Disposition',
        timestamp: minutesAgo(105),
        staffId: 's2',
        note: 'Awaiting inpatient mental health bed.',
      },
    ],
  },
  {
    id: 'ems-1',
    mrn: 'EMS-000441',
    firstName: 'Unknown',
    lastName: 'EMS Patient',
    dob: '1970-01-01',
    age: 54,
    sex: 'Other',
    arrivalTime: minutesAgo(8),
    chiefComplaint: 'EMS pre-arrival: stroke symptoms, ETA 6 minutes',
    complaintCategory: 'Neuro/Stroke',
    state: 'Arrival',
    priority: 'P1',
    vitals: [
      {
        hr: 108,
        sbp: 190,
        dbp: 104,
        spo2: 95,
        temp: 36.9,
        rr: 20,
        gcs: 12,
        pain: 0,
        recordedAt: minutesAgo(6),
        recordedBy: 'ems',
      },
    ],
    flags: ['EMSArrival', 'HighRisk'],
    assignedStaffId: 's3',
    notes: [],
    timeline: [
      {
        id: 'journey-ems-prearrival',
        to: 'Arrival',
        timestamp: minutesAgo(8),
        staffId: 'ems',
        note: 'EMS patched stroke symptoms; resus and CT notified.',
      },
    ],
  },
];

export const emergencyStaffFixture: EmergencyStaff[] = [
  { id: 's1', name: 'Dr. Priya Nair', role: 'MD', active: true },
  { id: 's2', name: 'Maya Thompson', role: 'RN', active: true },
  { id: 's3', name: 'Owen Clarke', role: 'Charge', active: true },
];

export const emergencyRoomsFixture: EmergencyRoom[] = [
  { id: 'r1', name: 'Resus 1', type: 'Resus', status: 'Available' },
  { id: 'r2', name: 'Resus 2', type: 'Resus', status: 'Occupied', patientId: 'p3' },
  { id: 'r3', name: 'Treatment 3', type: 'Treatment', status: 'Occupied', patientId: 'p1' },
  { id: 'r5', name: 'Treatment 5', type: 'Treatment', status: 'Available' },
  { id: 'r10', name: 'Treatment 10', type: 'Treatment', status: 'Blocked' },
  {
    id: 'r12',
    name: 'Mental Health Hold',
    type: 'Isolation',
    status: 'Occupied',
    patientId: 'p12',
  },
  { id: 'r14', name: 'Waiting Area A', type: 'Waiting', status: 'Occupied' },
];

export const emergencyAlertsFixture: EmergencyAlert[] = [
  {
    id: 'a1',
    severity: 'Critical',
    title: 'Sepsis criteria met',
    message: 'Dorothy Walsh has hypotension, fever, tachycardia, and altered mentation.',
    patientId: 'p3',
    createdAt: minutesAgo(24),
    dismissed: false,
  },
  {
    id: 'a2',
    severity: 'Warning',
    title: 'Reassessment due',
    message: 'James Tremblay is waiting with persistent right lower quadrant pain.',
    patientId: 'p4',
    createdAt: minutesAgo(12),
    dismissed: false,
  },
  {
    id: 'a3',
    severity: 'Critical',
    title: 'EMS stroke pre-arrival',
    message: 'Unknown EMS patient ETA 6 minutes. Stroke pathway and CT notification are pending.',
    patientId: 'ems-1',
    createdAt: minutesAgo(6),
    dismissed: false,
  },
];
