/**
 * CareDroid AI response provenance contract (PR-6).
 *
 * Clinically meaningful outputs must declare supporting evidence, confidence,
 * missing information, uncertainty, population limits, and human-review requirements.
 * LLMs summarize/retrieve/draft; they do not independently invent patient facts or scores.
 */

export const PROVENANCE_CONTRACT_VERSION = '1.1.0';

/**
 * How a response was actually produced. Added 2026-08-08 after a repeated
 * finding across this codebase's own truthfulness audits: a response can
 * carry real evidence/confidence/limitations (satisfying every other field
 * below) while still leaving the single question a clinician most needs
 * answered -- "was this generated by a model, or is it a rule matching my
 * input?" -- unstated. `modelOrEngine` is free text and was never a
 * controlled signal; this is.
 *
 * - LLM_GENERATED: free-text/summarized output from a real foundation-model
 *   call, not grounded by retrieved documents beyond conversation context.
 * - MODEL_PREDICTION: output of a trained ML/statistical model (classifier
 *   or regressor). As of this codebase's own audits, only 2 functions
 *   anywhere are backed by an actually-trained model (the NLU intent
 *   classifier, the artifact-type router) -- everything with a name like
 *   "predictX" or "-ml"/"-heuristic" that isn't one of those two is
 *   DETERMINISTIC_RULE, not this.
 * - RAG_ASSISTED: LLM output grounded by real retrieved chunks/sources
 *   (`evidence` contains `retrieved_chunk`/`knowledge_registry` items), or
 *   pure extractive retrieval with no generation step at all.
 * - TOOL_RESULT: output of a deterministic tool/calculator executed through
 *   the tool-orchestrator (a scored calculator, a structured lookup).
 * - DETERMINISTIC_RULE: hand-written rule-based or keyword-matching logic
 *   with no model or tool-orchestrator call -- e.g. keyword-trigger tables,
 *   threshold rules, command dispatchers.
 * - STATIC_CONTENT: a fixed, hardcoded string returned regardless of input
 *   -- a fallback message, not a per-request computation.
 * - FIXTURE_DEMO: sample, simulated, or placeholder data, not derived from
 *   real submitted/patient input.
 * - UNAVAILABLE: the model/tool path was attempted but failed, timed out,
 *   or is unconfigured; there is no real result to attribute to a category
 *   above.
 */
export const AI_RESPONSE_SOURCE_CATEGORIES = [
  'LLM_GENERATED',
  'MODEL_PREDICTION',
  'RAG_ASSISTED',
  'TOOL_RESULT',
  'DETERMINISTIC_RULE',
  'STATIC_CONTENT',
  'FIXTURE_DEMO',
  'UNAVAILABLE',
] as const;

export type AIResponseSourceCategory = (typeof AI_RESPONSE_SOURCE_CATEGORIES)[number];

export function isAiResponseSourceCategory(value: unknown): value is AIResponseSourceCategory {
  return (
    typeof value === 'string' &&
    (AI_RESPONSE_SOURCE_CATEGORIES as readonly string[]).includes(value)
  );
}

/**
 * How trustworthy an EVALUATION METRIC value is (accuracy, hallucination
 * rate, user satisfaction, quality/safety score, latency, success rate,
 * etc.) -- a different axis from AIResponseSourceCategory above, which
 * describes one response's generation mechanism. This describes whether an
 * aggregate/dashboard NUMBER reflects reality. Added 2026-08-08 after
 * finding a second, unfixed instance of the exact bug already fixed once in
 * `backend/src/modules/evaluation/evaluation.service.ts` (fabricated
 * per-turn metrics silently counted as measured) inside a structurally
 * identical sibling module (`backend/src/modules/training/`).
 *
 * - MEASURED: computed from real logged outcomes or a real offline/live
 *   evaluation harness run (e.g. qa/ai-eval/results/*.json, a trained
 *   classifier's held-out test-set metrics.json).
 * - HUMAN_REVIEWED: a real clinician/reviewer rated or verified this value.
 * - DERIVED: computed by a documented, deterministic formula from OTHER
 *   real measured/reviewed inputs (e.g. a weighted composite score) --
 *   trustworthy only as far as its inputs are.
 * - HEURISTIC: a proxy formula standing in for something never actually
 *   measured (e.g. "citations.length > 0 ? 0.02 : 0.05" as a
 *   "hallucination rate" -- a rule, not a detector).
 * - SYNTHETIC: a hardcoded literal or placeholder value, not computed from
 *   any real input at all.
 * - SEED_ONLY: explicitly demo/bootstrap data, self-identified as such,
 *   shown only so a dashboard/trend chart isn't empty.
 * - UNKNOWN: no producer asserted how this value was derived. MUST NEVER be
 *   treated as MEASURED by a consumer -- see
 *   PROMOTION_ELIGIBLE_EVALUATION_PROVENANCE below.
 */
export const EVALUATION_METRIC_PROVENANCE_VALUES = [
  'MEASURED',
  'HUMAN_REVIEWED',
  'DERIVED',
  'HEURISTIC',
  'SYNTHETIC',
  'SEED_ONLY',
  'UNKNOWN',
] as const;

export type EvaluationMetricProvenance = (typeof EVALUATION_METRIC_PROVENANCE_VALUES)[number];

export function isEvaluationMetricProvenance(value: unknown): value is EvaluationMetricProvenance {
  return (
    typeof value === 'string' &&
    (EVALUATION_METRIC_PROVENANCE_VALUES as readonly string[]).includes(value)
  );
}

/**
 * Only these provenance values may enter a "measured production quality" or
 * model-promotion aggregate pool. Every other value, including UNKNOWN,
 * must be excluded -- an absent/unrecognized provenance is not evidence of
 * quality, and must never silently default into the trusted pool.
 */
export const PROMOTION_ELIGIBLE_EVALUATION_PROVENANCE: readonly EvaluationMetricProvenance[] = [
  'MEASURED',
  'HUMAN_REVIEWED',
];

export function isPromotionEligibleEvaluationProvenance(
  provenance: EvaluationMetricProvenance,
): boolean {
  return (PROMOTION_ELIGIBLE_EVALUATION_PROVENANCE as readonly string[]).includes(provenance);
}

export type ProvenanceEvidenceKind =
  | 'retrieved_chunk'
  | 'knowledge_registry'
  | 'deterministic_calculator'
  | 'live_operational_data'
  | 'structured_rule'
  | 'user_input'
  | 'unknown';

export interface ProvenanceEvidenceItem {
  id: string;
  kind: ProvenanceEvidenceKind;
  title?: string;
  sourceId?: string;
  artifactId?: string;
  version?: string;
  excerpt?: string;
  url?: string;
  score?: number;
  evidenceGrade?: string;
  jurisdiction?: string;
}

export interface ProvenanceSourceVersion {
  sourceId: string;
  title?: string;
  version?: string;
  retrievedAt?: string;
  artifactId?: string;
}

export interface AiResponseProvenance {
  contractVersion: typeof PROVENANCE_CONTRACT_VERSION;
  /** How this response was actually produced -- see AIResponseSourceCategory above. */
  responseSource: AIResponseSourceCategory;
  evidence: ProvenanceEvidenceItem[];
  sourceVersions: ProvenanceSourceVersion[];
  confidence: number;
  missingInformation: string[];
  uncertainty: string;
  applicablePopulation: string;
  limitations: string[];
  recommendedReviewerRole: string;
  requiresClinicianReview: true;
  generatedAt: string;
  modelOrEngine?: string;
  responseClass: 'clinical' | 'operational' | 'informational' | 'error';
  /** Optional: claims stripped by entailment grounding */
  strippedClaims?: string[];
  unsupportedClaimRate?: number;
}

export interface BuildProvenanceInput {
  /**
   * Required, not inferred: this codebase's own audit history has
   * repeatedly found silent/inferred provenance defaults to the wrong
   * answer for a specific path (see AiTruthLabel.tsx and this session's
   * own findings). Every caller must state deliberately how its response
   * was produced.
   */
  responseSource: AIResponseSourceCategory;
  confidence?: number;
  evidence?: Array<Partial<ProvenanceEvidenceItem> & { id?: string; kind?: ProvenanceEvidenceKind }>;
  sourceVersions?: ProvenanceSourceVersion[];
  missingInformation?: string[];
  uncertainty?: string;
  applicablePopulation?: string;
  limitations?: string[];
  recommendedReviewerRole?: string;
  modelOrEngine?: string;
  responseClass?: AiResponseProvenance['responseClass'];
  strippedClaims?: string[];
  unsupportedClaimRate?: number;
  /** RAG sources shape from MedicalSource / citation panel */
  ragSources?: Array<{
    id?: string;
    title?: string;
    url?: string;
    date?: string;
    specialty?: string;
    evidenceLevel?: string;
    organization?: string;
  }>;
  ragChunks?: Array<{
    id?: string;
    text?: string;
    score?: number;
    metadata?: {
      sourceId?: string;
      title?: string;
      artifactId?: string;
      evidenceGrade?: string;
      jurisdiction?: string;
      metadata?: Record<string, unknown>;
    };
  }>;
  warnings?: string[];
  redFlags?: string[];
  missingFromData?: unknown;
}

function clamp01(n: number): number {
  if (!Number.isFinite(n)) return 0;
  return Math.min(1, Math.max(0, n));
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.map((v) => String(v)).filter((s) => s.trim().length > 0);
}

/**
 * Build a complete provenance block with safe defaults.
 * `requiresClinicianReview` is always true for this contract.
 */
export function buildAiResponseProvenance(input: BuildProvenanceInput): AiResponseProvenance {
  const evidence: ProvenanceEvidenceItem[] = [];

  for (const item of input.evidence || []) {
    evidence.push({
      id: item.id || `ev-${evidence.length + 1}`,
      kind: item.kind || 'unknown',
      title: item.title,
      sourceId: item.sourceId,
      artifactId: item.artifactId,
      version: item.version,
      excerpt: item.excerpt ? String(item.excerpt).slice(0, 280) : undefined,
      url: item.url,
      score: typeof item.score === 'number' ? clamp01(item.score) : undefined,
      evidenceGrade: item.evidenceGrade,
      jurisdiction: item.jurisdiction,
    });
  }

  for (const chunk of input.ragChunks || []) {
    const meta = chunk.metadata || {};
    const nested = (meta.metadata || {}) as Record<string, unknown>;
    evidence.push({
      id: chunk.id || `chunk-${evidence.length + 1}`,
      kind: 'retrieved_chunk',
      title: meta.title,
      sourceId: meta.sourceId,
      artifactId:
        (meta as any).artifactId ||
        (nested.artifactId as string | undefined) ||
        meta.sourceId,
      excerpt: chunk.text ? String(chunk.text).slice(0, 280) : undefined,
      score: typeof chunk.score === 'number' ? clamp01(chunk.score) : undefined,
      evidenceGrade:
        (meta as any).evidenceGrade ||
        (nested.evidenceGrade as string | undefined),
      jurisdiction:
        (meta as any).jurisdiction || (nested.jurisdiction as string | undefined),
    });
  }

  for (const source of input.ragSources || []) {
    if (!source?.id) continue;
    if (evidence.some((e) => e.sourceId === source.id || e.artifactId === source.id)) continue;
    evidence.push({
      id: `src-${source.id}`,
      kind: 'knowledge_registry',
      title: source.title,
      sourceId: source.id,
      artifactId: source.id.startsWith('kn-') ? source.id : undefined,
      url: source.url,
      version: source.date,
      evidenceGrade: source.evidenceLevel,
    });
  }

  const sourceVersions: ProvenanceSourceVersion[] = [
    ...(input.sourceVersions || []),
  ];
  for (const ev of evidence) {
    const sid = ev.artifactId || ev.sourceId;
    if (!sid) continue;
    if (sourceVersions.some((s) => s.sourceId === sid || s.artifactId === sid)) continue;
    sourceVersions.push({
      sourceId: sid,
      title: ev.title,
      version: ev.version,
      artifactId: ev.artifactId,
      retrievedAt: new Date().toISOString(),
    });
  }

  const missingInformation = unique([
    ...asStringArray(input.missingInformation),
    ...asStringArray(input.missingFromData),
  ]);

  const limitations = unique([
    ...(input.limitations || []),
    'Decision support only — not a diagnosis, prescription, or autonomous clinical order.',
    'Verify against primary sources and bedside assessment before acting.',
    evidence.length === 0
      ? 'No retrieved evidence was attached; treat as ungrounded draft guidance.'
      : '',
  ].filter(Boolean));

  const NO_REAL_CONFIDENCE_SOURCES: readonly AIResponseSourceCategory[] = [
    'UNAVAILABLE',
    'STATIC_CONTENT',
    'FIXTURE_DEMO',
  ];
  const confidence = clamp01(
    typeof input.confidence === 'number'
      ? input.confidence
      : NO_REAL_CONFIDENCE_SOURCES.includes(input.responseSource)
        ? 0
        : evidence.length
          ? 0.55
          : 0.25,
  );

  const uncertainty =
    input.uncertainty ||
    (missingInformation.length
      ? `Incomplete inputs: ${missingInformation.slice(0, 5).join(', ')}.`
      : evidence.length
        ? 'Evidence attached; residual uncertainty remains until clinician review.'
        : 'Low grounding: limited or no supporting evidence retrieved.');

  const redFlags = asStringArray(input.redFlags);
  const recommendedReviewerRole =
    input.recommendedReviewerRole ||
    (redFlags.length ? 'emergency_physician' : 'Responsible clinician');

  return {
    contractVersion: PROVENANCE_CONTRACT_VERSION,
    responseSource: input.responseSource,
    evidence,
    sourceVersions,
    confidence,
    missingInformation,
    uncertainty,
    applicablePopulation:
      input.applicablePopulation ||
      'Adult emergency / acute care operational context unless otherwise specified; not a universal protocol.',
    limitations,
    recommendedReviewerRole,
    requiresClinicianReview: true,
    generatedAt: new Date().toISOString(),
    modelOrEngine: input.modelOrEngine,
    responseClass: input.responseClass || (evidence.length ? 'clinical' : 'informational'),
    ...(input.strippedClaims?.length ? { strippedClaims: input.strippedClaims } : {}),
    ...(typeof input.unsupportedClaimRate === 'number'
      ? { unsupportedClaimRate: clamp01(input.unsupportedClaimRate) }
      : {}),
  };
}

export function isAiResponseProvenance(value: unknown): value is AiResponseProvenance {
  if (!value || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  return (
    v.contractVersion === PROVENANCE_CONTRACT_VERSION &&
    isAiResponseSourceCategory(v.responseSource) &&
    Array.isArray(v.evidence) &&
    Array.isArray(v.sourceVersions) &&
    typeof v.confidence === 'number' &&
    Array.isArray(v.missingInformation) &&
    typeof v.uncertainty === 'string' &&
    typeof v.applicablePopulation === 'string' &&
    Array.isArray(v.limitations) &&
    typeof v.recommendedReviewerRole === 'string' &&
    v.requiresClinicianReview === true &&
    typeof v.generatedAt === 'string'
  );
}

function unique(items: string[]): string[] {
  return [...new Set(items.map((s) => s.trim()).filter(Boolean))];
}
