import { CANONICAL_ROUTES } from './routes.config';

export const CARE_DROID_PAGE_ROLES = Object.freeze({
  admin: 'admin',
  doctor: 'physician',
  nurse: 'charge_nurse',
  triageNurse: 'triage_nurse',
  reception: 'registration_clerk',
  manager: 'ed_manager',
});

/**
 * ED OS page architecture — every surface maps to a journey stage with
 * operational state, ownership, and next-action contract.
 */
export const CARE_DROID_PAGE_ARCHITECTURE = Object.freeze([
  {
    id: 'dispatch',
    label: 'Dispatch',
    path: CANONICAL_ROUTES.emergencyDispatch,
    targetPath: CANONICAL_ROUTES.emergencyDispatch,
    icon: 'dispatch',
    roles: [CARE_DROID_PAGE_ROLES.manager, CARE_DROID_PAGE_ROLES.nurse],
    priority: 1,
    purpose:
      'Capture emergency signals, triage 911 calls, and dispatch EMS within the 3-minute response window.',
    workflow: 'pre-arrival',
    journeyPhase: 'pre-arrival',
    ownerRole: 'Dispatcher',
  },
  {
    id: 'ems',
    label: 'EMS Pipeline',
    path: CANONICAL_ROUTES.emergencyEms,
    targetPath: CANONICAL_ROUTES.emergencyEms,
    icon: 'ems',
    roles: [CARE_DROID_PAGE_ROLES.nurse, CARE_DROID_PAGE_ROLES.manager],
    priority: 2,
    purpose:
      'Coordinate inbound EMS, pre-arrival packets, offload pressure, and EMS-to-ED handoffs.',
    workflow: 'pre-arrival',
    journeyPhase: 'pre-arrival',
    ownerRole: 'EMS coordinator',
  },
  {
    id: 'ed-readiness',
    label: 'ED Readiness',
    path: CANONICAL_ROUTES.emergencyEdReadiness,
    targetPath: CANONICAL_ROUTES.emergencyEdReadiness,
    icon: 'ed-readiness',
    roles: [CARE_DROID_PAGE_ROLES.nurse, CARE_DROID_PAGE_ROLES.manager],
    priority: 3,
    purpose: 'Prepare rooms, staff, equipment, and specialty teams before patient arrival.',
    workflow: 'pre-arrival',
    journeyPhase: 'pre-arrival',
    ownerRole: 'Charge nurse',
  },
  {
    id: 'reception',
    label: 'Reception',
    path: CANONICAL_ROUTES.emergencyReception,
    targetPath: CANONICAL_ROUTES.emergencyReception,
    icon: 'reception',
    roles: [CARE_DROID_PAGE_ROLES.reception, CARE_DROID_PAGE_ROLES.nurse],
    priority: 4,
    purpose: 'Register arrivals, verify identity, capture complaint, and hand off to triage.',
    workflow: 'arrival-intake',
    journeyPhase: 'arrival-intake',
    ownerRole: 'Registration clerk',
  },
  {
    id: 'command-center',
    label: 'Hospital Command Center',
    path: CANONICAL_ROUTES.emergencyCommandCenter,
    targetPath: CANONICAL_ROUTES.emergencyCommandCenter,
    icon: 'activity',
    roles: [
      CARE_DROID_PAGE_ROLES.admin,
      CARE_DROID_PAGE_ROLES.doctor,
      CARE_DROID_PAGE_ROLES.nurse,
      CARE_DROID_PAGE_ROLES.manager,
    ],
    priority: 5,
    purpose:
      'Real-time ED operational awareness — occupancy, waits, staff, EMS, bottlenecks, alerts, AI recommendations, and 3-minute compliance in one picture.',
    workflow: 'journey-orchestration',
    journeyPhase: 'triage-assessment',
    ownerRole: 'ED manager',
  },
  {
    id: 'whiteboard',
    label: 'Whiteboard',
    path: CANONICAL_ROUTES.emergencyWhiteboard,
    targetPath: CANONICAL_ROUTES.emergencyWhiteboard,
    icon: 'whiteboard',
    roles: [
      CARE_DROID_PAGE_ROLES.doctor,
      CARE_DROID_PAGE_ROLES.nurse,
      CARE_DROID_PAGE_ROLES.triageNurse,
    ],
    priority: 6,
    purpose: 'Department flow, who-next, patient cards, capacity, and reassessment signals.',
    workflow: 'clinical-action',
    journeyPhase: 'triage-assessment',
    ownerRole: 'Charge nurse',
  },
  {
    id: 'triage',
    label: 'Triage',
    path: CANONICAL_ROUTES.triage,
    targetPath: `${CANONICAL_ROUTES.emergencyQueues}?queue=pretriage`,
    icon: 'stethoscope',
    roles: [CARE_DROID_PAGE_ROLES.triageNurse, CARE_DROID_PAGE_ROLES.nurse],
    priority: 7,
    purpose: 'Acuity assignment, vitals, red flags, AI triage support, and clinician override.',
    workflow: 'triage-assessment',
    journeyPhase: 'triage-assessment',
    ownerRole: 'Triage nurse',
  },
  {
    id: 'alerts',
    label: 'Alerts',
    path: CANONICAL_ROUTES.alerts,
    targetPath: CANONICAL_ROUTES.emergencyAlerts,
    icon: 'alerts',
    roles: [
      CARE_DROID_PAGE_ROLES.doctor,
      CARE_DROID_PAGE_ROLES.nurse,
      CARE_DROID_PAGE_ROLES.triageNurse,
      CARE_DROID_PAGE_ROLES.manager,
    ],
    priority: 8,
    purpose: 'Critical alert acknowledgement, escalation, and 3-minute response compliance.',
    workflow: 'critical-alerts',
    journeyPhase: 'triage-assessment',
    ownerRole: 'Assigned clinician',
  },
  {
    id: 'diagnostics',
    label: 'Diagnostics',
    path: CANONICAL_ROUTES.emergencyDiagnostics,
    targetPath: CANONICAL_ROUTES.emergencyDiagnostics,
    icon: 'diagnostics',
    roles: [CARE_DROID_PAGE_ROLES.doctor, CARE_DROID_PAGE_ROLES.nurse],
    priority: 9,
    purpose: 'Coordinate lab, imaging, ECG, pharmacy review, and consult orders.',
    workflow: 'diagnostics-treatment',
    journeyPhase: 'diagnostics-treatment',
    ownerRole: 'Physician',
  },
  {
    id: 'copilot',
    label: 'AI Chief',
    path: CANONICAL_ROUTES.aiChief,
    targetPath: CANONICAL_ROUTES.emergencyCopilot,
    icon: 'ed-copilot',
    roles: [
      CARE_DROID_PAGE_ROLES.doctor,
      CARE_DROID_PAGE_ROLES.nurse,
      CARE_DROID_PAGE_ROLES.triageNurse,
    ],
    priority: 10,
    purpose: 'Case-aware AI recommendations for triage, routing, and clinical next steps.',
    workflow: 'ai-journey',
    journeyPhase: 'triage-assessment',
    ownerRole: 'Clinician',
  },
  {
    id: 'referrals',
    label: 'Referrals',
    path: CANONICAL_ROUTES.emergencyReferrals,
    targetPath: CANONICAL_ROUTES.emergencyReferrals,
    icon: 'referrals',
    roles: [CARE_DROID_PAGE_ROLES.doctor, CARE_DROID_PAGE_ROLES.nurse],
    priority: 11,
    purpose: 'Consult, transfer, admission, and disposition coordination.',
    workflow: 'disposition-handoff',
    journeyPhase: 'disposition-handoff',
    ownerRole: 'Physician',
  },
  {
    id: 'handoffs',
    label: 'Handoffs',
    path: CANONICAL_ROUTES.emergencyHandoffs,
    targetPath: CANONICAL_ROUTES.emergencyHandoffs,
    icon: 'handoffs',
    roles: [CARE_DROID_PAGE_ROLES.nurse, CARE_DROID_PAGE_ROLES.doctor],
    priority: 12,
    purpose: 'Structured EMS, admission, transfer, and discharge handoff readiness.',
    workflow: 'disposition-handoff',
    journeyPhase: 'disposition-handoff',
    ownerRole: 'Charge nurse',
  },
  {
    id: 'capacity',
    label: 'Capacity',
    path: CANONICAL_ROUTES.departments,
    targetPath: CANONICAL_ROUTES.emergencyCapacity,
    icon: 'capacity',
    roles: [CARE_DROID_PAGE_ROLES.nurse, CARE_DROID_PAGE_ROLES.manager],
    priority: 13,
    purpose: 'Room pressure, boarding load, bed availability, and flow bottlenecks.',
    workflow: 'disposition-handoff',
    journeyPhase: 'disposition-handoff',
    ownerRole: 'Patient flow coordinator',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    path: CANONICAL_ROUTES.analytics,
    targetPath: CANONICAL_ROUTES.emergencyAnalytics,
    icon: 'emergency-analytics',
    roles: [CARE_DROID_PAGE_ROLES.admin, CARE_DROID_PAGE_ROLES.manager],
    priority: 14,
    purpose: 'Wait time, triage time, throughput, occupancy, and operational KPIs.',
    workflow: 'reporting-analytics',
    journeyPhase: 'reporting-analytics',
    ownerRole: 'ED manager',
  },
  {
    id: 'reports',
    label: 'Reports',
    path: CANONICAL_ROUTES.reports,
    targetPath: CANONICAL_ROUTES.emergencyReports,
    icon: 'report',
    roles: [CARE_DROID_PAGE_ROLES.admin, CARE_DROID_PAGE_ROLES.manager],
    priority: 15,
    purpose: 'Response compliance, bottleneck outcomes, and exportable operational summaries.',
    workflow: 'reporting-analytics',
    journeyPhase: 'reporting-analytics',
    ownerRole: 'Quality safety officer',
  },
  {
    id: 'settings',
    label: 'Settings',
    path: CANONICAL_ROUTES.emergencySettings,
    targetPath: CANONICAL_ROUTES.emergencySettings,
    icon: 'settings',
    roles: [CARE_DROID_PAGE_ROLES.admin, CARE_DROID_PAGE_ROLES.manager],
    priority: 16,
    purpose: 'Hospital configuration, roles, thresholds, AI safety, and notification rules.',
    workflow: 'platform-admin',
    journeyPhase: 'reporting-analytics',
    ownerRole: 'IT administrator',
  },
]);

export const CARE_DROID_PATIENT_PROFILE_PAGE = Object.freeze({
  id: 'patient-profile',
  label: 'Patient Profile',
  path: CANONICAL_ROUTES.patientProfile,
  targetPath: CANONICAL_ROUTES.emergencyPatients,
  purpose:
    'Single source of truth for patient summary, timeline, vitals, red flags, assigned staff, AI summary, handoff, and next action.',
  workflow: 'patient-journey',
  journeyPhase: 'triage-assessment',
  ownerRole: 'Care team',
});

export const CARE_DROID_WORKFLOW_MAP = Object.freeze({
  patientJourney: Object.freeze([
    'Emergency call or walk-in',
    'Pre-arrival (EMS + ED readiness)',
    'Reception and registration',
    'Triage and acuity',
    'Diagnostics and treatment',
    'Disposition and handoff',
    'Reporting and analytics feedback',
  ]),
  preArrival: Object.freeze([
    'Emergency signal',
    '911 dispatch',
    'EMS en route',
    'Hospital pre-arrival',
    'ED readiness activation',
  ]),
  criticalAlertJourney: Object.freeze([
    'Alert generated',
    'Dashboard banner',
    'Alerts page',
    'AI Chief recommendation',
    'Assigned staff acknowledgement',
    'Escalation if delayed',
    'Patient profile update',
    'Analytics and reporting',
  ]),
  aiJourney: Object.freeze([
    'Clinical or operational event',
    'Frontend hook/client',
    'Centralized AI node',
    'Structured AI response',
    'Reusable AI UI component',
    'Clinician review',
    'Accepted, modified, dismissed, or escalated action',
    'Audit trail when supported',
  ]),
});

export const CARE_DROID_LAYOUT_COMPONENTS = Object.freeze([
  'AppShell',
  'Sidebar',
  'Header',
  'PageHeader',
  'EdJourneyProgressRail',
  'WorkflowSituationBrief',
  'DashboardGrid',
  'MetricGrid',
  'DashboardSection',
  'PageShell',
  'OperationalEmptyState',
  'EmptyState',
  'ErrorState',
  'LoadingState',
]);
