import { CANONICAL_ROUTES } from './routes.config';

export const EMERGENCY_OS_ROUTE_COMMANDS = Object.freeze([
  {
    id: 'open-whiteboard',
    label: 'Open Whiteboard',
    hint: 'W',
    keywords: ['whiteboard', 'board', 'patient flow', 'operational screen'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyWhiteboard }),
  },
  {
    id: 'open-patients',
    label: 'Open Patients',
    hint: 'P',
    keywords: ['patients', 'patient list', 'snapshots'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyPatients }),
  },
  {
    id: 'open-journey',
    label: 'Open Patient Journey',
    hint: 'J',
    keywords: ['journey', 'patient journey', 'flow events', 'state transitions'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyJourney }),
  },
  {
    id: 'open-ems',
    label: 'Open EMS',
    hint: 'E',
    keywords: ['ems', 'pre-arrival', 'ambulance', 'pipeline'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyEms }),
  },
  {
    id: 'open-intake',
    label: 'Open Smart Intake',
    hint: 'I',
    keywords: ['intake', 'arrival', 'identity', 'registration', 'ocr'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyIntake }),
  },
  {
    id: 'open-queues',
    label: 'Open Queues',
    hint: 'Q',
    keywords: ['queues', 'queue intelligence', 'waiting', 'who next'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyQueues }),
  },
  {
    id: 'open-reassessment',
    label: 'Open Reassessment',
    hint: 'R',
    keywords: ['reassessment', 'due', 'safety', 'review'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyReassessment }),
  },
  {
    id: 'open-capacity',
    label: 'Open Capacity',
    hint: 'C',
    keywords: ['capacity', 'rooms', 'pressure', 'occupancy'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyCapacity }),
  },
  {
    id: 'open-boarding',
    label: 'Open Boarding',
    hint: 'B',
    keywords: ['boarding', 'admission pending', 'boarders'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyBoarding }),
  },
  {
    id: 'open-referrals',
    label: 'Open Referrals',
    hint: 'Ref',
    keywords: ['referrals', 'consults', 'transfer', 'specialty'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyReferrals }),
  },
  {
    id: 'open-provincial-health',
    label: 'Open Provincial Health',
    hint: 'PH',
    keywords: ['provincial health', 'ohip', 'hie', 'external records', 'medications', 'allergies'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyProvincialHealth }),
  },
  {
    id: 'open-integrations',
    label: 'Open Integration Hub',
    hint: 'Hub',
    keywords: ['integrations', 'integration hub', 'fhir', 'hl7', 'iot', 'devices'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyIntegrations }),
  },
  {
    id: 'open-copilot',
    label: 'Open ED Copilot',
    hint: 'AI',
    keywords: ['copilot', 'assistant', 'ai', 'chat'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyCopilot }),
  },
  {
    id: 'open-analytics',
    label: 'Open Analytics',
    hint: 'A',
    keywords: ['analytics', 'throughput', 'metrics', 'trends'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyAnalytics }),
  },
  {
    id: 'open-simulation',
    label: 'Open Real-Time Simulation',
    hint: 'Sim',
    keywords: ['simulation', 'real-time simulation', 'rts', 'interventions', 'forecast'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencySimulation }),
  },
  {
    id: 'open-federated-learning',
    label: 'Open Federated Learning',
    hint: 'FL',
    keywords: ['federated learning', 'fedavg', 'multi hospital', 'model aggregation'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyFederatedLearning }),
  },
  {
    id: 'open-digital-twin',
    label: 'Open Digital Twin',
    hint: 'Twin',
    keywords: ['digital twin', 'des', 'abm', 'simulation twin', 'operations twin'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyDigitalTwin }),
  },
  {
    id: 'open-ai-governance',
    label: 'Open AI Governance',
    hint: 'G',
    keywords: ['ai governance', 'governance', 'safety', 'compliance', 'model inventory'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.aiGovernance }),
  },
  {
    id: 'open-settings',
    label: 'Open Settings',
    hint: 'S',
    keywords: ['settings', 'thresholds', 'staff', 'configuration'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencySettings }),
  },
]);
