import { CANONICAL_ROUTES } from './routes.config';

export const EMERGENCY_OS_ROUTE_COMMANDS = Object.freeze([
  {
    id: 'open-whiteboard',
    label: 'Open Whiteboard',
    hint: 'W',
    keywords: ['whiteboard', 'board', 'patient flow', 'operational screen'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyWhiteboard }),
  },
  {
    id: 'open-patients',
    label: 'Open Patients',
    hint: 'P',
    keywords: ['patients', 'patient list', 'snapshots'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyPatients }),
  },
  {
    id: 'open-ems',
    label: 'Open EMS',
    hint: 'E',
    keywords: ['ems', 'pre-arrival', 'ambulance', 'pipeline'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyEms }),
  },
  {
    id: 'open-intake',
    label: 'Open Smart Intake',
    hint: 'I',
    keywords: ['intake', 'arrival', 'identity', 'registration', 'ocr'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyIntake }),
  },
  {
    id: 'open-queues',
    label: 'Open Queues',
    hint: 'Q',
    keywords: ['queues', 'queue intelligence', 'waiting', 'who next'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyQueues }),
  },
  {
    id: 'open-reassessment',
    label: 'Open Reassessment',
    hint: 'R',
    keywords: ['reassessment', 'due', 'safety', 'review'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyReassessment }),
  },
  {
    id: 'open-capacity',
    label: 'Open Capacity',
    hint: 'C',
    keywords: ['capacity', 'rooms', 'pressure', 'occupancy'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyCapacity }),
  },
  {
    id: 'open-boarding',
    label: 'Open Boarding',
    hint: 'B',
    keywords: ['boarding', 'admission pending', 'boarders'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyBoarding }),
  },
  {
    id: 'open-referrals',
    label: 'Open Referrals',
    hint: 'Ref',
    keywords: ['referrals', 'consults', 'transfer', 'specialty'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyReferrals }),
  },
  {
    id: 'open-copilot',
    label: 'Open ED Copilot',
    hint: 'AI',
    keywords: ['copilot', 'assistant', 'ai', 'chat'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyCopilot }),
  },
  {
    id: 'open-clinical-tools',
    label: 'Open Clinical Tools',
    hint: 'T',
    keywords: ['tools', 'calculators', 'clinical tools', 'heart', 'qsofa'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyTools }),
  },
  {
    id: 'open-analytics',
    label: 'Open Analytics',
    hint: 'A',
    keywords: ['analytics', 'throughput', 'metrics', 'trends'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyAnalytics }),
  },
  {
    id: 'open-department-pulse',
    label: 'Open Department Pulse',
    hint: 'Pulse',
    keywords: ['pulse', 'charge nurse', 'department status', 'operations'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyPulse }),
  },
  {
    id: 'open-ai-governance',
    label: 'Open AI Governance',
    hint: 'Gov',
    keywords: ['governance', 'ai governance', 'safety', 'audit'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyAiGovernance }),
  },
  {
    id: 'open-shift-summary',
    label: 'Open Shift Summary',
    hint: 'Shift',
    keywords: ['shift', 'handoff', 'summary', 'charge nurse'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencyShift }),
  },
  {
    id: 'open-settings',
    label: 'Open Settings',
    hint: 'S',
    keywords: ['settings', 'thresholds', 'staff', 'configuration'],
    build: () => ({ type: 'OPEN_ROUTE', path: CANONICAL_ROUTES.emergencySettings }),
  },
]);
