/**
 * Canonical route and alias configuration.
 *
 * React Router still owns rendering in `App.jsx`; this module owns stable paths
 * and redirect aliases so route consumers do not define competing maps.
 */

export const CANONICAL_ROUTES = Object.freeze({
  auth: '/auth',
  authCallback: '/auth-callback',
  dashboard: '/dashboard',
  discover: '/discover',
  automation: '/automation',
  automationAudit: '/automation-audit',
  assistant: '/assistant',
  tools: '/tools',
  operations: '/operations',
  operationsCenter: '/operations-center',
  calculators: '/tools/calculators',
  calculatorDetail: '/tools/calculators/:slug',
  protocols: '/protocols',
  research: '/research',
  documentation: '/documentation',
  knowledgeGraph: '/knowledge-graph',
  predictiveAnalytics: '/predictive-analytics',
  clinicalDecisionSupport: '/clinical-decision-support',
  competencies: '/competencies',
  credentials: '/credentials',
  simulation: '/simulation',
  simulationOutcomes: '/simulation/outcomes',
  laboratory: '/laboratory',
  medical3dViewer: '/3d-viewer',
  liveMap: '/live-map',
  hospitalMap: '/hospital-map',
  medicalIot: '/medical-iot',
  devices: '/devices',
  fleetCommand: '/fleet/command',
  fleetMap: '/fleet/map',
  digitalTwin: '/digital-twin',
  profile: '/profile',
  profileSettings: '/profile/settings',
  profileToolPreferences: '/profile/tool-preferences',
  settings: '/settings',
  customerPortal: '/customer-portal',
  knowledgeBase: '/knowledge-base',
  marketplace: '/marketplace',
  enterpriseReadiness: '/enterprise-readiness',
  platformAdmin: '/platform-admin',
  billing: '/billing',
  usage: '/usage',
  notifications: '/notifications',
  timeline: '/timeline',
  workflows: '/workflows',
  search: '/search',
  developerCatalog: '/tools/catalog',
  plugins: '/plugins',
  featureFlags: '/feature-flags',
  dependencyMap: '/dependency-map',
  dependencyGraph: '/dependency-graph',
  dataLineage: '/data-lineage',
  selfDiagnostics: '/self-diagnostics',
  systemHealth: '/system-health',
  saasHealth: '/saas-health',
  governanceRegistry: '/governance-registry',
  aiGovernance: '/ai-governance',
  security: '/security',
  audit: '/audit',
  regulatory: '/regulatory',
  humanReview: '/human-review',
  assets: '/assets',
  artifacts: '/artifacts',
  aiModels: '/ai-models',
  organization: '/organization',
  organizationSettings: '/settings/organization',
  tenantAdmin: '/tenant-admin',
  organizationPacks: '/settings/organization/packs',
  organizationAssets: '/settings/organization/assets',
  platformAnalytics: '/platform-analytics',
  departments: '/departments',
  serviceLines: '/service-lines',
  products: '/products',
  assetPacks: '/asset-packs',
  plans: '/plans',
  specialties: '/specialties',
  carePathways: '/care-pathways',
  agents: '/agents',
  maturityAssessment: '/maturity-assessment',
  outcomes: '/outcomes',
  valueTracking: '/value-tracking',
  customerSuccess: '/customer-success',
  successCenter: '/success-center',
  integrationsMarketplace: '/integrations-marketplace',
  integrationReadiness: '/integration-readiness',
  solutionBuilder: '/solution-builder',
  configurationStudio: '/configuration-studio',
  welcome: '/welcome',
  onboarding: '/onboarding',
});

export const AUTH_PATH_ALIASES = Object.freeze([
  '/login',
  '/log-in',
  '/signin',
  '/sign-in',
  '/signup',
  '/sign-up',
  '/register',
  '/join',
  '/create-account',
  '/account/login',
  '/account/signup',
  '/account/register',
  '/accounts/login',
  '/accounts/signup',
]);

export const AUTH_SIGNUP_PATH_ALIASES = Object.freeze([
  '/signup',
  '/sign-up',
  '/register',
  '/join',
  '/create-account',
  '/account/signup',
  '/account/register',
  '/accounts/signup',
]);

export const ASSISTANT_ROUTE_ALIASES = Object.freeze(['/chat', '/ai', '/copilot']);
export const TOOLS_ROUTE_ALIASES = Object.freeze(['/all-tools', '/clinical-tools', '/catalog']);
export const CALCULATORS_ROUTE_ALIASES = Object.freeze(['/calculators']);
export const SIMULATION_ROUTE_ALIASES = Object.freeze(['/medical-simulation']);
export const LABORATORY_ROUTE_ALIASES = Object.freeze(['/lab']);
export const MEDICAL_3D_VIEWER_ROUTE_ALIASES = Object.freeze(['/anatomy-viewer']);
export const LIVE_MAP_ROUTE_ALIASES = Object.freeze(['/maps', '/tracking', '/live-tracking']);
export const FLEET_MAP_ROUTE_ALIASES = Object.freeze([
  '/fleet',
  '/fleet/live-map',
  '/fleet/tracking',
]);
export const OPERATIONS_ROUTE_ALIASES = Object.freeze([]);
export const AUDIT_ROUTE_ALIASES = Object.freeze(['/audit-logs']);
export const HOME_ROUTE_ALIASES = Object.freeze(['/home']);
export const ORGANIZATION_PACKS_ROUTE_ALIASES = Object.freeze([]);

export const ROUTE_RECORDS = Object.freeze([
  Object.freeze({
    id: 'auth',
    path: CANONICAL_ROUTES.auth,
    layout: 'auth',
    auth: 'publicOnly',
    status: 'active',
    aliases: AUTH_PATH_ALIASES,
    navGroup: 'auth',
  }),
  Object.freeze({
    id: 'dashboard',
    path: CANONICAL_ROUTES.dashboard,
    componentKey: 'CommandDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: HOME_ROUTE_ALIASES,
    navGroup: 'primary',
  }),
  Object.freeze({
    id: 'assistant',
    path: CANONICAL_ROUTES.assistant,
    componentKey: 'AssistantPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: ASSISTANT_ROUTE_ALIASES,
    navGroup: 'primary',
  }),
  Object.freeze({
    id: 'knowledgeBase',
    path: CANONICAL_ROUTES.knowledgeBase,
    componentKey: 'KnowledgeBasePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
  }),
  Object.freeze({
    id: 'marketplace',
    path: CANONICAL_ROUTES.marketplace,
    componentKey: 'MarketplacePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes: 'Unified extensibility marketplace for asset packs, workflows, simulations, protocols, AI agents, and integrations.',
  }),
  Object.freeze({
    id: 'enterpriseReadiness',
    path: CANONICAL_ROUTES.enterpriseReadiness,
    componentKey: 'EnterpriseReadinessPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes: 'Enterprise readiness center with weighted SSO, RBAC, tenant isolation, audit, governance, integration, and security scoring.',
  }),
  Object.freeze({
    id: 'platformAdmin',
    path: CANONICAL_ROUTES.platformAdmin,
    componentKey: 'PlatformAdminPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes: 'SaaS operating system layer unifying organization, subscription, products, packs, assets, workspaces, users, AI agents, and automations.',
  }),
  Object.freeze({
    id: 'tools',
    path: CANONICAL_ROUTES.tools,
    componentKey: 'ToolsOverview',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: TOOLS_ROUTE_ALIASES,
    matchPrefixes: ['/tools/'],
    navGroup: 'primary',
  }),
  Object.freeze({
    id: 'calculators',
    path: CANONICAL_ROUTES.calculators,
    componentKey: 'Calculators',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: CALCULATORS_ROUTE_ALIASES,
    matchPrefixes: ['/tools/calculators/'],
    navGroup: 'tools',
  }),
  Object.freeze({
    id: 'operations',
    path: CANONICAL_ROUTES.operations,
    componentKey: 'Operations',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: OPERATIONS_ROUTE_ALIASES,
    matchPrefixes: ['/operations/'],
    navGroup: 'primary',
  }),
  Object.freeze({
    id: 'operationsCenter',
    path: CANONICAL_ROUTES.operationsCenter,
    componentKey: 'DigitalOperationsCenter',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes: 'Digital operations command surface for throughput, capacity, maps, devices, and incidents.',
  }),
  Object.freeze({
    id: 'digitalTwin',
    path: CANONICAL_ROUTES.digitalTwin,
    componentKey: 'DigitalTwinPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/digital-twin/'],
    navGroup: 'operations',
  }),
  Object.freeze({
    id: 'hospitalMap',
    path: CANONICAL_ROUTES.hospitalMap,
    componentKey: 'HospitalMapDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/hospital-map/'],
    navGroup: 'operations',
  }),
  Object.freeze({
    id: 'medicalIot',
    path: CANONICAL_ROUTES.medicalIot,
    componentKey: 'MedicalIotDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
  }),
  Object.freeze({
    id: 'devices',
    path: CANONICAL_ROUTES.devices,
    componentKey: 'DeviceFleetManagement',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
  }),
  Object.freeze({
    id: 'simulation',
    path: CANONICAL_ROUTES.simulation,
    componentKey: 'MedicalSimulationSuite',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: SIMULATION_ROUTE_ALIASES,
    matchPrefixes: ['/simulation/'],
    navGroup: 'tools',
  }),
  Object.freeze({
    id: 'laboratory',
    path: CANONICAL_ROUTES.laboratory,
    componentKey: 'LaboratoryDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: LABORATORY_ROUTE_ALIASES,
    navGroup: 'tools',
  }),
  Object.freeze({
    id: 'medical3dViewer',
    path: CANONICAL_ROUTES.medical3dViewer,
    componentKey: 'Medical3DViewer',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: MEDICAL_3D_VIEWER_ROUTE_ALIASES,
    navGroup: 'tools',
  }),
  Object.freeze({
    id: 'liveMap',
    path: CANONICAL_ROUTES.liveMap,
    componentKey: 'LiveTrackingMap',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: LIVE_MAP_ROUTE_ALIASES,
    navGroup: 'operations',
  }),
  Object.freeze({
    id: 'fleetMap',
    path: CANONICAL_ROUTES.fleetMap,
    componentKey: 'FleetLiveMap',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: FLEET_MAP_ROUTE_ALIASES,
    matchPrefixes: ['/fleet/'],
    navGroup: 'operations',
  }),
  Object.freeze({
    id: 'fleetCommand',
    path: CANONICAL_ROUTES.fleetCommand,
    componentKey: 'FleetDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes: 'Fleet command dashboard retained as an operations detail route while /fleet/map is the canonical map entry.',
  }),
  Object.freeze({
    id: 'audit',
    path: CANONICAL_ROUTES.audit,
    componentKey: 'PlatformGovernanceWorkspace',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: AUDIT_ROUTE_ALIASES,
    matchPrefixes: ['/audit/'],
    navGroup: 'advanced',
  }),
  Object.freeze({
    id: 'assetPacks',
    path: CANONICAL_ROUTES.assetPacks,
    componentKey: 'PackMarketplace',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Canonical organization-aware asset pack marketplace.',
  }),
  Object.freeze({
    id: 'organization',
    path: CANONICAL_ROUTES.organization,
    componentKey: 'OrganizationDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/organization/'],
    navGroup: 'organization',
    notes: 'Tenant organization dashboard and settings entry point.',
  }),
  Object.freeze({
    id: 'platformAnalytics',
    path: CANONICAL_ROUTES.platformAnalytics,
    componentKey: 'PlatformAnalyticsPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes: 'Tenant analytics for usage, adoption, automation, and value signals.',
  }),
  Object.freeze({
    id: 'products',
    path: CANONICAL_ROUTES.products,
    componentKey: 'ProductsIndexPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/products/'],
    navGroup: 'products',
    notes: 'Sellable CareDroid product catalog mapped to packs and assets.',
  }),
  Object.freeze({
    id: 'plans',
    path: CANONICAL_ROUTES.plans,
    componentKey: 'CommercialPlansPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Subscription plan catalog mapped to included products and packs.',
  }),
  Object.freeze({
    id: 'specialties',
    path: CANONICAL_ROUTES.specialties,
    componentKey: 'SpecialtiesIndexPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/specialties/'],
    navGroup: 'products',
  }),
  Object.freeze({
    id: 'carePathways',
    path: CANONICAL_ROUTES.carePathways,
    componentKey: 'CarePathwaysIndexPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/care-pathways/'],
    navGroup: 'products',
  }),
  Object.freeze({
    id: 'agents',
    path: CANONICAL_ROUTES.agents,
    componentKey: 'AgentsRegistryPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'AI agent registry mounted to products, packs, workspaces, and role profiles.',
  }),
  Object.freeze({
    id: 'maturityAssessment',
    path: CANONICAL_ROUTES.maturityAssessment,
    componentKey: 'MaturityAssessmentPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
  }),
  Object.freeze({
    id: 'outcomes',
    path: CANONICAL_ROUTES.outcomes,
    componentKey: 'OutcomesDashboardPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
  }),
  Object.freeze({
    id: 'integrationsMarketplace',
    path: CANONICAL_ROUTES.integrationsMarketplace,
    componentKey: 'IntegrationsMarketplacePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Integration marketplace route documented as product/system purpose until integration assets are launchable.',
  }),
  Object.freeze({
    id: 'departments',
    path: CANONICAL_ROUTES.departments,
    componentKey: 'DepartmentsPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Department-to-asset mapping across packs, assets, roles, permissions, and users.',
  }),
  Object.freeze({
    id: 'serviceLines',
    path: CANONICAL_ROUTES.serviceLines,
    componentKey: 'ServiceLinesPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Service-line architecture across departments, asset packs, and assets.',
  }),
  Object.freeze({
    id: 'integrationReadiness',
    path: CANONICAL_ROUTES.integrationReadiness,
    componentKey: 'IntegrationReadinessPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Integration readiness across interoperability, identity, government, and scheduling systems.',
  }),
  Object.freeze({
    id: 'configurationStudio',
    path: CANONICAL_ROUTES.configurationStudio,
    componentKey: 'ConfigurationStudioPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'No-code configuration studio for tenant-safe product and pack setup.',
  }),
  Object.freeze({
    id: 'solutionBuilder',
    path: CANONICAL_ROUTES.solutionBuilder,
    componentKey: 'HospitalSolutionBuilderPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'No-code hospital deployment recommendation and apply workflow.',
  }),
  Object.freeze({
    id: 'valueTracking',
    path: CANONICAL_ROUTES.valueTracking,
    componentKey: 'ValueTrackingPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Clinical, operational, and executive value tracking framework.',
  }),
  Object.freeze({
    id: 'customerSuccess',
    path: CANONICAL_ROUTES.customerSuccess,
    componentKey: 'CustomerSuccessDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Customer health and retention dashboard for adoption and usage signals.',
  }),
  Object.freeze({
    id: 'customerPortal',
    path: CANONICAL_ROUTES.customerPortal,
    componentKey: 'CustomerPortalPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes: 'Tenant-scoped customer portal for subscription, entitlements, organization profile, users, integrations, invoices, support, and release notes.',
  }),
  Object.freeze({
    id: 'successCenter',
    path: CANONICAL_ROUTES.successCenter,
    componentKey: 'SuccessCenterPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Tenant-scoped success center for adoption, workspace adoption, asset usage, AI usage, simulation, workflow, onboarding, and health score.',
  }),
  Object.freeze({
    id: 'billing',
    path: CANONICAL_ROUTES.billing,
    componentKey: 'BillingPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes: 'Organization subscription billing and plan limit overview.',
  }),
  Object.freeze({
    id: 'usage',
    path: CANONICAL_ROUTES.usage,
    componentKey: 'UsagePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes: 'Organization usage metering by workspace, asset, role, and period.',
  }),
  Object.freeze({
    id: 'saasHealth',
    path: CANONICAL_ROUTES.saasHealth,
    componentKey: 'SaasHealthCenter',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes: 'SaaS health center for frontend, backend, API, integrations, tenant, AI, and simulation health.',
  }),
  Object.freeze({
    id: 'governanceRegistry',
    path: CANONICAL_ROUTES.governanceRegistry,
    componentKey: 'GovernanceRegistry',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes: 'Platform governance registry for owner, steward, approver, risk, evidence, version, audit, and review schedules.',
  }),
  Object.freeze({
    id: 'dependencyGraph',
    path: CANONICAL_ROUTES.dependencyGraph,
    componentKey: 'DependencyGraph',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes: 'Asset dependency graph across products, packs, assets, routes, backend services, and integrations.',
  }),
  Object.freeze({
    id: 'artifacts',
    path: CANONICAL_ROUTES.artifacts,
    componentKey: 'Artifacts',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes: 'Machine-learning-ready artifact intelligence catalog with CSV/JSON export, feature rows, and resonance metadata.',
  }),
  Object.freeze({
    id: 'knowledgeGraph',
    path: CANONICAL_ROUTES.knowledgeGraph,
    componentKey: 'ClinicalKnowledgeGraph',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes: 'Artifact knowledge graph across assets, packs, products, workspaces, roles, routes, simulations, workflows, AI agents, and integrations.',
  }),
  Object.freeze({
    id: 'aiModels',
    path: CANONICAL_ROUTES.aiModels,
    componentKey: 'AiModelsPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes: 'Unified AI model registry for gateway, MoE, RAG, tool calling, resonance, tutoring, cost, guardrails, and evaluation systems.',
  }),
  Object.freeze({
    id: 'tenantAdmin',
    path: CANONICAL_ROUTES.tenantAdmin,
    componentKey: 'TenantAdministrationCenter',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes: 'Tenant-scoped organization administration center for no-code customer configuration.',
  }),
  Object.freeze({
    id: 'organizationPacks',
    path: CANONICAL_ROUTES.organizationPacks,
    componentKey: 'PackMarketplace',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: ORGANIZATION_PACKS_ROUTE_ALIASES,
    navGroup: 'organization',
    notes: 'Organization-specific pack marketplace and entitlement management.',
  }),
  Object.freeze({
    id: 'workflows',
    path: CANONICAL_ROUTES.workflows,
    componentKey: 'WorkflowBuilderPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'secondary',
    notes: 'Workflow route kept distinct while /automation merge decision remains pending.',
  }),
]);

export const ROUTE_RECORDS_BY_ID = Object.freeze(
  Object.fromEntries(ROUTE_RECORDS.map((record) => [record.id, record]))
);

export const ROUTE_ALIAS_REDIRECTS = Object.freeze(
  ROUTE_RECORDS.flatMap((record) =>
    (record.aliases || []).map((path) =>
      Object.freeze({
        path,
        to: record.path,
        routeId: record.id,
        auth: record.auth,
      })
    )
  )
);

export const PROTECTED_ROUTE_ALIAS_REDIRECTS = Object.freeze(
  ROUTE_ALIAS_REDIRECTS.filter((entry) => entry.auth === 'required')
);

function aliasesForRoute(id) {
  return ROUTE_RECORDS_BY_ID[id]?.aliases || Object.freeze([]);
}

export const ROUTE_ALIAS_GROUPS = Object.freeze({
  auth: Object.freeze({ target: CANONICAL_ROUTES.auth, aliases: aliasesForRoute('auth') }),
  dashboard: Object.freeze({
    target: CANONICAL_ROUTES.dashboard,
    aliases: aliasesForRoute('dashboard'),
  }),
  assistant: Object.freeze({
    target: CANONICAL_ROUTES.assistant,
    aliases: aliasesForRoute('assistant'),
  }),
  knowledgeBase: Object.freeze({
    target: CANONICAL_ROUTES.knowledgeBase,
    aliases: aliasesForRoute('knowledgeBase'),
  }),
  marketplace: Object.freeze({
    target: CANONICAL_ROUTES.marketplace,
    aliases: aliasesForRoute('marketplace'),
  }),
  enterpriseReadiness: Object.freeze({
    target: CANONICAL_ROUTES.enterpriseReadiness,
    aliases: aliasesForRoute('enterpriseReadiness'),
  }),
  platformAdmin: Object.freeze({
    target: CANONICAL_ROUTES.platformAdmin,
    aliases: aliasesForRoute('platformAdmin'),
  }),
  tools: Object.freeze({ target: CANONICAL_ROUTES.tools, aliases: aliasesForRoute('tools') }),
  calculators: Object.freeze({
    target: CANONICAL_ROUTES.calculators,
    aliases: aliasesForRoute('calculators'),
  }),
  simulation: Object.freeze({
    target: CANONICAL_ROUTES.simulation,
    aliases: aliasesForRoute('simulation'),
  }),
  laboratory: Object.freeze({
    target: CANONICAL_ROUTES.laboratory,
    aliases: aliasesForRoute('laboratory'),
  }),
  medical3dViewer: Object.freeze({
    target: CANONICAL_ROUTES.medical3dViewer,
    aliases: aliasesForRoute('medical3dViewer'),
  }),
  liveMap: Object.freeze({ target: CANONICAL_ROUTES.liveMap, aliases: aliasesForRoute('liveMap') }),
  fleetMap: Object.freeze({ target: CANONICAL_ROUTES.fleetMap, aliases: aliasesForRoute('fleetMap') }),
  operations: Object.freeze({
    target: CANONICAL_ROUTES.operations,
    aliases: aliasesForRoute('operations'),
  }),
  audit: Object.freeze({ target: CANONICAL_ROUTES.audit, aliases: aliasesForRoute('audit') }),
  assetPacks: Object.freeze({
    target: CANONICAL_ROUTES.assetPacks,
    aliases: aliasesForRoute('assetPacks'),
  }),
  organizationPacks: Object.freeze({
    target: CANONICAL_ROUTES.organizationPacks,
    aliases: aliasesForRoute('organizationPacks'),
  }),
});

export function getRouteAliasTarget(pathname) {
  return ROUTE_ALIAS_REDIRECTS.find((entry) => entry.path === pathname)?.to || null;
}
