/**
 * Canonical route and alias configuration.
 *
 * React Router still owns rendering in `src/app/router.tsx`; this module owns stable paths
 * and redirect aliases so route consumers do not define competing maps.
 */

export const CANONICAL_ROUTES = Object.freeze({
  auth: '/auth',
  authCallback: '/auth-callback',
  authForgotPassword: '/auth/forgot-password',
  authMagicLink: '/auth/magic-link',
  authInvite: '/auth/invite',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  platformStart: '/start',
  adminOperations: '/admin',
  adminEdStaff: '/admin/staff-workflows',
  dashboard: '/dashboard',
  intake: '/intake',
  queue: '/queue',
  triage: '/triage',
  alerts: '/alerts',
  aiChief: '/ai-chief',
  staff: '/staff',
  analytics: '/analytics',
  reports: '/reports',
  patientProfile: '/patients/:id',
  executive: '/executive',
  discover: '/discover',
  recommendations: '/recommendations',
  automation: '/automation',
  automationAudit: '/automation-audit',
  automationAnalytics: '/automation-analytics',
  assistant: '/assistant',
  aiCommandCenter: '/ai-command-center',
  tools: '/tools',
  operations: '/operations',
  emergencyWorkspace: '/emergency/whiteboard',
  emergencyWhiteboard: '/emergency/whiteboard',
  emergencyCommandCenter: '/emergency/command-center',
  emergencyPatients: '/emergency/patients',
  emergencyJourney: '/emergency/journey',
  emergencyEms: '/emergency/ems',
  emergencySmartIntake: '/emergency/intake',
  emergencyIntake: '/emergency/intake',
  emergencyReception: '/emergency/reception',
  emergencySelfArrival: '/emergency/self-arrival',
  emergencyPatientRoom: '/emergency/patient-room',
  emergencyQueues: '/emergency/queues',
  emergencyReassessment: '/emergency/reassessment',
  emergencyOperations: '/emergency/queues',
  emergencyCapacity: '/emergency/capacity',
  emergencyAnalytics: '/emergency/analytics',
  emergencySimulation: '/emergency/simulation',
  emergencyFederatedLearning: '/emergency/federated-learning',
  emergencyDigitalTwin: '/emergency/digital-twin',
  emergencyCopilot: '/emergency/copilot',
  emergencyDocumentation: '/emergency/documentation',
  emergencyBoarding: '/emergency/boarding',
  emergencyReferrals: '/emergency/referrals',
  emergencyProvincialHealth: '/emergency/provincial-health',
  emergencyIntegrations: '/emergency/integrations',
  integrationHub: '/integrations/hub',
  cosmosViewer: '/cosmos',
  emergencyAiGovernance: '/emergency/ai-governance',
  emergencyPulse: '/emergency/pulse',
  emergencyShift: '/emergency/shift',
  emergencySettings: '/emergency/settings',
  emergencyHelp: '/emergency/help',
  emergencyAlerts: '/emergency/alerts',
  emergencyTools: '/emergency/tools',
  emergencyDispatch: '/emergency/dispatch',
  emergencyEdReadiness: '/emergency/ed-readiness',
  emergencyDiagnostics: '/emergency/diagnostics',
  emergencyHandoffs: '/emergency/handoffs',
  emergencyReports: '/emergency/reports',
  workspace: '/workspace',
  workspaces: '/workspaces',
  operationsCenter: '/operations-center',
  calculators: '/tools/calculators',
  calculatorDetail: '/tools/calculators/:slug',
  protocols: '/protocols',
  research: '/research',
  documentation: '/documentation',
  knowledgeGraph: '/knowledge-graph',
  predictiveAnalytics: '/predictive-analytics',
  clinicalDecisionSupport: '/clinical-decision-support',
  competencies: '/competencies',
  credentials: '/credentials',
  simulation: '/simulation',
  simulationOutcomes: '/simulation/outcomes',
  laboratory: '/laboratory',
  medical3dViewer: '/3d-viewer',
  liveMap: '/live-map',
  hospitalMap: '/hospital-map',
  medicalIot: '/medical-iot',
  devices: '/devices',
  fleetCommand: '/fleet/command',
  fleetMap: '/fleet/map',
  surveillanceNexus: '/surveillance/nexus',
  digitalTwin: '/digital-twin',
  digitalTwinIntelligence: '/digital-twin-intelligence',
  profile: '/profile',
  profileSettings: '/profile/settings',
  profileToolPreferences: '/profile/tool-preferences',
  settings: '/settings',
  settingsFeatures: '/settings/features',
  customerPortal: '/customer-portal',
  knowledgeHub: '/knowledge-hub',
  knowledgeBase: '/knowledge-base',
  marketplace: '/marketplace',
  enterpriseReadiness: '/enterprise-readiness',
  trackMindWorkspace: '/trackmind',
  trackMindMaturity: '/trackmind-maturity',
  enterprisePlatform: '/enterprise-platform',
  platformIntelligence: '/platform-intelligence',
  platformAdmin: '/platform-admin',
  billing: '/billing',
  usage: '/usage',
  notifications: '/notifications',
  timeline: '/timeline',
  workflows: '/workflows',
  workflowMining: '/workflow-mining',
  workspaceDependencyGraph: '/workspace-dependency-graph',
  search: '/search',
  developerCatalog: '/tools/catalog',
  plugins: '/plugins',
  featureFlags: '/feature-flags',
  dependencyMap: '/dependency-map',
  dependencyGraph: '/dependency-graph',
  dataLineage: '/data-lineage',
  selfDiagnostics: '/self-diagnostics',
  systemHealth: '/system-health',
  saasHealth: '/saas-health',
  governanceRegistry: '/governance-registry',
  aiGovernance: '/ai-governance',
  security: '/security',
  audit: '/audit',
  regulatory: '/regulatory',
  humanReview: '/human-review',
  assets: '/assets',
  artifacts: '/artifacts',
  aiModels: '/ai-models',
  aiEvaluation: '/ai-evaluation',
  platformLearningEngine: '/platform-learning-engine',
  brain: '/brain',
  businessBrain: '/business-brain',
  organization: '/organization',
  organizationIntelligence: '/organization-intelligence',
  organizationSettings: '/settings/organization',
  tenantAdmin: '/tenant-admin',
  tenantAdminWorkspaces: '/tenant-admin/workspaces',
  organizationPacks: '/settings/organization/packs',
  organizationAssets: '/settings/organization/assets',
  platformAnalytics: '/platform-analytics',
  departmentIntelligence: '/department-intelligence',
  departments: '/departments',
  serviceLines: '/service-lines',
  products: '/products',
  assetPacks: '/asset-packs',
  plans: '/plans',
  specialties: '/specialties',
  carePathways: '/care-pathways',
  agents: '/agents',
  maturityAssessment: '/maturity-assessment',
  outcomes: '/outcomes',
  valueTracking: '/value-tracking',
  productIntelligence: '/product-intelligence',
  expansionOpportunities: '/expansion-opportunities',
  customerSuccess: '/customer-success',
  successCenter: '/success-center',
  integrationsMarketplace: '/integrations-marketplace',
  integrationReadiness: '/integration-readiness',
  solutionBuilder: '/solution-builder',
  configurationStudio: '/configuration-studio',
  welcome: '/welcome',
  onboarding: '/onboarding',
});

export const CANONICAL_APP_ROUTE_TREE = Object.freeze([
  { path: '/', type: 'redirect', to: '/emergency/whiteboard' },
  { path: '/auth-callback', type: 'page', componentKey: 'AuthCallback' },
  { path: '/shared/tools/:shareId', type: 'page', componentKey: 'SharedToolSession' },
  { path: '/whiteboard', type: 'redirect', to: '/emergency/whiteboard' },
  { path: '/reception', type: 'redirect', to: '/emergency/reception' },
  { path: '/triage', type: 'redirect', to: '/emergency/reception?queue=pretriage' },
  { path: '/charge', type: 'redirect', to: '/emergency/whiteboard' },
  { path: '/physician', type: 'redirect', to: '/emergency/whiteboard' },
  { path: '/ems', type: 'redirect', to: '/emergency/ems' },
  { path: '/analytics', type: 'redirect', to: '/emergency/analytics' },
  { path: '/copilot', type: 'redirect', to: '/emergency/copilot' },
  { path: '/calculators', type: 'redirect', to: '/emergency/tools' },
  { path: '/admin', type: 'redirect', to: '/admin' },
  { path: '/emergency', type: 'redirect', to: '/emergency/whiteboard' },
  { path: '/emergency/command-center', type: 'page', componentKey: 'EmergencyCommandCenter' },
  { path: '/emergency/whiteboard', type: 'page', componentKey: 'EmergencyWhiteboard' },
  { path: '/emergency/patients', type: 'page', componentKey: 'EmergencyPatientsRoute' },
  { path: '/emergency/journey', type: 'page', componentKey: 'FullJourneyOperatingPage' },
  { path: '/emergency/dispatch', type: 'page', componentKey: 'DispatchConsole' },
  { path: '/emergency/ems', type: 'page', componentKey: 'EMSPipeline' },
  { path: '/emergency/ed-readiness', type: 'page', componentKey: 'EdReadinessOperatingPage' },
  { path: '/emergency/reception', type: 'page', componentKey: 'ReceptionWorkspace' },
  { path: '/emergency/intake', type: 'page', componentKey: 'SmartIntake' },
  { path: '/emergency/queues', type: 'page', componentKey: 'EmergencyQueueRoute' },
  { path: '/emergency/reassessment', type: 'page', componentKey: 'EmergencyReassessmentRoute' },
  { path: '/emergency/capacity', type: 'page', componentKey: 'CapacityDetail' },
  { path: '/emergency/boarding', type: 'page', componentKey: 'EmergencyBoardingRoute' },
  { path: '/emergency/referrals', type: 'page', componentKey: 'ReferralPanel' },
  { path: '/emergency/copilot', type: 'page', componentKey: 'EmergencyCopilotRoute' },
  { path: '/emergency/documentation', type: 'page', componentKey: 'ClinicalDocumentationAssistant' },
  { path: '/emergency/tools', type: 'page', componentKey: 'ToolsOverview' },
  { path: '/emergency/pulse', type: 'page', componentKey: 'EmergencyDepartmentPulse' },
  { path: '/emergency/shift', type: 'page', componentKey: 'EmergencyShiftSummary' },
  { path: '/emergency/analytics', type: 'page', componentKey: 'EmergencyAnalytics' },
  { path: '/emergency/diagnostics', type: 'page', componentKey: 'DiagnosticsOperatingPage' },
  { path: '/emergency/handoffs', type: 'page', componentKey: 'HandoffsOperatingPage' },
  { path: '/emergency/reports', type: 'page', componentKey: 'EmergencyReportsOperatingPage' },
  { path: '/emergency/alerts', type: 'page', componentKey: 'ClinicalAlertsPage' },
  { path: '/emergency/settings', type: 'page', componentKey: 'EmergencySettingsRoute' },
  { path: '/emergency/help', type: 'page', componentKey: 'HelpHubPage' },
  { path: '*', type: 'redirect', to: '/emergency/whiteboard' },
]);

export const EMERGENCY_OS_TARGET_ROUTES = Object.freeze(
  CANONICAL_APP_ROUTE_TREE.filter((route) => route.type === 'page').map((route) => route.path),
);

export const AUTH_PATH_ALIASES = Object.freeze([
  '/login',
  '/log-in',
  '/signin',
  '/sign-in',
  '/signup',
  '/sign-up',
  '/register',
  '/join',
  '/create-account',
  '/account/login',
  '/account/signup',
  '/account/register',
  '/accounts/login',
  '/accounts/signup',
]);

export const AUTH_SIGNUP_PATH_ALIASES = Object.freeze([
  '/signup',
  '/sign-up',
  '/register',
  '/join',
  '/create-account',
  '/account/signup',
  '/account/register',
  '/accounts/signup',
]);

export const ASSISTANT_ROUTE_ALIASES = Object.freeze(['/assistant', '/chat', '/ai', '/copilot']);
export const TOOLS_ROUTE_ALIASES = Object.freeze([
  '/tools',
  '/all-tools',
  '/clinical-tools',
  '/catalog',
]);
export const CALCULATORS_ROUTE_ALIASES = Object.freeze(['/calculators']);
export const SIMULATION_ROUTE_ALIASES = Object.freeze(['/medical-simulation']);
export const LABORATORY_ROUTE_ALIASES = Object.freeze(['/lab']);
export const MEDICAL_3D_VIEWER_ROUTE_ALIASES = Object.freeze(['/anatomy-viewer']);
export const LIVE_MAP_ROUTE_ALIASES = Object.freeze(['/maps', '/tracking', '/live-tracking']);
export const FLEET_MAP_ROUTE_ALIASES = Object.freeze([
  '/fleet',
  '/fleet/live-map',
  '/fleet/tracking',
]);
export const OPERATIONS_ROUTE_ALIASES = Object.freeze(['/operations-center']);
export const AUDIT_ROUTE_ALIASES = Object.freeze(['/audit-logs']);
export const HOME_ROUTE_ALIASES = Object.freeze(['/home', '/workspace', '/app', '/whiteboard']);
export const ORGANIZATION_PACKS_ROUTE_ALIASES = Object.freeze([]);

export const LEGACY_EMERGENCY_ROUTE_REDIRECTS = Object.freeze(
  [
    ['/ems', CANONICAL_ROUTES.emergencyEms],
    ['/journey', CANONICAL_ROUTES.emergencyPatients],
    ['/intake', CANONICAL_ROUTES.emergencyIntake],
    ['/reception', CANONICAL_ROUTES.emergencyReception],
    ['/emergency/arrival', CANONICAL_ROUTES.emergencyReception],
    ['/workspace/emergency/reception', CANONICAL_ROUTES.emergencyReception],
    ['/queues', CANONICAL_ROUTES.emergencyQueues],
    ['/queue', CANONICAL_ROUTES.emergencyQueues],
    ['/reassessment', CANONICAL_ROUTES.emergencyReassessment],
    ['/capacity', CANONICAL_ROUTES.emergencyCapacity],
    ['/boarding', CANONICAL_ROUTES.emergencyBoarding],
    ['/referrals', CANONICAL_ROUTES.emergencyReferrals],
    ['/provincial-health', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/integrations', CANONICAL_ROUTES.integrationHub],
    ['/integrations/hub', CANONICAL_ROUTES.integrationHub],
    ['/platform/cosmos', CANONICAL_ROUTES.cosmosViewer],
    ['/cosmos', CANONICAL_ROUTES.cosmosViewer],
    ['/simulation', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/shift', CANONICAL_ROUTES.emergencyShift],
    ['/shift-summary', CANONICAL_ROUTES.emergencyShift],
    ['/pulse', CANONICAL_ROUTES.emergencyPulse],
    ['/tools', CANONICAL_ROUTES.emergencyTools],
    ['/calculators', CANONICAL_ROUTES.emergencyTools],
    ['/scores', CANONICAL_ROUTES.emergencyTools],
    ['/scores/*', CANONICAL_ROUTES.emergencyTools],
    ['/emergency/smart-intake', CANONICAL_ROUTES.emergencyIntake],
    ['/emergency/queue', CANONICAL_ROUTES.emergencyQueues],
    ['/emergency/patient-journey', CANONICAL_ROUTES.emergencyPatients],
    ['/emergency/provincial-health', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/emergency/integrations', CANONICAL_ROUTES.integrationHub],
    ['/emergency/simulation', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/emergency/department-pulse', CANONICAL_ROUTES.emergencyPulse],
    ['/department-pulse', CANONICAL_ROUTES.emergencyPulse],
    [CANONICAL_ROUTES.emergencyAiGovernance, CANONICAL_ROUTES.aiGovernance],
    [CANONICAL_ROUTES.emergencyDigitalTwin, CANONICAL_ROUTES.digitalTwin],
    ['/emergency/calculators', CANONICAL_ROUTES.emergencyTools],
    ['/emergency/clinical-tools', CANONICAL_ROUTES.emergencyTools],
    ['/emergency/shift-summary', CANONICAL_ROUTES.emergencyShift],
    ['/workspace/emergency/pulse', CANONICAL_ROUTES.emergencyPulse],
    ['/workspace/emergency/charge-nurse', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/workspace/emergency', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/workspace/emergency/whiteboard', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/workspace/emergency/intake', CANONICAL_ROUTES.emergencyIntake],
    ['/workspace/emergency/patients', CANONICAL_ROUTES.emergencyPatients],
    ['/workspace/emergency/journey', CANONICAL_ROUTES.emergencyJourney],
    ['/workspace/emergency/queue', CANONICAL_ROUTES.emergencyQueues],
    ['/workspace/emergency/queues', CANONICAL_ROUTES.emergencyQueues],
    ['/workspace/emergency/ems', CANONICAL_ROUTES.emergencyEms],
    ['/workspace/emergency/referrals', CANONICAL_ROUTES.emergencyReferrals],
    ['/workspace/emergency/provincial-health', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/workspace/emergency/integrations', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/workspace/emergency/capacity', CANONICAL_ROUTES.emergencyCapacity],
    ['/workspace/emergency/boarding', CANONICAL_ROUTES.emergencyBoarding],
    ['/workspace/emergency/simulation', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/workspace/emergency/federated-learning', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/workspace/emergency/digital-twin', CANONICAL_ROUTES.digitalTwin],
    ['/workspace/emergency/tools', CANONICAL_ROUTES.emergencyTools],
    ['/workspace/emergency/calculators', CANONICAL_ROUTES.emergencyTools],
    ['/workspace/emergency/shift-summary', CANONICAL_ROUTES.emergencyShift],
    ['/workspace/emergency/shift', CANONICAL_ROUTES.emergencyShift],
    ['/workspace/emergency/settings', CANONICAL_ROUTES.emergencySettings],
    ['/workspace/emergency/copilot', CANONICAL_ROUTES.emergencyCopilot],
    ['/workspace/emergency/ai-governance', CANONICAL_ROUTES.aiGovernance],
    ['/workspace/emergency/command-center', CANONICAL_ROUTES.emergencyCommandCenter],
    ['/workspace/emergency/department-pulse', CANONICAL_ROUTES.emergencyPulse],
    ['/patients', CANONICAL_ROUTES.emergencyPatients],
    ['/patients/*', CANONICAL_ROUTES.emergencyPatients],
    ['/settings', CANONICAL_ROUTES.emergencySettings],
    ['/settings/general', CANONICAL_ROUTES.emergencySettings],
    ['/settings/thresholds', CANONICAL_ROUTES.emergencySettings],
    ['/settings/staff', CANONICAL_ROUTES.emergencySettings],
    ['/settings/integrations', CANONICAL_ROUTES.emergencySettings],
    ['/settings/features', CANONICAL_ROUTES.featureFlags],
    ['/anatomy-viewer', CANONICAL_ROUTES.medical3dViewer],
    ['/hospital-map', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/hospital-map/*', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/medical-iot', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/medical-iot/*', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/devices', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/devices/*', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/live-map', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/live-map/*', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/operations', CANONICAL_ROUTES.emergencyWhiteboard],
    ['/operations/*', CANONICAL_ROUTES.emergencyWhiteboard],
  ].map(([path, to]) =>
    Object.freeze({
      path,
      to,
      routeId: 'legacy-emergency',
      auth: 'required',
    }),
  ),
);

export const NON_ED_WORKSPACE_REDIRECT_ROUTES = Object.freeze([
  Object.freeze({ path: '/analytics', moduleName: 'Analytics' }),
  Object.freeze({ path: '/federated-learning', moduleName: 'Federated Learning' }),
  Object.freeze({ path: '/governance', moduleName: 'Governance' }),
  Object.freeze({ path: '/governance/*', moduleName: 'Governance' }),
  Object.freeze({ path: '/lab', moduleName: 'Laboratory' }),
  Object.freeze({ path: '/fleet', moduleName: 'Fleet' }),
  Object.freeze({ path: '/fleet/*', moduleName: 'Fleet' }),
  Object.freeze({ path: '/vehicle', moduleName: 'Vehicle Operations' }),
  Object.freeze({ path: '/vehicle/*', moduleName: 'Vehicle Operations' }),
  Object.freeze({ path: '/research/*', moduleName: 'Research' }),
  Object.freeze({ path: '/education', moduleName: 'Education' }),
  Object.freeze({ path: '/education/*', moduleName: 'Education' }),
  Object.freeze({ path: '/pharmacy', moduleName: 'Pharmacy' }),
  Object.freeze({ path: '/pharmacy/*', moduleName: 'Pharmacy' }),
  Object.freeze({ path: '/radiology', moduleName: 'Radiology' }),
  Object.freeze({ path: '/radiology/*', moduleName: 'Radiology' }),
]);

export const WORKSPACE_EMERGENCY_SUBPAGE_REDIRECTS = Object.freeze({
  whiteboard: CANONICAL_ROUTES.emergencyWhiteboard,
  patients: CANONICAL_ROUTES.emergencyPatients,
  journey: CANONICAL_ROUTES.emergencyJourney,
  'patient-journey': CANONICAL_ROUTES.emergencyPatients,
  queues: CANONICAL_ROUTES.emergencyQueues,
  queue: CANONICAL_ROUTES.emergencyQueues,
  reassessment: CANONICAL_ROUTES.emergencyReassessment,
  ems: CANONICAL_ROUTES.emergencyEms,
  referrals: CANONICAL_ROUTES.emergencyReferrals,
  'provincial-health': CANONICAL_ROUTES.emergencyWhiteboard,
  integrations: CANONICAL_ROUTES.emergencyWhiteboard,
  capacity: CANONICAL_ROUTES.emergencyCapacity,
  boarding: CANONICAL_ROUTES.emergencyBoarding,
  analytics: CANONICAL_ROUTES.emergencyAnalytics,
  simulation: CANONICAL_ROUTES.emergencyWhiteboard,
  'real-time-simulation': CANONICAL_ROUTES.emergencyWhiteboard,
  'federated-learning': CANONICAL_ROUTES.emergencyWhiteboard,
  'digital-twin': CANONICAL_ROUTES.emergencyWhiteboard,
  pulse: CANONICAL_ROUTES.emergencyPulse,
  'department-pulse': CANONICAL_ROUTES.emergencyPulse,
  'shift-summary': CANONICAL_ROUTES.emergencyShift,
  shift: CANONICAL_ROUTES.emergencyShift,
  tools: CANONICAL_ROUTES.emergencyTools,
  calculators: CANONICAL_ROUTES.emergencyTools,
  'clinical-tools': CANONICAL_ROUTES.emergencyTools,
  intake: CANONICAL_ROUTES.emergencyIntake,
  'smart-intake': CANONICAL_ROUTES.emergencyIntake,
  reception: CANONICAL_ROUTES.emergencyReception,
  arrival: CANONICAL_ROUTES.emergencyReception,
  'command-center': CANONICAL_ROUTES.emergencyCommandCenter,
  copilot: CANONICAL_ROUTES.emergencyCopilot,
  'ai-governance': CANONICAL_ROUTES.emergencyWhiteboard,
});

export const ROUTE_RECORDS = Object.freeze([
  Object.freeze({
    id: 'auth',
    path: CANONICAL_ROUTES.platformStart,
    layout: 'auth',
    auth: 'publicOnly',
    status: 'redirect',
    aliases: AUTH_PATH_ALIASES,
    navGroup: 'auth',
  }),
  Object.freeze({
    id: 'dashboard',
    path: CANONICAL_ROUTES.emergencyWhiteboard,
    componentKey: 'EmergencyWhiteboard',
    layout: 'app',
    auth: 'required',
    status: 'redirect',
    aliases: HOME_ROUTE_ALIASES,
    navGroup: 'primary',
  }),
  Object.freeze({
    id: 'executive',
    path: CANONICAL_ROUTES.executive,
    componentKey: 'ExecutiveCommandCenter',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'C-suite hospital leadership dashboard for platform value, adoption, operational readiness, compliance, security, and alerts.',
  }),
  Object.freeze({
    id: 'assistant',
    path: CANONICAL_ROUTES.emergencyCopilot,
    componentKey: 'EmergencyCopilotPanel',
    layout: 'app',
    auth: 'required',
    status: 'redirect',
    aliases: ASSISTANT_ROUTE_ALIASES,
    navGroup: 'primary',
  }),
  Object.freeze({
    id: 'aiCommandCenter',
    path: CANONICAL_ROUTES.aiCommandCenter,
    componentKey: 'AiCommandCenterDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: ['/ai/command-center', '/ai-command'],
    navGroup: 'advanced',
    notes:
      'Unified AI command surface for Ask, Act, Monitor, Govern, and Learn workflows across CareDroid.',
  }),
  Object.freeze({
    id: 'recommendations',
    path: CANONICAL_ROUTES.emergencyTools,
    componentKey: 'ToolsOverview',
    layout: 'app',
    auth: 'required',
    status: 'redirect',
    aliases: [],
    navGroup: 'solutions',
    notes:
      'Retired standalone recommendations route redirects into CareDroid tools with recommendation filters.',
  }),
  Object.freeze({
    id: 'knowledgeHub',
    path: CANONICAL_ROUTES.knowledgeHub,
    componentKey: 'HealthcareKnowledgeHubPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes:
      'Centralized healthcare knowledge hub for protocols, pathways, calculators, simulations, AI guidance, and documentation.',
  }),
  Object.freeze({
    id: 'knowledgeBase',
    path: CANONICAL_ROUTES.knowledgeBase,
    componentKey: 'KnowledgeBasePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
  }),
  Object.freeze({
    id: 'marketplace',
    path: CANONICAL_ROUTES.marketplace,
    componentKey: 'MarketplacePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes:
      'Unified extensibility marketplace for asset packs, workflows, simulations, protocols, AI agents, and integrations.',
  }),
  Object.freeze({
    id: 'enterpriseReadiness',
    path: CANONICAL_ROUTES.enterpriseReadiness,
    componentKey: 'EnterpriseReadinessPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes:
      'Enterprise readiness center with weighted SSO, RBAC, tenant isolation, audit, governance, integration, and security scoring.',
  }),
  Object.freeze({
    id: 'trackMindMaturity',
    path: CANONICAL_ROUTES.trackMindMaturity,
    componentKey: 'TrackMindMaturityDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes:
      'TrackMind Operating System Maturity Framework — nine-domain scoring for operations, safety, compliance, security, equine welfare, facilities, finance, AI governance, and data quality.',
  }),
  Object.freeze({
    id: 'enterprisePlatform',
    path: CANONICAL_ROUTES.enterprisePlatform,
    componentKey: 'EnterpriseOperatingPlatformHub',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes:
      'TrackMind Enterprise Operating Platform — Prompts 99–116: benchmarking, franchise readiness, certification, risk, continuity, DR, assets, workforce, training, knowledge, playbooks, decision support, scenarios, strategy, portfolio, governance, ESG, architecture.',
  }),
  Object.freeze({
    id: 'platformIntelligence',
    path: CANONICAL_ROUTES.platformIntelligence,
    componentKey: 'PlatformIntelligenceHub',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes:
      'TrackMind Platform Intelligence — Prompts 117–136: artifact registry, lineage, metadata, KPI intelligence, observability, technical debt, convergence review.',
  }),
  // Future module
  Object.freeze({
    id: 'platformAdmin',
    path: CANONICAL_ROUTES.platformAdmin,
    componentKey: 'PlatformAdminPage',
    layout: 'app',
    auth: 'required',
    status: 'future',
    aliases: [],
    navGroup: 'account',
    notes:
      'SaaS operating system layer unifying organization, subscription, products, packs, assets, workspaces, users, AI agents, and automations.',
  }),
  Object.freeze({
    id: 'tools',
    path: CANONICAL_ROUTES.emergencyTools,
    componentKey: 'ToolsOverview',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: TOOLS_ROUTE_ALIASES,
    matchPrefixes: ['/tools/'],
    navGroup: 'tools',
  }),
  Object.freeze({
    id: 'calculators',
    path: CANONICAL_ROUTES.emergencyTools,
    componentKey: 'ToolsOverview',
    layout: 'app',
    auth: 'required',
    status: 'redirect',
    aliases: CALCULATORS_ROUTE_ALIASES,
    matchPrefixes: ['/tools/calculators/'],
    navGroup: 'tools',
  }),
  Object.freeze({
    id: 'operations',
    path: CANONICAL_ROUTES.emergencyQueues,
    componentKey: 'EmergencyQueueRoute',
    layout: 'app',
    auth: 'required',
    status: 'redirect',
    aliases: OPERATIONS_ROUTE_ALIASES,
    matchPrefixes: ['/operations/'],
    navGroup: 'primary',
  }),
  // Future module
  Object.freeze({
    id: 'digitalTwin',
    path: CANONICAL_ROUTES.emergencyTools,
    componentKey: 'ToolsOverview',
    layout: 'app',
    auth: 'required',
    status: 'redirect',
    aliases: [],
    matchPrefixes: ['/digital-twin/'],
    navGroup: 'operations',
  }),
  Object.freeze({
    id: 'digitalTwinIntelligence',
    path: CANONICAL_ROUTES.digitalTwinIntelligence,
    componentKey: 'DigitalTwinIntelligence',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/digital-twin-intelligence/'],
    navGroup: 'operations',
    notes:
      'Predictive operational twin combining Hospital Map, Fleet, Medical IoT, occupancy, telemetry, alerts, and maintenance readiness.',
  }),
  Object.freeze({
    id: 'hospitalMap',
    path: CANONICAL_ROUTES.hospitalMap,
    componentKey: 'HospitalMapDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/hospital-map/'],
    navGroup: 'operations',
    notes: 'Indoor hospital floor plan with device and bed markers.',
  }),
  Object.freeze({
    id: 'medicalIot',
    path: CANONICAL_ROUTES.medicalIot,
    componentKey: 'MedicalIotDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes: 'Medical IoT device registry, vitals, and connectivity.',
  }),
  Object.freeze({
    id: 'devices',
    path: CANONICAL_ROUTES.devices,
    componentKey: 'DeviceFleetManagement',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes: 'Biomedical device fleet inventory and maintenance.',
  }),
  Object.freeze({
    id: 'surveillanceNexus',
    path: CANONICAL_ROUTES.surveillanceNexus,
    componentKey: 'SurveillanceNexusDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: ['/surveillance', '/cctv', '/iot-nexus'],
    matchPrefixes: ['/surveillance/'],
    navGroup: 'operations',
    notes:
      'TrackMind-aligned surveillance and IoT nexus — cameras, zones, health, alerts, and incident linkage.',
  }),
  Object.freeze({
    id: 'simulation',
    path: CANONICAL_ROUTES.emergencyTools,
    componentKey: 'ToolsOverview',
    layout: 'app',
    auth: 'required',
    status: 'redirect',
    aliases: SIMULATION_ROUTE_ALIASES,
    matchPrefixes: ['/simulation/'],
    navGroup: 'tools',
  }),
  // Future module
  Object.freeze({
    id: 'laboratory',
    path: CANONICAL_ROUTES.laboratory,
    componentKey: 'LaboratoryDashboard',
    layout: 'app',
    auth: 'required',
    status: 'future',
    aliases: LABORATORY_ROUTE_ALIASES,
    navGroup: 'tools',
  }),
  Object.freeze({
    id: 'medical3dViewer',
    path: CANONICAL_ROUTES.medical3dViewer,
    componentKey: 'Medical3DViewer',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: MEDICAL_3D_VIEWER_ROUTE_ALIASES,
    navGroup: 'tools',
  }),
  Object.freeze({
    id: 'liveMap',
    path: CANONICAL_ROUTES.emergencyTools,
    componentKey: 'ToolsOverview',
    layout: 'app',
    auth: 'required',
    status: 'redirect',
    aliases: LIVE_MAP_ROUTE_ALIASES,
    navGroup: 'operations',
  }),
  // Future module
  Object.freeze({
    id: 'fleetMap',
    path: CANONICAL_ROUTES.fleetMap,
    componentKey: 'FleetLiveMap',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: FLEET_MAP_ROUTE_ALIASES,
    matchPrefixes: ['/fleet/'],
    navGroup: 'operations',
  }),
  // Future module
  Object.freeze({
    id: 'fleetCommand',
    path: CANONICAL_ROUTES.fleetCommand,
    componentKey: 'FleetDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes:
      'Fleet command dashboard retained as an operations detail route while /fleet/map is the canonical map entry.',
  }),
  Object.freeze({
    id: 'audit',
    path: CANONICAL_ROUTES.audit,
    componentKey: 'PlatformGovernanceWorkspace',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: AUDIT_ROUTE_ALIASES,
    matchPrefixes: ['/audit/'],
    navGroup: 'advanced',
  }),
  Object.freeze({
    id: 'assetPacks',
    path: CANONICAL_ROUTES.assetPacks,
    componentKey: 'PackMarketplace',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Canonical organization-aware asset pack marketplace.',
  }),
  Object.freeze({
    id: 'businessBrain',
    path: CANONICAL_ROUTES.businessBrain,
    componentKey: 'CareDroidBusinessBrainPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Business intelligence layer aggregating platform and business analytics into advisory recommendations.',
  }),
  Object.freeze({
    id: 'organization',
    path: CANONICAL_ROUTES.organization,
    componentKey: 'OrganizationDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/organization/'],
    navGroup: 'organization',
    notes: 'Tenant organization dashboard and settings entry point.',
  }),
  Object.freeze({
    id: 'platformAnalytics',
    path: CANONICAL_ROUTES.platformAnalytics,
    componentKey: 'PlatformAnalyticsPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes: 'Tenant analytics for usage, adoption, automation, and value signals.',
  }),
  Object.freeze({
    id: 'departmentIntelligence',
    path: CANONICAL_ROUTES.departmentIntelligence,
    componentKey: 'DepartmentIntelligencePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes:
      'Department performance intelligence with health scores and measurable platform outcomes.',
  }),
  Object.freeze({
    id: 'workflowMining',
    path: CANONICAL_ROUTES.workflowMining,
    componentKey: 'WorkflowMiningEnginePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes:
      'Workflow mining engine for common journeys, friction, dead ends, and unnecessary clicks.',
  }),
  Object.freeze({
    id: 'workspaceDependencyGraph',
    path: CANONICAL_ROUTES.workspaceDependencyGraph,
    componentKey: 'WorkspaceDependencyGraphPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes:
      'Cross-workspace intelligence dependency graph for handoffs, signals, and operational relationships.',
  }),
  Object.freeze({
    id: 'organizationIntelligence',
    path: CANONICAL_ROUTES.organizationIntelligence,
    componentKey: 'OrganizationIntelligenceProfile',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Organization intelligence profile with behavior-aware pack, asset, AI, workflow, simulation, and automation recommendations.',
  }),
  Object.freeze({
    id: 'platformLearningEngine',
    path: CANONICAL_ROUTES.platformLearningEngine,
    componentKey: 'PlatformLearningEngine',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: ['/platform-learning'],
    navGroup: 'advanced',
    notes:
      'Privacy-safe platform learning engine that turns usage signals into optimization suggestions.',
  }),
  Object.freeze({
    id: 'brain',
    path: CANONICAL_ROUTES.brain,
    componentKey: 'CareDroidBrainDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Centralized CareDroid Brain intelligence layer across platform, organization, role, asset, automation, memory, recommendations, and learning systems.',
  }),
  Object.freeze({
    id: 'products',
    path: CANONICAL_ROUTES.products,
    componentKey: 'ProductsIndexPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/products/'],
    navGroup: 'products',
    notes: 'Sellable CareDroid product catalog mapped to packs and assets.',
  }),
  Object.freeze({
    id: 'plans',
    path: CANONICAL_ROUTES.plans,
    componentKey: 'CommercialPlansPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Subscription plan catalog mapped to included products and packs.',
  }),
  Object.freeze({
    id: 'specialties',
    path: CANONICAL_ROUTES.specialties,
    componentKey: 'SpecialtiesIndexPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/specialties/'],
    navGroup: 'products',
  }),
  Object.freeze({
    id: 'carePathways',
    path: CANONICAL_ROUTES.carePathways,
    componentKey: 'CarePathwaysIndexPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    matchPrefixes: ['/care-pathways/'],
    navGroup: 'products',
  }),
  Object.freeze({
    id: 'agents',
    path: CANONICAL_ROUTES.agents,
    componentKey: 'AgentsRegistryPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'AI agent registry mounted to products, packs, workspaces, and role profiles.',
  }),
  Object.freeze({
    id: 'maturityAssessment',
    path: CANONICAL_ROUTES.maturityAssessment,
    componentKey: 'MaturityAssessmentPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
  }),
  Object.freeze({
    id: 'outcomes',
    path: CANONICAL_ROUTES.outcomes,
    componentKey: 'OutcomesDashboardPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
  }),
  Object.freeze({
    id: 'integrationsMarketplace',
    path: CANONICAL_ROUTES.integrationsMarketplace,
    componentKey: 'IntegrationsMarketplacePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes:
      'Integration marketplace route documented as product/system purpose until integration assets are launchable.',
  }),
  Object.freeze({
    id: 'departments',
    path: CANONICAL_ROUTES.departments,
    componentKey: 'DepartmentsPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Department-to-asset mapping across packs, assets, roles, permissions, and users.',
  }),
  Object.freeze({
    id: 'serviceLines',
    path: CANONICAL_ROUTES.serviceLines,
    componentKey: 'ServiceLinesPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Service-line architecture across departments, asset packs, and assets.',
  }),
  Object.freeze({
    id: 'integrationReadiness',
    path: CANONICAL_ROUTES.integrationReadiness,
    componentKey: 'IntegrationReadinessPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes:
      'Integration readiness across interoperability, identity, government, and scheduling systems.',
  }),
  Object.freeze({
    id: 'configurationStudio',
    path: CANONICAL_ROUTES.configurationStudio,
    componentKey: 'ConfigurationStudioPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'No-code configuration studio for tenant-safe product and pack setup.',
  }),
  Object.freeze({
    id: 'solutionBuilder',
    path: CANONICAL_ROUTES.solutionBuilder,
    componentKey: 'HospitalSolutionBuilderPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'No-code hospital deployment recommendation and apply workflow.',
  }),
  Object.freeze({
    id: 'valueTracking',
    path: CANONICAL_ROUTES.valueTracking,
    componentKey: 'ValueTrackingPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Clinical, operational, and executive value tracking framework.',
  }),
  Object.freeze({
    id: 'productIntelligence',
    path: CANONICAL_ROUTES.productIntelligence,
    componentKey: 'ProductIntelligenceLayerPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes:
      'Product intelligence layer for adoption, ROI, health, and engagement value-chain metrics.',
  }),
  Object.freeze({
    id: 'expansionOpportunities',
    path: CANONICAL_ROUTES.expansionOpportunities,
    componentKey: 'CustomerExpansionOpportunitiesPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes: 'Customer expansion engine for upsell, cross-sell, and next-best pack opportunities.',
  }),
  Object.freeze({
    id: 'customerSuccess',
    path: CANONICAL_ROUTES.customerSuccess,
    componentKey: 'CustomerSuccessPlatformPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes:
      'Customer success platform — onboarding progress, adoption metrics, feature utilization, health scores, support tracking, renewal readiness, and KPIs.',
  }),
  Object.freeze({
    id: 'customerPortal',
    path: CANONICAL_ROUTES.customerPortal,
    componentKey: 'CustomerPortalPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes:
      'Tenant-scoped customer portal for subscription, entitlements, organization profile, users, integrations, invoices, support, and release notes.',
  }),
  Object.freeze({
    id: 'successCenter',
    path: CANONICAL_ROUTES.successCenter,
    componentKey: 'SuccessCenterPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'products',
    notes:
      'Tenant-scoped success center for adoption, workspace adoption, asset usage, AI usage, simulation, workflow, onboarding, and health score.',
  }),
  Object.freeze({
    id: 'billing',
    path: CANONICAL_ROUTES.billing,
    componentKey: 'BillingPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'account',
    notes: 'Organization subscription billing and plan limit overview.',
  }),
  Object.freeze({
    id: 'usage',
    path: CANONICAL_ROUTES.usage,
    componentKey: 'UsagePage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'operations',
    notes: 'Organization usage metering by workspace, asset, role, and period.',
  }),
  Object.freeze({
    id: 'saasHealth',
    path: CANONICAL_ROUTES.saasHealth,
    componentKey: 'SaasHealthCenter',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'SaaS health center for frontend, backend, API, integrations, tenant, AI, and simulation health.',
  }),
  // Future module
  Object.freeze({
    id: 'governanceRegistry',
    path: CANONICAL_ROUTES.governanceRegistry,
    componentKey: 'GovernanceRegistry',
    layout: 'app',
    auth: 'required',
    status: 'future',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Platform governance registry for owner, steward, approver, risk, evidence, version, audit, and review schedules.',
  }),
  // Future module
  Object.freeze({
    id: 'aiGovernance',
    path: CANONICAL_ROUTES.aiGovernance,
    componentKey: 'AIGovernanceDashboard',
    layout: 'app',
    auth: 'required',
    status: 'future',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Enterprise AI governance dashboard for AI service inventory, safety rules, compliance reporting, prompt validation, and human-review posture.',
  }),
  Object.freeze({
    id: 'dependencyGraph',
    path: CANONICAL_ROUTES.dependencyGraph,
    componentKey: 'DependencyGraph',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Asset dependency graph across products, packs, assets, routes, backend services, and integrations.',
  }),
  Object.freeze({
    id: 'artifacts',
    path: CANONICAL_ROUTES.artifacts,
    componentKey: 'Artifacts',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Machine-learning-ready artifact intelligence catalog with CSV/JSON export, feature rows, and resonance metadata.',
  }),
  Object.freeze({
    id: 'knowledgeGraph',
    path: CANONICAL_ROUTES.knowledgeGraph,
    componentKey: 'ClinicalKnowledgeGraph',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Artifact knowledge graph across assets, packs, products, workspaces, roles, routes, simulations, workflows, AI agents, and integrations.',
  }),
  Object.freeze({
    id: 'aiModels',
    path: CANONICAL_ROUTES.aiModels,
    componentKey: 'AiModelsPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Unified AI model registry for gateway, MoE, RAG, tool calling, resonance, tutoring, cost, guardrails, and evaluation systems.',
  }),
  Object.freeze({
    id: 'aiEvaluation',
    path: CANONICAL_ROUTES.aiEvaluation,
    componentKey: 'AiEvaluationDashboard',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: ['/ai/evaluation'],
    navGroup: 'advanced',
    notes:
      'AI Evaluation Lab for model quality, hallucination, tool-call, workflow, latency, cost, and comparison benchmarks.',
  }),
  // Future module
  Object.freeze({
    id: 'tenantAdmin',
    path: CANONICAL_ROUTES.tenantAdmin,
    componentKey: 'TenantAdministrationCenter',
    layout: 'app',
    auth: 'required',
    status: 'future',
    aliases: [],
    navGroup: 'account',
    notes: 'Tenant-scoped organization administration center for no-code customer configuration.',
  }),
  Object.freeze({
    id: 'organizationPacks',
    path: CANONICAL_ROUTES.organizationPacks,
    componentKey: 'PackMarketplace',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: ORGANIZATION_PACKS_ROUTE_ALIASES,
    navGroup: 'organization',
    notes: 'Organization-specific pack marketplace and entitlement management.',
  }),
  Object.freeze({
    id: 'workflows',
    path: CANONICAL_ROUTES.workflows,
    componentKey: 'WorkflowBuilderPage',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [CANONICAL_ROUTES.automation],
    navGroup: 'secondary',
    notes:
      'Canonical workflow route. Legacy /automation redirects here to avoid duplicate workflow UI ownership.',
  }),
  Object.freeze({
    id: 'automationAnalytics',
    path: CANONICAL_ROUTES.automationAnalytics,
    componentKey: 'AutomationAnalytics',
    layout: 'app',
    auth: 'required',
    status: 'active',
    aliases: [],
    navGroup: 'advanced',
    notes:
      'Automation analytics across solution packages, workspace automations, audit events, human overrides, and AI recommendation adoption.',
  }),
]);

export const ROUTE_RECORDS_BY_ID = Object.freeze(
  Object.fromEntries(ROUTE_RECORDS.map((record) => [record.id, record])),
);

export const ROUTE_ALIAS_REDIRECTS = Object.freeze(
  ROUTE_RECORDS.filter((record) => record.status !== 'future').flatMap((record) =>
    (record.aliases || []).map((path) =>
      Object.freeze({
        path,
        to: record.path,
        routeId: record.id,
        auth: record.auth,
      }),
    ),
  ),
);

export const PROTECTED_ROUTE_ALIAS_REDIRECTS = Object.freeze(
  ROUTE_ALIAS_REDIRECTS.filter((entry) => entry.auth === 'required'),
);

function aliasesForRoute(id) {
  const record = ROUTE_RECORDS_BY_ID[id];
  if (!record || record.status === 'future') return Object.freeze([]);
  return record.aliases || Object.freeze([]);
}

export const ROUTE_ALIAS_GROUPS = Object.freeze({
  auth: Object.freeze({ target: CANONICAL_ROUTES.platformStart, aliases: aliasesForRoute('auth') }),
  dashboard: Object.freeze({
    target: CANONICAL_ROUTES.emergencyWhiteboard,
    aliases: aliasesForRoute('dashboard'),
  }),
  assistant: Object.freeze({
    target: CANONICAL_ROUTES.emergencyCopilot,
    aliases: aliasesForRoute('assistant'),
  }),
  knowledgeBase: Object.freeze({
    target: CANONICAL_ROUTES.knowledgeBase,
    aliases: aliasesForRoute('knowledgeBase'),
  }),
  marketplace: Object.freeze({
    target: CANONICAL_ROUTES.marketplace,
    aliases: aliasesForRoute('marketplace'),
  }),
  enterpriseReadiness: Object.freeze({
    target: CANONICAL_ROUTES.enterpriseReadiness,
    aliases: aliasesForRoute('enterpriseReadiness'),
  }),
  trackMindMaturity: Object.freeze({
    target: CANONICAL_ROUTES.trackMindMaturity,
    aliases: aliasesForRoute('trackMindMaturity'),
  }),
  enterprisePlatform: Object.freeze({
    target: CANONICAL_ROUTES.enterprisePlatform,
    aliases: aliasesForRoute('enterprisePlatform'),
  }),
  platformIntelligence: Object.freeze({
    target: CANONICAL_ROUTES.platformIntelligence,
    aliases: aliasesForRoute('platformIntelligence'),
  }),
  platformAdmin: Object.freeze({
    target: CANONICAL_ROUTES.platformAdmin,
    aliases: aliasesForRoute('platformAdmin'),
  }),
  tools: Object.freeze({
    target: CANONICAL_ROUTES.emergencyTools,
    aliases: aliasesForRoute('tools'),
  }),
  calculators: Object.freeze({
    target: CANONICAL_ROUTES.emergencyTools,
    aliases: aliasesForRoute('calculators'),
  }),
  simulation: Object.freeze({
    target: CANONICAL_ROUTES.simulation,
    aliases: aliasesForRoute('simulation'),
  }),
  laboratory: Object.freeze({
    target: CANONICAL_ROUTES.laboratory,
    aliases: aliasesForRoute('laboratory'),
  }),
  medical3dViewer: Object.freeze({
    target: CANONICAL_ROUTES.medical3dViewer,
    aliases: aliasesForRoute('medical3dViewer'),
  }),
  liveMap: Object.freeze({ target: CANONICAL_ROUTES.liveMap, aliases: aliasesForRoute('liveMap') }),
  fleetMap: Object.freeze({
    target: CANONICAL_ROUTES.fleetMap,
    aliases: aliasesForRoute('fleetMap'),
  }),
  operations: Object.freeze({
    target: CANONICAL_ROUTES.emergencyQueues,
    aliases: aliasesForRoute('operations'),
  }),
  audit: Object.freeze({ target: CANONICAL_ROUTES.audit, aliases: aliasesForRoute('audit') }),
  assetPacks: Object.freeze({
    target: CANONICAL_ROUTES.assetPacks,
    aliases: aliasesForRoute('assetPacks'),
  }),
  organizationPacks: Object.freeze({
    target: CANONICAL_ROUTES.organizationPacks,
    aliases: aliasesForRoute('organizationPacks'),
  }),
});

export function getRouteAliasTarget(pathname) {
  return ROUTE_ALIAS_REDIRECTS.find((entry) => entry.path === pathname)?.to || null;
}
