export type ScenarioCategory =
  | 'cardiac'
  | 'respiratory'
  | 'neurological'
  | 'sepsis'
  | 'abdominal'
  | 'trauma'
  | 'mental_health'
  | 'pediatric'
  | 'geriatric'
  | 'toxicology'
  | 'operational';

export type ScenarioFrequency = 'critical' | 'very-common' | 'common' | 'moderate' | 'rare';

export type ScenarioCodeStatus = 'complete' | 'partial' | 'stub' | 'missing';

export interface EDScenario {
  id: string;
  name: string;
  category: ScenarioCategory;

  ctasLevels: number[];
  chiefComplaints: string[];
  icdCodes?: string[];

  frequency: ScenarioFrequency;
  timeCritical: boolean;
  canadianGuideline?: string;

  clinicalScores: string[];
  protocols: string[];
  checklistId?: string;

  codeStatus: ScenarioCodeStatus;
  toggleable: boolean;
  defaultEnabled: boolean;

  triggerOnComplaints: boolean;
  copilotAware: boolean;
}

type ScenarioInput = Omit<EDScenario, 'toggleable' | 'defaultEnabled' | 'copilotAware'> &
  Partial<Pick<EDScenario, 'toggleable' | 'defaultEnabled' | 'copilotAware'>>;

const scenario = (definition: ScenarioInput): EDScenario => {
  const defaultEnabled =
    definition.defaultEnabled ?? (definition.codeStatus === 'complete' || definition.codeStatus === 'partial');

  return {
    toggleable: true,
    copilotAware: true,
    ...definition,
    defaultEnabled,
  };
};

export const SCENARIO_REGISTRY: EDScenario[] = [
  scenario({
    id: 'stemi-cath-lab-activation',
    name: 'STEMI / Cath Lab Activation',
    category: 'cardiac',
    ctasLevels: [1, 2],
    chiefComplaints: ['stemi', 'chest pain', 'st elevation', 'ecg changes', 'diaphoretic', 'crushing chest pain'],
    icdCodes: ['I21'],
    frequency: 'critical',
    timeCritical: true,
    canadianGuideline: 'CTAS 2025; local STEMI/cath lab activation pathways',
    clinicalScores: ['heart-score', 'timi-ua-nstemi', 'grace-acs'],
    protocols: ['stemi-pathway-assistant', 'acs-workflow-assistant'],
    checklistId: 'stemi',
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'acs-chest-pain-risk',
    name: 'ACS Chest Pain Risk Stratification',
    category: 'cardiac',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['chest pain', 'chest pressure', 'chest tightness', 'troponin', 'acs', 'nstemi'],
    icdCodes: ['I20', 'I21', 'I24'],
    frequency: 'very-common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 chest pain acuity guidance',
    clinicalScores: ['heart-score', 'timi-ua-nstemi', 'grace-acs'],
    protocols: ['acs-workflow-assistant'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'arrhythmia-qt-cardioversion',
    name: 'Arrhythmia / QT / Cardioversion',
    category: 'cardiac',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['palpitations', 'arrhythmia', 'atrial fibrillation', 'syncope', 'qt prolongation', 'cardioversion'],
    icdCodes: ['I47', 'I48', 'I49'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 dysrhythmia and syncope guidance',
    clinicalScores: ['corrected-qt', 'chads2', 'has-bled'],
    protocols: ['atrial-fibrillation-assistant'],
    codeStatus: 'stub',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'heart-failure-bnp',
    name: 'Heart Failure / BNP',
    category: 'cardiac',
    ctasLevels: [2, 3],
    chiefComplaints: ['shortness of breath', 'dyspnea', 'leg swelling', 'heart failure', 'pulmonary edema', 'bnp'],
    icdCodes: ['I50'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 dyspnea/cardiac failure guidance',
    clinicalScores: ['heart-failure-staging', 'bnp-context'],
    protocols: ['heart-failure-assistant'],
    codeStatus: 'stub',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'dyspnea-respiratory-deterioration-news2',
    name: 'Dyspnea / Respiratory Deterioration / NEWS2',
    category: 'respiratory',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['dyspnea', 'shortness of breath', 'sob', "can't breathe", 'respiratory distress', 'hypoxia'],
    icdCodes: ['R06'],
    frequency: 'very-common',
    timeCritical: true,
    canadianGuideline: 'CTAS 2025 respiratory distress guidance',
    clinicalScores: ['news2', 'gcs-calculator', 'rox-index'],
    protocols: ['oxygen-escalation-helper', 'ventilator-support-assistant'],
    checklistId: 'respiratory-failure',
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'pulmonary-embolism-wells-perc',
    name: 'Pulmonary Embolism / Wells PE / PERC',
    category: 'respiratory',
    ctasLevels: [2, 3],
    chiefComplaints: ['pleuritic chest pain', 'dyspnea', 'shortness of breath', 'hemoptysis', 'pulmonary embolism', 'pe'],
    icdCodes: ['I26'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 chest pain and dyspnea guidance',
    clinicalScores: ['wells-pe', 'perc', 'news2'],
    protocols: ['pulmonary-embolism-review'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'pneumonia-curb65',
    name: 'Pneumonia / CURB-65',
    category: 'respiratory',
    ctasLevels: [2, 3, 4],
    chiefComplaints: ['pneumonia', 'cough', 'fever', 'shortness of breath', 'productive cough'],
    icdCodes: ['J18'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 respiratory infection guidance',
    clinicalScores: ['curb65-calculator', 'pneumonia-severity-index', 'news2'],
    protocols: ['pneumonia-workflow'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'asthma-copd-peak-flow',
    name: 'Asthma / COPD / Peak Flow',
    category: 'respiratory',
    ctasLevels: [1, 2, 3, 4],
    chiefComplaints: ['asthma', 'wheezing', 'copd', 'shortness of breath', 'peak flow', 'respiratory failure'],
    icdCodes: ['J44', 'J45'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 asthma/COPD respiratory distress guidance',
    clinicalScores: ['asthma-severity-score', 'copd-gold-assessment', 'bode-index', 'rox-index'],
    protocols: ['asthma-exacerbation-assistant', 'copd-workflow-assistant'],
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'stroke-nihss',
    name: 'Stroke / NIHSS',
    category: 'neurological',
    ctasLevels: [1, 2],
    chiefComplaints: ['stroke', 'facial droop', 'arm weakness', 'speech difficulty', 'aphasia', 'hemiparesis'],
    icdCodes: ['I63', 'I64'],
    frequency: 'critical',
    timeCritical: true,
    canadianGuideline: 'Canadian Stroke Best Practices 2024; CTAS 2025 stroke guidance',
    clinicalScores: ['nihss', 'gcs-calculator', 'modified-rankin-scale'],
    protocols: ['stroke-workflow-assistant'],
    checklistId: 'stroke',
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'tia-abcd2',
    name: 'TIA / ABCD2',
    category: 'neurological',
    ctasLevels: [2, 3],
    chiefComplaints: ['tia', 'transient weakness', 'transient speech difficulty', 'resolved stroke symptoms'],
    icdCodes: ['G45'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'Canadian Stroke Best Practices 2024; CTAS 2025 neurologic deficit guidance',
    clinicalScores: ['abcd2'],
    protocols: ['stroke-workflow-assistant'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'gcs-altered-mental-status',
    name: 'GCS / Altered Mental Status',
    category: 'neurological',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['altered mental status', 'ams', 'confusion', 'unresponsive', 'decreased loc', 'gcs'],
    icdCodes: ['R41'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 level-of-consciousness guidance',
    clinicalScores: ['gcs-calculator', 'four-score', 'news2'],
    protocols: ['neuro-exam-assistant'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'seizure-status-epilepticus',
    name: 'Seizure / Status Epilepticus',
    category: 'neurological',
    ctasLevels: [1, 2],
    chiefComplaints: ['seizure', 'convulsion', 'status epilepticus', 'postictal', 'new seizure'],
    icdCodes: ['G40', 'R56'],
    frequency: 'critical',
    timeCritical: true,
    canadianGuideline: 'CTAS 2025 seizure guidance',
    clinicalScores: ['gcs-calculator'],
    protocols: ['seizure-assistant'],
    codeStatus: 'stub',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'sepsis-qsofa-screening',
    name: 'Sepsis / qSOFA Screening',
    category: 'sepsis',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['sepsis', 'fever', 'infection', 'confused', 'high heart rate', 'hypotension', 'qsofa'],
    icdCodes: ['A41', 'R65'],
    frequency: 'critical',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 infection/sepsis guidance; Sepsis-3 qSOFA',
    clinicalScores: ['qsofa', 'news2'],
    protocols: ['sepsis-management'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'sofa-septic-shock',
    name: 'SOFA / Septic Shock Organ Dysfunction',
    category: 'sepsis',
    ctasLevels: [1, 2],
    chiefComplaints: ['septic shock', 'sepsis', 'hypotension', 'lactate', 'organ dysfunction', 'sofa'],
    icdCodes: ['A41', 'R65.2'],
    frequency: 'critical',
    timeCritical: true,
    canadianGuideline: 'Sepsis-3 SOFA criteria; CTAS 2025 sepsis guidance',
    clinicalScores: ['sofa-score', 'qsofa', 'news2'],
    protocols: ['sepsis-management'],
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'sep1-bundle-antibiotics-cultures',
    name: 'SEP-1 Bundle / Lactate / Antibiotics / Blood Cultures',
    category: 'sepsis',
    ctasLevels: [1, 2],
    chiefComplaints: ['sepsis', 'septic shock', 'lactate', 'antibiotics', 'blood culture', 'infection'],
    icdCodes: ['A41', 'R65'],
    frequency: 'critical',
    timeCritical: false,
    canadianGuideline: 'Surviving Sepsis Campaign; local sepsis bundle policies',
    clinicalScores: ['qsofa', 'sofa-score', 'news2'],
    protocols: ['sepsis-management', 'antibiotic-dose-guide'],
    codeStatus: 'stub',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'appendicitis-alvarado',
    name: 'Appendicitis / Alvarado',
    category: 'abdominal',
    ctasLevels: [2, 3, 4],
    chiefComplaints: ['right lower quadrant pain', 'appendicitis', 'abdominal pain', 'rlq pain', 'migration of pain'],
    icdCodes: ['K35'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 abdominal pain guidance',
    clinicalScores: ['alvarado'],
    protocols: ['abdominal-pain-workflow'],
    codeStatus: 'stub',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'gi-bleed-blatchford-rockall',
    name: 'GI Bleed / Glasgow-Blatchford / Rockall',
    category: 'abdominal',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['gi bleed', 'hematemesis', 'melena', 'rectal bleeding', 'black stool', 'vomiting blood'],
    icdCodes: ['K92.0', 'K92.1', 'K92.2'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 GI bleed/abdominal pain guidance',
    clinicalScores: ['glasgow-blatchford-score', 'rockall-score'],
    protocols: ['gi-bleed-workflow-assistant'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'pancreatitis-ranson-bisap',
    name: 'Pancreatitis / Ranson / BISAP',
    category: 'abdominal',
    ctasLevels: [2, 3],
    chiefComplaints: ['pancreatitis', 'epigastric pain', 'abdominal pain radiating to back', 'elevated lipase'],
    icdCodes: ['K85'],
    frequency: 'moderate',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 abdominal pain guidance',
    clinicalScores: ['ranson-criteria', 'bisap-score'],
    protocols: ['pancreatitis-workflow-assistant'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'bowel-general-abdominal-pain',
    name: 'Bowel / General Abdominal Pain Workflow',
    category: 'abdominal',
    ctasLevels: [2, 3, 4],
    chiefComplaints: ['abdominal pain', 'belly pain', 'stomach pain', 'bowel obstruction', 'constipation', 'vomiting'],
    icdCodes: ['R10', 'K56'],
    frequency: 'very-common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 abdominal pain guidance',
    clinicalScores: [],
    protocols: ['abdominal-pain-workflow'],
    codeStatus: 'stub',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'major-trauma-atls-fast-shock-index',
    name: 'Major Trauma / ATLS / FAST / Shock Index',
    category: 'trauma',
    ctasLevels: [1, 2],
    chiefComplaints: ['major trauma', 'mvc', 'pedestrian struck', 'stab wound', 'gunshot', 'hemorrhage', 'shock'],
    icdCodes: ['T14', 'V89'],
    frequency: 'critical',
    timeCritical: true,
    canadianGuideline: 'CTAS 2025 trauma guidance; ATLS principles',
    clinicalScores: ['shock-index', 'revised-trauma-score', 'gcs-calculator'],
    protocols: ['trauma-workflow'],
    checklistId: 'trauma',
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'head-injury-ct-pecarn',
    name: 'Head Injury / CT Head / PECARN',
    category: 'trauma',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['head injury', 'head strike', 'concussion', 'fall with head strike', 'ct head', 'vomiting after head injury'],
    icdCodes: ['S06'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 head injury guidance; PECARN pediatric head injury rule',
    clinicalScores: ['pecarn-head', 'gcs-calculator'],
    protocols: ['head-injury-workflow'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'fracture-cspine-ankle',
    name: 'Fracture / C-Spine / Ankle Injury',
    category: 'trauma',
    ctasLevels: [2, 3, 4],
    chiefComplaints: ['fracture', 'neck pain after fall', 'c-spine', 'ankle injury', 'foot injury', 'fall'],
    icdCodes: ['S12', 'S82', 'S92'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'Canadian C-Spine Rule; Ottawa Ankle Rules; CTAS 2025 trauma guidance',
    clinicalScores: ['canadian-c-spine', 'nexus-cspine', 'ottawa-ankle'],
    protocols: ['fracture-imaging-workflow'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'laceration-wound-repair',
    name: 'Laceration / Wound Repair',
    category: 'trauma',
    ctasLevels: [3, 4, 5],
    chiefComplaints: ['laceration', 'cut', 'wound', 'needs stitches', 'bleeding wound'],
    icdCodes: ['S01', 'S51', 'S61', 'S81', 'S91'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 minor trauma guidance',
    clinicalScores: [],
    protocols: ['wound-repair-workflow'],
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'suicide-risk-columbia',
    name: 'Suicide Risk / Columbia Workflow',
    category: 'mental_health',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['suicidal', 'self harm', 'want to die', 'suicide attempt', 'overdose on purpose'],
    icdCodes: ['R45.851', 'X60', 'X84'],
    frequency: 'critical',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 mental health crisis guidance; C-SSRS workflow context',
    clinicalScores: ['columbia-suicide-severity-workflow', 'phq9'],
    protocols: ['suicide-risk-workflow-assistant'],
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'depression-anxiety-phq9-gad7',
    name: 'Depression/Anxiety / PHQ-9 / GAD-7',
    category: 'mental_health',
    ctasLevels: [2, 3, 4],
    chiefComplaints: ['depression', 'anxiety', 'panic', 'phq', 'gad', 'mental health'],
    icdCodes: ['F32', 'F41'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 mental health guidance',
    clinicalScores: ['phq9', 'gad7'],
    protocols: ['mental-health-screening-assistant'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'alcohol-substance-cage-audit-c-ciwa',
    name: 'Alcohol/Substance / CAGE / AUDIT-C / CIWA',
    category: 'mental_health',
    ctasLevels: [1, 2, 3, 4],
    chiefComplaints: ['intoxication', 'alcohol withdrawal', 'substance use', 'drunk', 'overdose', 'ciwa'],
    icdCodes: ['F10', 'F19'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 substance use and withdrawal guidance',
    clinicalScores: ['cage', 'audit-c'],
    protocols: ['substance-use-screening-assistant'],
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'psychiatric-agitation-boarding',
    name: 'Psychiatric Agitation / Psych Boarding',
    category: 'mental_health',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['agitation', 'psychosis', 'psychiatric crisis', 'violent behavior', 'mental health boarding'],
    icdCodes: ['F29', 'R45'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 mental health and safety guidance',
    clinicalScores: ['rass'],
    protocols: ['psychiatry-monitoring-dashboard', 'crisis-escalation-audit-log'],
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'pediatric-dosing-broselow-weight-based',
    name: 'Pediatric Dosing / Broselow / Weight-Based',
    category: 'pediatric',
    ctasLevels: [1, 2, 3, 4],
    chiefComplaints: ['child', 'pediatric', 'infant', 'baby', 'peds dose', 'broselow', 'pediatric arrest'],
    icdCodes: ['Z00.1'],
    frequency: 'critical',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 pediatric guidance; local pediatric resuscitation policies',
    clinicalScores: ['pediatric-dose-safety-checker'],
    protocols: ['pediatric-command-center'],
    checklistId: 'pediatric-arrest',
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'pews-pediatric-gcs-vitals',
    name: 'PEWS / Pediatric GCS / Pediatric Vitals',
    category: 'pediatric',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['pediatric deterioration', 'child fever', 'infant lethargic', 'pediatric gcs', 'pews'],
    icdCodes: ['R50', 'R53'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 pediatric acuity guidance',
    clinicalScores: ['pews', 'pediatric-gcs'],
    protocols: ['pediatric-command-center'],
    codeStatus: 'complete',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'croup-febrile-child-neonatal',
    name: 'Croup / Febrile Child / Neonatal',
    category: 'pediatric',
    ctasLevels: [1, 2, 3, 4],
    chiefComplaints: ['croup', 'barking cough', 'febrile child', 'fever infant', 'neonatal fever', 'stridor'],
    icdCodes: ['J05', 'R50'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 pediatric fever/respiratory guidance',
    clinicalScores: ['neonatal-bilirubin-risk-helper', 'pediatric-bp-percentile'],
    protocols: ['pediatric-sepsis-assistant', 'neonatal-assessment-assistant'],
    codeStatus: 'stub',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'falls-frailty-elderly-fall',
    name: 'Falls / Frailty / Elderly Fall',
    category: 'geriatric',
    ctasLevels: [2, 3, 4],
    chiefComplaints: ['fall', 'elderly fall', 'frailty', 'weakness', 'fall on anticoagulants'],
    icdCodes: ['W19', 'R54'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 geriatric trauma/falls guidance',
    clinicalScores: ['morse-fall-scale', 'braden-scale'],
    protocols: ['geriatric-fall-workflow'],
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'delirium-cognition-dementia-mmse-moca',
    name: 'Delirium / Cognition / Dementia / MMSE-MoCA',
    category: 'geriatric',
    ctasLevels: [2, 3, 4],
    chiefComplaints: ['delirium', 'confusion elderly', 'dementia', 'cognitive decline', 'mmse', 'moca'],
    icdCodes: ['F03', 'F05', 'R41'],
    frequency: 'common',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 altered mental status and geriatric guidance',
    clinicalScores: ['mmse', 'moca-placeholder-workflow'],
    protocols: ['cognitive-screening-assistant'],
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'overdose-naloxone-antidote',
    name: 'Overdose / Naloxone / Antidote Reference',
    category: 'toxicology',
    ctasLevels: [1, 2, 3],
    chiefComplaints: ['overdose', 'opioid overdose', 'naloxone', 'poisoning', 'toxic ingestion', 'antidote'],
    icdCodes: ['T40', 'T50'],
    frequency: 'critical',
    timeCritical: false,
    canadianGuideline: 'CTAS 2025 poisoning/overdose guidance',
    clinicalScores: ['osmolal-gap'],
    protocols: ['antidote-reference', 'substance-use-screening-assistant'],
    codeStatus: 'stub',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'anaphylaxis-epinephrine-allergy',
    name: 'Anaphylaxis / Epinephrine / Allergy',
    category: 'toxicology',
    ctasLevels: [1, 2],
    chiefComplaints: ['anaphylaxis', 'allergic reaction', 'epinephrine', 'hives and wheeze', 'throat swelling'],
    icdCodes: ['T78.2', 'T78.0'],
    frequency: 'critical',
    timeCritical: true,
    canadianGuideline: 'CTAS 2025 anaphylaxis guidance',
    clinicalScores: ['pediatric-dose-safety-checker'],
    protocols: ['anaphylaxis-workflow'],
    checklistId: 'anaphylaxis',
    codeStatus: 'partial',
    triggerOnComplaints: true,
  }),
  scenario({
    id: 'capacity-surge-diversion-nedocs',
    name: 'Capacity / Surge / Diversion / NEDOCS',
    category: 'operational',
    ctasLevels: [1, 2, 3, 4, 5],
    chiefComplaints: ['capacity', 'surge', 'diversion', 'crowding', 'nedocs', 'ems backlog'],
    frequency: 'critical',
    timeCritical: false,
    canadianGuideline: 'CTAS operational indicators; local full capacity protocol',
    clinicalScores: ['bed-occupancy-calculator', 'staffing-ratio-calculator', 'resource-utilization-index'],
    protocols: ['capacity-command-center', 'full-capacity-protocol'],
    codeStatus: 'partial',
    triggerOnComplaints: false,
  }),
  scenario({
    id: 'boarding-lwbs-wait-time-queue',
    name: 'Boarding / LWBS / Wait Time / Queue',
    category: 'operational',
    ctasLevels: [1, 2, 3, 4, 5],
    chiefComplaints: ['boarding', 'lwbs', 'left without being seen', 'wait time', 'queue', 'admission delay'],
    frequency: 'critical',
    timeCritical: false,
    canadianGuideline: 'CTAS operational indicators; local ED flow benchmarks',
    clinicalScores: ['turnaround-time-calculator', 'bed-occupancy-calculator'],
    protocols: ['boarding-intelligence', 'long-wait-rescue'],
    codeStatus: 'partial',
    triggerOnComplaints: false,
  }),
];

export const SCENARIO_REGISTRY_BY_ID: Record<string, EDScenario> = Object.freeze(
  Object.fromEntries(SCENARIO_REGISTRY.map((entry) => [entry.id, entry])),
);

export const SCENARIO_CATEGORIES: ScenarioCategory[] = [
  'cardiac',
  'respiratory',
  'neurological',
  'sepsis',
  'abdominal',
  'trauma',
  'mental_health',
  'pediatric',
  'geriatric',
  'toxicology',
  'operational',
];

export const CRITICAL_PATH_SCENARIO_IDS = SCENARIO_REGISTRY.filter((entry) => entry.timeCritical).map(
  (entry) => entry.id,
);

export function getScenarioById(id: string): EDScenario | undefined {
  return SCENARIO_REGISTRY_BY_ID[id];
}

export function getScenariosByCategory(category: ScenarioCategory): EDScenario[] {
  return SCENARIO_REGISTRY.filter((entry) => entry.category === category);
}

export function getEnabledDefaultScenarios(): EDScenario[] {
  return SCENARIO_REGISTRY.filter((entry) => entry.defaultEnabled);
}
