#!/usr/bin/env node
// Regenerates the root-level tree.txt architecture snapshot. Run at the start of every
// healing/scan cycle (see memory: feedback-tree-scan-before-healing) so structural decisions
// (duplicate directories, orphaned modules, page/route placement) are made against the real,
// current filesystem instead of a stale map or memory of how the repo used to look.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const excludePatterns = 'node_modules|dist|dist-ssr|coverage|.git|.cache|build|.next|tmp|temp';
const args = ['-a', '--dirs-first', '-I', excludePatterns];
const treeBin = path.join(
  repoRoot,
  'node_modules',
  '.bin',
  process.platform === 'win32' ? 'tree.cmd' : 'tree',
);

const generatedAt = new Date().toISOString();
const commandLine = `npx tree ${args.map((a) => (a.includes('|') ? `"${a}"` : a)).join(' ')}`;
const header = [
  `# tree.txt -- CareDroid-Clinical-AI repository structure snapshot`,
  `# Generated by: ${commandLine} (respects .gitignore in addition to -I)`,
  `# Generated at: ${generatedAt}`,
  `# Regenerate with: npm run tree`,
  '',
  '',
].join('\n');

// execSync (not execFileSync) so we control quoting explicitly: the -I pattern contains `|`,
// which cmd.exe treats as a pipe operator unless the whole argument is wrapped in double quotes
// -- execFileSync's shell:true mode doesn't escape shell metacharacters for us on Windows, and
// .cmd shims (tree-node-cli's binary) can't be spawned at all without shell:true.
const commandString = `"${treeBin}" ${args.map((a) => (a.includes('|') ? `"${a}"` : a)).join(' ')}`;
const treeOutput = execSync(commandString, {
  cwd: repoRoot,
  encoding: 'utf8',
  maxBuffer: 64 * 1024 * 1024,
});

writeFileSync(path.join(repoRoot, 'tree.txt'), header + treeOutput);
console.log(`tree.txt regenerated at ${generatedAt}`);
