import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  Baby,
  Bandage,
  BarChart3,
  Bell,
  Book,
  BookOpen,
  Bot,
  Braces,
  Brain,
  Footprints,
  Calculator,
  Check,
  CheckCircle2,
  Copy,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  CircleDollarSign,
  Contrast,
  Dna,
  Download,
  Droplets,
  Dumbbell,
  FileSpreadsheet,
  FileText,
  Flame,
  FlaskConical,
  FileEdit,
  GitBranch,
  HeartPulse,
  Hospital,
  Keyboard,
  Layers,
  LayoutDashboard,
  Loader2,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link2,
  Lock,
  LogOut,
  Menu,
  MessageCircle,
  MessageSquare,
  Mail,
  Microscope,
  Moon,
  Palette,
  Pin,
  Pill,
  Rocket,
  Route,
  Scale,
  ScrollText,
  Search,
  Settings,
  Shield,
  Siren,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  TestTube2,
  Trash2,
  Trophy,
  Truck,
  Upload,
  User,
  Users,
  WifiOff,
  Wine,
  Wind,
  Wrench,
  X,
  Zap,
} from 'lucide-react';

const FALLBACK = Layers;

/** Primary app routes (Sidebar / Navigation) */
const NAV_ICONS = {
  workspace: Layers,
  home: LayoutDashboard,
  discover: Lightbulb,
  automation: Zap,
  assistant: Bot,
  tools: Wrench,
  calculators: Calculator,
  'digital-twin': Activity,
  'live-map': Route,
  'hospital-map': Hospital,
  fleet: Truck,
  devices: Wrench,
  artifacts: Layers,
  memory: Brain,
  training: LineChart,
  simulation: Trophy,
  laboratory: FlaskConical,
  '3d-viewer': Layers,
  operations: Truck,
  maps: Route,
  'medical-iot': Activity,
  'developer-audit': ScrollText,
  plugins: Braces,
  'dependency-map': Link2,
  'dependency-graph': GitBranch,
  'data-lineage': GitBranch,
  'self-diagnostics': Activity,
  'system-health': Activity,
  governance: Shield,
  security: Lock,
  settings: Settings,
  pulse: LayoutDashboard,
  chat: MessageSquare,
  control: Settings,
  'clinical-alerts': Siren,
  profile: User,
  team: Users,
  audit: ScrollText,
  analytics: LineChart,
};

/** Tool registry ids */
const TOOL_ICONS = {
  'drug-check': Pill,
  'lab-interp': FlaskConical,
  'simulation-suite': Trophy,
  'laboratory-dashboard': FlaskConical,
  'medical-3d-viewer': Layers,
  calculators: Calculator,
  'sofa-score': Hospital,
  'calc-gfr': Activity,
  'calc-bmi': Scale,
  'calc-chads2vasc': HeartPulse,
  qsofa: Siren,
  news2: ClipboardList,
  'child-pugh': Microscope,
  'has-bled': Bandage,
  meld: TestTube2,
  'meld-na': TestTube2,
  'timi-ua-nstemi': HeartPulse,
  'ascvd-risk': HeartPulse,
  'duke-treadmill-score': LineChart,
  'reynolds-risk-score': HeartPulse,
  'hcm-sudden-death-risk': AlertTriangle,
  chads2: HeartPulse,
  'heart-failure-staging': HeartPulse,
  'ckd-staging': Activity,
  'stop-bang': Moon,
  'bode-index': Wind,
  'copd-gold-assessment': Flame,
  'aa-gradient': Wind,
  'pao2-fio2-ratio': Activity,
  'rox-index': Activity,
  'pneumonia-severity-index': Stethoscope,
  'asthma-severity-score': Wind,
  'audit-c': Wine,
  phq9: Brain,
  gad7: Zap,
  'heart-score': HeartPulse,
  'centor-mcisaac': Stethoscope,
  'bishop-score': Baby,
  'apgar-score': Baby,
  'braden-scale': Bandage,
  'morse-fall-scale': User,
  'ranson-criteria': TestTube2,
  'bisap-score': TestTube2,
  fib4: Microscope,
  'maddrey-discriminant-function': TestTube2,
  apri: Microscope,
  'glasgow-blatchford-score': TestTube2,
  'rockall-score': TestTube2,
  'framingham-risk': LineChart,
  'ecg-interpretation-assistant': Activity,
  'stemi-pathway-assistant': Siren,
  'acs-workflow-assistant': ClipboardList,
  'atrial-fibrillation-assistant': HeartPulse,
  'heart-failure-assistant': HeartPulse,
  'cardiac-telemetry-analyzer': Activity,
  'ecg-trend-engine': LineChart,
  'arrhythmia-risk-classifier': AlertTriangle,
  'remote-cardiology-monitoring-dashboard': LayoutDashboard,
  'cardiology-command-center': LayoutDashboard,
  'copd-gold': Flame,
  'asthma-exacerbation-assistant': Wind,
  'ventilator-support-assistant': Activity,
  'oxygen-escalation-helper': Wind,
  'copd-workflow-assistant': Flame,
  'ventilator-monitoring-dashboard': LayoutDashboard,
  'respiratory-telemetry-dashboard': Activity,
  'sleep-apnea-analytics': Moon,
  'pulmonary-trend-engine': LineChart,
  'respiratory-command-center': LayoutDashboard,
  'rome-iv-ibs': BookOpen,
  'gi-bleed-workflow-assistant': TestTube2,
  'liver-disease-assistant': Microscope,
  'pancreatitis-workflow-assistant': TestTube2,
  'gi-surveillance-dashboard': LayoutDashboard,
  'hepatic-trend-analytics': LineChart,
  'endoscopy-workflow-assistant': ClipboardList,
  'cirrhosis-monitoring-engine': Activity,
  'gi-command-center': LayoutDashboard,
  'live-tracking-map': Route,
  'fleet-live-map': Truck,
  'fleet-command': Truck,
  'hospital-map': Hospital,
  'device-fleet-management': Wrench,
  'telemetry-monitoring': Activity,
  'device-maintenance': Wrench,
  'hospital-operations-command': LayoutDashboard,
  'hospital-command-assistant': Sparkles,
  'resource-allocation-assistant': Layers,
  'device-recommendation-assistant': Lightbulb,
  'asset-tracking-dashboard': Pin,
  'incident-command-center': AlertTriangle,
  'hospital-operations-cockpit': LayoutDashboard,
  'device-battery-intelligence': Zap,
  'capacity-prediction-engine': LineChart,
  'medical-iot-dashboard': Activity,
  'predictive-maintenance': Wrench,
  'route-optimizer': Route,
  'dispatch-ai': Sparkles,
  'wells-pe': HeartPulse,
  'apache2-calculator': Hospital,
  'curb65-calculator': Stethoscope,
  'gcs-calculator': Brain,
  mews: ClipboardList,
  'revised-trauma-score': Siren,
  pews: Baby,
  perc: Wind,
  'grace-acs': HeartPulse,
  nihss: Brain,
  'canadian-c-spine': Braces,
  'ottawa-ankle': Footprints,
  'pecarn-head': Baby,
  'nexus-cspine': Braces,
  abcd2: Brain,
  'shock-index': Siren,
  'anion-gap': FlaskConical,
  rass: Activity,
  'bed-occupancy-calculator': Hospital,
  'staffing-ratio-calculator': Users,
  'turnaround-time-calculator': Clock,
  'resource-utilization-index': BarChart3,
  protocols: ClipboardList,
  diagnosis: Stethoscope,
  procedures: BookOpen,
  'ambient-scribe': FileEdit,
  'calculator-recommender-ai': Lightbulb,
  'guideline-rag': ScrollText,
  'differential-ai': Brain,
  'timeline-ai': Clock,
  'patient-summary-ai': ClipboardList,
  'order-set-ai': FileText,
  'ai-explainability': Search,
  'clinical-audit': ScrollText,
};

const TOOL_ID_ALIASES = {
  'drug-interaction-checker': 'drug-check',
  'drug-interactions': 'drug-check',
  'lab-interpreter': 'lab-interp',
  'sofa-calculator': 'sofa-score',
};

/** Calculator sub-cards (Calculators.jsx) */
const CALCULATOR_SUB_ICONS = {
  sofa: Hospital,
  qsofa: Siren,
  news2: ClipboardList,
  'child-pugh': Microscope,
  'has-bled': Bandage,
  meld: TestTube2,
  'meld-na': TestTube2,
  'timi-ua-nstemi': HeartPulse,
  'ascvd-risk': HeartPulse,
  'ckd-staging': Activity,
  'stop-bang': Moon,
  'bode-index': Wind,
  'copd-gold-assessment': Flame,
  'aa-gradient': Wind,
  'pao2-fio2-ratio': Activity,
  'rox-index': Activity,
  'pneumonia-severity-index': Stethoscope,
  'asthma-severity-score': Wind,
  'audit-c': Wine,
  phq9: Brain,
  gad7: Zap,
  'heart-score': HeartPulse,
  'centor-mcisaac': Stethoscope,
  'bishop-score': Baby,
  'apgar-score': Baby,
  'braden-scale': Bandage,
  'morse-fall-scale': User,
  'ranson-criteria': TestTube2,
  'bisap-score': TestTube2,
  fib4: Microscope,
  'maddrey-discriminant-function': TestTube2,
  apri: Microscope,
  'glasgow-blatchford-score': TestTube2,
  'rockall-score': TestTube2,
  'framingham-risk': LineChart,
  'duke-treadmill-score': LineChart,
  'reynolds-risk-score': HeartPulse,
  'hcm-sudden-death-risk': AlertTriangle,
  chads2: HeartPulse,
  'heart-failure-staging': HeartPulse,
  'apache-ii': Hospital,
  'curb-65': Stethoscope,
  gcs: Brain,
  mews: ClipboardList,
  'revised-trauma-score': Siren,
  pews: Baby,
  'shock-index': Siren,
  'anion-gap': FlaskConical,
  rass: Activity,
  'bed-occupancy-calculator': Hospital,
  'staffing-ratio-calculator': Users,
  'turnaround-time-calculator': Clock,
  'resource-utilization-index': BarChart3,
  gfr: Activity,
  bmi: Scale,
  chads2vasc: HeartPulse,
};

/** Lab Interpreter category headers */
const LAB_CATEGORY_ICONS = {
  CBC: Droplets,
  Electrolytes: Zap,
  'Renal Function': Activity,
  'Liver Function': TestTube2,
  Coagulation: Bandage,
  Other: FlaskConical,
};

/** featureInventory.js ids */
const FEATURE_ICONS = {
  'drug-interactions': Pill,
  calculators: Calculator,
  protocols: ClipboardList,
  'lab-interpreter': FlaskConical,
  diagnosis: Search,
  procedures: BookOpen,
  'ai-workflow': Brain,
  'audit-logging': FileText,
  'drug-database': Book,
  'offline-access': WifiOff,
  'fhir-hl7-dicom': Link2,
  'custom-branding': Palette,
  'dedicated-support': LifeBuoy,
  'sso-saml': Lock,
  'team-management': Users,
  'ai-query-limits': Zap,
};

/**
 * Lucide keys persisted on `workspace.icon` (new workspaces).
 * Legacy emoji values are mapped internally for getWorkspaceIcon.
 */
export const WORKSPACE_ICON_CHOICES = {
  Hospital,
  Stethoscope,
  Pill,
  Dna,
  FlaskConical,
  Syringe,
  Bandage,
  Microscope,
  LineChart,
  LayoutDashboard,
  Zap,
  Flame,
  Lightbulb,
  Palette,
  Rocket,
  Star,
  Trophy,
  Dumbbell,
  Brain,
  Heart: HeartPulse,
  Bell,
  Smartphone,
  Siren,
};

export const WORKSPACE_PICK_KEYS = [
  'Hospital',
  'Stethoscope',
  'Pill',
  'Dna',
  'FlaskConical',
  'Syringe',
  'Bandage',
  'Microscope',
  'LineChart',
  'LayoutDashboard',
  'Zap',
  'Flame',
  'Lightbulb',
  'Palette',
  'Rocket',
  'Star',
  'Trophy',
  'Dumbbell',
  'Brain',
  'Heart',
  'Bell',
  'Smartphone',
  'Siren',
];

/** Map legacy emoji workspace icons to Lucide components (internal; used by getWorkspaceIcon). */
const WORKSPACE_EMOJI_TO_ICON = {
  '🏥': Hospital,
  '⚕️': Stethoscope,
  '🩺': Stethoscope,
  '💊': Pill,
  '🧬': Dna,
  '🔬': FlaskConical,
  '💉': Syringe,
  '🩹': Bandage,
  '🧪': FlaskConical,
  '📊': LineChart,
  '📈': LineChart,
  '🎯': LayoutDashboard,
  '⚡': Zap,
  '🔥': Flame,
  '💡': Lightbulb,
  '🎨': Palette,
  '🚀': Rocket,
  '⭐': Star,
  '🏆': Trophy,
  '💪': Dumbbell,
  '🧠': Brain,
  '❤️': HeartPulse,
  '🔔': Bell,
  '📱': Smartphone,
  '🚨': Siren,
};

export const CHROME_ICONS = {
  menu: Menu,
  sun: Sun,
  moon: Moon,
  contrast: Contrast,
  sparkles: Sparkles,
  search: Search,
  settings: Settings,
  message: MessageSquare,
  tools: Wrench,
  wrench: Wrench,
  truck: Truck,
  layoutDashboard: LayoutDashboard,
  hospital: Hospital,
  brain: Brain,
  bell: Bell,
  logOut: LogOut,
  bolt: Zap,
  zap: Zap,
  star: Star,
  pin: Pin,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  messageCircle: MessageCircle,
  close: X,
  upload: Upload,
  bot: Bot,
  check: Check,
  checkCircle: CheckCircle2,
  circleDollar: CircleDollarSign,
  user: User,
  users: Users,
  shield: Shield,
  lock: Lock,
  lineChart: LineChart,
  training: LineChart,
  artifacts: Layers,
  trophy: Trophy,
  flask: FlaskConical,
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  rocket: Rocket,
  lightbulb: Lightbulb,
  shareLink: Link2,
  download: Download,
  mail: Mail,
  copy: Copy,
  loader: Loader2,
  formatJson: Braces,
  formatCsv: FileSpreadsheet,
  formatPdf: FileText,
  siren: Siren,
  trash: Trash2,
  barChart: BarChart3,
  keyboard: Keyboard,
  fileEdit: FileEdit,
  clipboardList: ClipboardList,
  microscope: Microscope,
  calculator: Calculator,
  stethoscope: Stethoscope,
  heartPulse: HeartPulse,
  bandage: Bandage,
  activity: Activity,
  scale: Scale,
};

export function getNavIcon(id) {
  return NAV_ICONS[id] || FALLBACK;
}

export function getToolIcon(id) {
  if (!id) return FALLBACK;
  const canonical = TOOL_ID_ALIASES[id] || id;
  return TOOL_ICONS[canonical] || FALLBACK;
}

export function getFeatureIcon(id) {
  return FEATURE_ICONS[id] || TOOL_ICONS[id] || FALLBACK;
}

export function getCalculatorSubIcon(id) {
  return CALCULATOR_SUB_ICONS[id] || Calculator;
}

export function getLabCategoryIcon(category) {
  return LAB_CATEGORY_ICONS[category] || FlaskConical;
}

/**
 * Resolve workspace glyph: Lucide choice key, or legacy emoji, or Hospital.
 */
export function getWorkspaceIcon(stored) {
  if (!stored) return Hospital;
  const fromKey = WORKSPACE_ICON_CHOICES[stored];
  if (fromKey) return fromKey;
  const fromEmoji = WORKSPACE_EMOJI_TO_ICON[stored];
  if (fromEmoji) return fromEmoji;
  return Hospital;
}
