export type FeatureCategory =
  | 'clinical'
  | 'operational'
  | 'ems'
  | 'referral'
  | 'capacity'
  | 'ai'
  | 'intake'
  | 'analytics'
  | 'admin';

export type FeatureTier = 'core' | 'professional' | 'enterprise';
export type FeatureStatus = 'stable' | 'beta' | 'preview' | 'deprecated';

export interface Feature {
  id: string;
  label: string;
  description: string;
  category: FeatureCategory;
  tier: FeatureTier;
  status: FeatureStatus;
  defaultEnabled: boolean;
  dependencies: string[];
  sidebarIcon?: string;
  sidebarRoute?: string;
  backendEndpoint?: string;
  relatedTools?: string[];
}

type FeatureInput = Omit<Feature, 'dependencies'> & Partial<Pick<Feature, 'dependencies'>>;

const feature = (definition: FeatureInput): Feature => ({
  dependencies: [],
  ...definition,
});

const calculator = (
  id: string,
  label: string,
  description: string,
  toolId: string,
  slug: string,
  status: FeatureStatus = 'stable',
): Feature =>
  feature({
    id,
    label,
    description,
    category: 'clinical',
    tier: 'core',
    status,
    defaultEnabled: true,
    dependencies: ['clinical_calculator_hub'],
    sidebarIcon: 'calculators',
    sidebarRoute: `/tools/calculators/${slug}`,
    relatedTools: [toolId],
  });

export const FEATURE_REGISTRY: Feature[] = [
  feature({
    id: 'emergency_whiteboard',
    label: 'Emergency Whiteboard',
    description: 'Default CareDroid Emergency OS patient-flow workspace for small ED and urgent care teams.',
    category: 'operational',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'whiteboard',
    sidebarRoute: '/emergency/whiteboard',
  }),
  feature({
    id: 'emergency_patients',
    label: 'Patients',
    description: 'Patient list and snapshots sourced from the Emergency OS journey state.',
    category: 'operational',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'whiteboard',
    sidebarRoute: '/emergency/patients',
  }),
  feature({
    id: 'department_pulse',
    label: 'Department Pulse',
    description: 'Optional charge nurse status summary for teams that need a read-only command view.',
    category: 'operational',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'pulse',
    sidebarRoute: '/emergency/whiteboard',
  }),
  feature({
    id: 'smart_intake',
    label: 'Smart Intake',
    description: 'Identity-safe intake, OCR evidence review, duplicate detection, and staff verification workflow.',
    category: 'intake',
    tier: 'core',
    status: 'beta',
    defaultEnabled: true,
    sidebarIcon: 'intake',
    sidebarRoute: '/emergency/intake',
    backendEndpoint: '/api/emergency/intake/sessions',
  }),
  feature({
    id: 'clinical_calculator_hub',
    label: 'Clinical Tools',
    description: 'Emergency-focused calculator and bedside reference launcher inside the patient-flow workspace.',
    category: 'clinical',
    tier: 'professional',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'calculators',
    sidebarRoute: '/emergency/whiteboard',
    relatedTools: ['calculators'],
  }),

  calculator(
    'heart_score',
    'HEART Score',
    'ED chest pain risk score with human-reviewed pathway context.',
    'heart-score',
    'heart-score',
  ),
  calculator(
    'qsofa',
    'qSOFA',
    'Bedside sepsis screen using respiratory rate, systolic BP, and mentation.',
    'qsofa',
    'qsofa',
  ),
  calculator(
    'nihss',
    'NIHSS',
    'Stroke deficit severity scoring surface for clinician review.',
    'nihss',
    'nihss',
  ),
  calculator(
    'curb65',
    'CURB-65',
    'Community-acquired pneumonia severity score.',
    'curb65-calculator',
    'curb-65',
  ),
  calculator(
    'wells_pe',
    'Wells PE',
    'Pulmonary embolism pre-test probability calculator.',
    'wells-pe',
    'wells-pe',
  ),
  calculator(
    'news2',
    'NEWS2',
    'Acute illness deterioration score for ED and ward review.',
    'news2',
    'news2',
  ),
  calculator(
    'timi',
    'TIMI',
    'TIMI UA/NSTEMI risk score for ACS documentation context.',
    'timi-ua-nstemi',
    'timi-ua-nstemi',
  ),
  calculator(
    'alvarado',
    'Alvarado Score',
    'Appendicitis scoring helper for abdominal pain review.',
    'alvarado',
    'alvarado',
    'preview',
  ),
  calculator(
    'pews',
    'PEWS',
    'Pediatric early warning score with pediatric caution labels.',
    'pews',
    'pews',
  ),
  calculator(
    'phq9',
    'PHQ-9',
    'Depression symptom screen with question 9 safety escalation.',
    'phq9',
    'phq9',
  ),
  calculator(
    'gad7',
    'GAD-7',
    'Anxiety symptom screen with severe-range escalation messaging.',
    'gad7',
    'gad7',
  ),
  calculator(
    'columbia_suicide',
    'Columbia Suicide Severity',
    'Suicide-severity workflow entry with immediate safety review messaging.',
    'columbia-suicide-severity-workflow',
    'columbia-suicide-severity-workflow',
  ),
  calculator(
    'glasgow_coma',
    'Glasgow Coma Scale',
    'Adult Glasgow Coma Scale scoring for trauma and neurologic handoff.',
    'gcs-calculator',
    'gcs',
  ),
  calculator(
    'pediatric_drug_calc',
    'Pediatric Drug Calculator',
    'Pediatric ED emergency drug quick-reference with verification prompts.',
    'pediatric-dose-safety-checker',
    'pediatric-dose-safety-checker',
  ),
  calculator(
    'iv_fluid_calc',
    'IV Fluid Calculator',
    'Fluid balance and IV fluid context helper without prescribing fluids.',
    'fluid-balance-monitor',
    'iv-fluid',
    'preview',
  ),
  calculator(
    'drug_dose_calc',
    'Drug Dose Calculator',
    'Educational medication dose concepts with dosing safety guardrails.',
    'dose-calculator',
    'dose-calculator',
  ),
  calculator(
    'egfr_calc',
    'eGFR Calculator',
    'Kidney function estimate using eGFR calculator surfaces.',
    'egfr-ckd-epi',
    'egfr-ckd-epi',
  ),
  calculator(
    'anion_gap',
    'Anion Gap',
    'Serum anion gap calculation with optional albumin correction.',
    'anion-gap',
    'anion-gap',
  ),
  calculator(
    'corrected_qt',
    'Corrected QT',
    'QTc calculation and ECG interval context helper.',
    'corrected-qt',
    'corrected-qt',
    'preview',
  ),
  calculator(
    'shock_index',
    'Shock Index',
    'Hemodynamic screening index from heart rate and systolic blood pressure.',
    'shock-index',
    'shock-index',
  ),

  feature({
    id: 'ems_pipeline',
    label: 'EMS Pipeline',
    description: 'Pre-arrival EMS intake, readiness, critical broadcast, and handoff workflow.',
    category: 'ems',
    tier: 'professional',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'ems',
    sidebarRoute: '/emergency/ems',
    backendEndpoint: '/api/fleet/snapshot',
  }),
  feature({
    id: 'ems_pressure_score',
    label: 'EMS Pressure Score',
    description: 'Operational pressure score for incoming EMS units and critical arrivals.',
    category: 'ems',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    dependencies: ['ems_pipeline'],
    sidebarRoute: '/emergency/ems',
    backendEndpoint: '/api/fleet/snapshot',
  }),
  feature({
    id: 'referral_intelligence',
    label: 'Referrals',
    description: 'Fast referral sending, tracking, response updates, and escalation support.',
    category: 'referral',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    sidebarIcon: 'referrals',
    sidebarRoute: '/emergency/referrals',
    backendEndpoint: '/api/emergency/referrals',
  }),
  feature({
    id: 'capacity_intelligence',
    label: 'Capacity',
    description: 'Simple capacity score, room pressure, EMS load, and discharge-readiness signals.',
    category: 'capacity',
    tier: 'professional',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'capacity',
    sidebarRoute: '/emergency/capacity',
    backendEndpoint: '/api/emergency/capacity/history',
  }),
  feature({
    id: 'boarding_intelligence',
    label: 'Boarding Intelligence',
    description: 'Boarding patient visibility and capacity-risk escalation signals.',
    category: 'capacity',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    dependencies: ['capacity_intelligence'],
    sidebarIcon: 'capacity',
    sidebarRoute: '/emergency/boarding',
    backendEndpoint: '/api/emergency/analytics',
  }),
  feature({
    id: 'queue_intelligence',
    label: 'Queue Intelligence',
    description: 'Queue wait analytics, bottleneck detection, and flow recommendations.',
    category: 'operational',
    tier: 'professional',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'operations',
    sidebarRoute: '/emergency/queues',
    backendEndpoint: '/api/emergency/queues/analytics',
  }),
  feature({
    id: 'reassessment_engine',
    label: 'Reassessment Engine',
    description: 'Flags reassessment due patients and surfaces deterioration review prompts.',
    category: 'clinical',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    dependencies: ['queue_intelligence'],
    sidebarIcon: 'shift',
    sidebarRoute: '/emergency/reassessment',
  }),
  feature({
    id: 'emergency_analytics',
    label: 'Analytics',
    description: 'Emergency OS throughput, safety, EMS, reassessment, and capacity trends.',
    category: 'analytics',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    sidebarIcon: 'analytics',
    sidebarRoute: '/emergency/analytics',
    backendEndpoint: '/api/emergency/analytics',
  }),
  feature({
    id: 'simulation_engine',
    label: 'Simulation Engine',
    description: 'Emergency scenario simulation and operational rehearsal support.',
    category: 'operational',
    tier: 'professional',
    status: 'preview',
    defaultEnabled: false,
    sidebarIcon: 'simulation',
    sidebarRoute: '/simulation',
  }),

  feature({
    id: 'ed_copilot',
    label: 'ED Copilot',
    description: 'Unified Emergency OS AI assistant for decision-support chat.',
    category: 'ai',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'copilot',
    sidebarRoute: '/emergency/copilot',
    backendEndpoint: '/api/chat/message',
  }),
  feature({
    id: 'copilot_tool_actions',
    label: 'Copilot Tool Actions',
    description: 'AI-triggered Emergency OS tool calls with confirmation for state changes.',
    category: 'ai',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    dependencies: ['ed_copilot'],
    sidebarRoute: '/emergency/copilot',
    backendEndpoint: '/api/chat/message',
  }),
  feature({
    id: 'score_ai_assist',
    label: 'Score AI Assist',
    description: 'Calculator-linked AI guidance for key score fields and missing context.',
    category: 'ai',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    dependencies: ['ed_copilot', 'clinical_calculator_hub'],
    backendEndpoint: '/api/chat/message',
    relatedTools: ['calculators'],
  }),
  feature({
    id: 'intake_ai_suggest',
    label: 'Intake AI Suggest',
    description: 'Complaint-driven intake protocol chip suggestions for triage review.',
    category: 'ai',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    dependencies: ['ed_copilot'],
    backendEndpoint: '/api/chat/message',
  }),
  feature({
    id: 'handoff_brief_gen',
    label: 'Handoff Brief Generation',
    description: 'AI-generated 300-word shift handoff narrative for clinician review.',
    category: 'ai',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    dependencies: ['ed_copilot', 'shift_analytics'],
    backendEndpoint: '/api/chat/message',
  }),
  feature({
    id: 'protocol_suggest',
    label: 'Protocol Suggest',
    description: 'Complaint-based ordered protocol and tool recommendations.',
    category: 'ai',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    dependencies: ['ed_copilot', 'clinical_calculator_hub'],
    backendEndpoint: '/api/chat/message',
    relatedTools: ['calculators'],
  }),

  feature({
    id: 'vitals_history_chart',
    label: 'Vitals History Chart',
    description: 'Patient vital sign trend visualization from observation/source data.',
    category: 'clinical',
    tier: 'professional',
    status: 'preview',
    defaultEnabled: true,
    backendEndpoint: '/api/patients/:patientId/source-data',
  }),
  feature({
    id: 'lab_results_panel',
    label: 'Lab Results Panel',
    description: 'Patient lab result panel with abnormal and critical value context.',
    category: 'clinical',
    tier: 'professional',
    status: 'preview',
    defaultEnabled: true,
    backendEndpoint: '/api/patients/:patientId/import/labs',
  }),
  feature({
    id: 'imaging_orders',
    label: 'Imaging Orders',
    description: 'Imaging order and result summary surface for patient detail.',
    category: 'clinical',
    tier: 'professional',
    status: 'preview',
    defaultEnabled: true,
    backendEndpoint: '/api/patients/:patientId/source-data',
  }),
  feature({
    id: 'medication_history',
    label: 'Medication History',
    description: 'Medication history and status panel sourced from patient records.',
    category: 'clinical',
    tier: 'professional',
    status: 'preview',
    defaultEnabled: true,
    backendEndpoint: '/api/patients/:patientId/import/medications',
  }),
  feature({
    id: 'visit_history',
    label: 'Visit History',
    description: 'Prior visit and encounter history for patient context.',
    category: 'clinical',
    tier: 'professional',
    status: 'preview',
    defaultEnabled: true,
    backendEndpoint: '/api/patients/:patientId/timeline',
  }),
  feature({
    id: 'shift_analytics',
    label: 'Shift Analytics',
    description: 'Shift-level ED throughput, wait, volume, and disposition analytics.',
    category: 'analytics',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    sidebarIcon: 'analytics',
    sidebarRoute: '/emergency/analytics',
    backendEndpoint: '/api/emergency/analytics',
  }),
  feature({
    id: 'shift_summary',
    label: 'Shift Handoff',
    description: 'Shift summary, handoff brief, and quality metrics for Emergency OS teams.',
    category: 'operational',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'shift',
    sidebarRoute: '/emergency/whiteboard',
  }),
  feature({
    id: 'audit_log',
    label: 'Audit Log',
    description: 'Governance and activity audit trail for emergency operations.',
    category: 'admin',
    tier: 'enterprise',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'audit',
    sidebarRoute: '/audit',
    backendEndpoint: '/api/audit/my-logs',
  }),
  feature({
    id: 'ems_diversion',
    label: 'EMS Diversion',
    description: 'Emergency diversion status visibility and operational guardrails.',
    category: 'ems',
    tier: 'enterprise',
    status: 'preview',
    defaultEnabled: false,
    dependencies: ['ems_pipeline'],
    backendEndpoint: '/api/emergency/diversion/status',
  }),
  feature({
    id: 'inter_facility_transfer',
    label: 'Inter-Facility Transfer',
    description: 'Transfer workflow status updates for referral and transport coordination.',
    category: 'referral',
    tier: 'enterprise',
    status: 'preview',
    defaultEnabled: false,
    dependencies: ['referral_intelligence'],
    backendEndpoint: '/api/emergency/transfers/:referralId/status',
  }),
  feature({
    id: 'icd10_lookup',
    label: 'ICD-10 Lookup',
    description: 'Diagnosis code lookup surface for documentation workflows.',
    category: 'clinical',
    tier: 'professional',
    status: 'preview',
    defaultEnabled: false,
    backendEndpoint: '/api/tools/icd10/lookup',
  }),
  feature({
    id: 'export_shift_report',
    label: 'Export Shift Report',
    description: 'Printable or downloadable emergency shift report export.',
    category: 'analytics',
    tier: 'professional',
    status: 'preview',
    defaultEnabled: true,
    dependencies: ['shift_analytics'],
    backendEndpoint: '/api/emergency/shift/report/export',
  }),

  feature({
    id: 'feature_toggles_panel',
    label: 'Feature Toggles Panel',
    description: 'Organization-scoped feature flag management panel.',
    category: 'admin',
    tier: 'enterprise',
    status: 'beta',
    defaultEnabled: true,
    sidebarIcon: 'settings',
    sidebarRoute: '/settings',
    backendEndpoint: '/api/organizations/:organizationId/feature-flags',
  }),
  feature({
    id: 'emergency_settings',
    label: 'Settings',
    description: 'CareDroid Emergency OS settings, staff, thresholds, and feature controls.',
    category: 'admin',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    sidebarIcon: 'settings',
    sidebarRoute: '/emergency/settings',
  }),
  feature({
    id: 'settings_thresholds',
    label: 'Settings Thresholds',
    description: 'Emergency OS threshold and alert rule configuration.',
    category: 'admin',
    tier: 'professional',
    status: 'beta',
    defaultEnabled: true,
    sidebarIcon: 'settings',
    sidebarRoute: '/settings',
    backendEndpoint: '/api/organizations/:organizationId/tenant-admin',
  }),
  feature({
    id: 'room_management',
    label: 'Room Management',
    description: 'Room occupancy, availability, and assignment configuration.',
    category: 'admin',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    dependencies: ['capacity_intelligence'],
    sidebarRoute: '/settings',
  }),
  feature({
    id: 'staff_management',
    label: 'Staff Management',
    description: 'Staff roster, role, and shift assignment configuration.',
    category: 'admin',
    tier: 'core',
    status: 'stable',
    defaultEnabled: true,
    sidebarRoute: '/settings',
    backendEndpoint: '/api/organizations/:organizationId/tenant-admin',
  }),
  feature({
    id: 'integration_status',
    label: 'Integration Status',
    description: 'FHIR and HL7 integration status and test connection surfaces.',
    category: 'admin',
    tier: 'enterprise',
    status: 'beta',
    defaultEnabled: true,
    sidebarRoute: '/settings',
    backendEndpoint: '/api/integrations/fhir/connections',
  }),
];

export const FEATURE_REGISTRY_BY_ID: Readonly<Record<string, Feature>> = Object.freeze(
  Object.fromEntries(FEATURE_REGISTRY.map((featureDefinition) => [featureDefinition.id, featureDefinition])),
);
