import { PatientFlag } from '../../src/types/emergency';
import type { EmergencyRoleId, OrchestrationToolDefinition } from './orchestrationTypes';

const CLINICAL_ROLES: EmergencyRoleId[] = [
  'triage_nurse',
  'physician',
  'charge_nurse',
  'ed_manager',
  'admin',
];

const ALL_STAFF: EmergencyRoleId[] = [
  'registration_clerk',
  'triage_nurse',
  'physician',
  'charge_nurse',
  'ed_manager',
  'ems_user',
  'admin',
];

export const ORCHESTRATION_TOOL_CATALOG: readonly OrchestrationToolDefinition[] = Object.freeze([
  {
    id: 'verify-identity',
    toolId: 'verify-identity',
    label: 'Verify identity',
    category: 'intake_verification',
    launchKind: 'workflow',
    maturity: 'live',
    stages: ['arrival', 'waiting_intake'],
    roles: ['registration_clerk', 'triage_nurse', 'ems_user', 'admin'],
    baseScore: 90,
  },
  {
    id: 'triage-assist',
    toolId: 'triage-assist',
    label: 'Triage assist',
    category: 'reassessment_deterioration',
    launchKind: 'copilot',
    maturity: 'demo',
    stages: ['waiting_intake', 'triage_handoff'],
    roles: ['triage_nurse', 'charge_nurse', 'ed_manager', 'admin'],
    baseScore: 85,
  },
  {
    id: 'news2',
    toolId: 'news2',
    label: 'NEWS2',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'news2',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment', 'observation_reassessment', 'deterioration_concern'],
    overlayStages: ['deterioration_concern'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['news2'],
    requiresVitals: true,
    requiresIdentity: true,
    baseScore: 80,
  },
  {
    id: 'qsofa',
    toolId: 'qsofa',
    label: 'qSOFA',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'qsofa',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment', 'observation_reassessment', 'deterioration_concern'],
    overlayStages: ['deterioration_concern'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['qsofa'],
    flagTriggers: [PatientFlag.SepsisAlert],
    requiresVitals: true,
    requiresIdentity: true,
    baseScore: 82,
  },
  {
    id: 'heart-score',
    toolId: 'heart-score',
    label: 'HEART Score',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'heart-score',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['heart-score', 'heartScore'],
    requiresIdentity: true,
    baseScore: 88,
  },
  {
    id: 'wells-pe',
    toolId: 'wells-pe',
    label: 'Wells PE',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'wells-pe',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['wells-pe', 'wellsPe'],
    requiresIdentity: true,
    baseScore: 86,
  },
  {
    id: 'nihss',
    toolId: 'nihss',
    label: 'NIHSS',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'nihss',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment', 'deterioration_concern'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['nihss'],
    flagTriggers: [PatientFlag.StrokeCode, PatientFlag.DeterioratingNeuro],
    requiresIdentity: true,
    baseScore: 90,
  },
  {
    id: 'shock-index',
    toolId: 'shock-index',
    label: 'Shock Index',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'shock-index',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment', 'observation_reassessment', 'deterioration_concern'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['shock-index', 'shockIndex'],
    requiresVitals: true,
    baseScore: 78,
  },
  {
    id: 'pews',
    toolId: 'pews',
    label: 'PEWS',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'pews',
    maturity: 'live',
    stages: ['triage_handoff', 'observation_reassessment'],
    roles: CLINICAL_ROLES,
    maxAge: 17,
    requiresVitals: true,
    baseScore: 84,
  },
  {
    id: 'phq9',
    toolId: 'phq9',
    label: 'PHQ-9',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'phq9',
    maturity: 'live',
    stages: ['physician_assessment', 'waiting_intake', 'triage_handoff'],
    roles: ['triage_nurse', 'physician', 'charge_nurse', 'ed_manager', 'admin'],
    complaintScoreIds: ['phq9'],
    baseScore: 70,
  },
  {
    id: 'gad7',
    toolId: 'gad7',
    label: 'GAD-7',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'gad7',
    maturity: 'live',
    stages: ['physician_assessment', 'waiting_intake', 'triage_handoff'],
    roles: ['triage_nurse', 'physician', 'charge_nurse', 'ed_manager', 'admin'],
    complaintScoreIds: ['gad7'],
    baseScore: 68,
  },
  {
    id: 'revised-trauma-score',
    toolId: 'revised-trauma-score',
    label: 'Revised Trauma Score',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'revised-trauma-score',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment', 'deterioration_concern'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['revised-trauma-score'],
    requiresVitals: true,
    requiresIdentity: true,
    baseScore: 86,
  },
  {
    id: 'ranson-criteria',
    toolId: 'ranson-criteria',
    label: 'Ranson Criteria',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'ranson-criteria',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['ranson-criteria'],
    requiresIdentity: true,
    baseScore: 82,
  },
  {
    id: 'bisap-score',
    toolId: 'bisap-score',
    label: 'BISAP',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'bisap-score',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['bisap-score'],
    requiresIdentity: true,
    baseScore: 82,
  },
  {
    id: 'glasgow-blatchford-score',
    toolId: 'glasgow-blatchford-score',
    label: 'Glasgow-Blatchford',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'glasgow-blatchford-score',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['glasgow-blatchford-score'],
    requiresIdentity: true,
    baseScore: 84,
  },
  {
    id: 'ciwa-ar',
    toolId: 'ciwa-ar',
    label: 'CIWA-Ar',
    category: 'risk_score',
    launchKind: 'calculator',
    registryId: 'ciwa-ar',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment', 'observation_reassessment'],
    roles: CLINICAL_ROLES,
    complaintScoreIds: ['ciwa-ar'],
    requiresIdentity: true,
    baseScore: 80,
  },
  {
    id: 'pediatric-dose-safety-checker',
    toolId: 'pediatric-dose-safety-checker',
    label: 'Pediatric dosing',
    category: 'medication_safety',
    launchKind: 'calculator',
    registryId: 'pediatric-dose-safety-checker',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment'],
    roles: CLINICAL_ROLES,
    maxAge: 17,
    requiresIdentity: true,
    baseScore: 83,
  },
  {
    id: 'columbia-suicide',
    toolId: 'columbia-suicide-severity-workflow',
    label: 'C-SSRS',
    category: 'checklist_protocol',
    launchKind: 'checklist',
    registryId: 'columbia-suicide-severity-workflow',
    maturity: 'live',
    stages: ['waiting_intake', 'triage_handoff', 'physician_assessment'],
    roles: CLINICAL_ROLES,
    flagTriggers: [PatientFlag.PsychAlert],
    baseScore: 88,
  },
  {
    id: 'drug-check',
    toolId: 'drug-check',
    label: 'Drug interactions',
    category: 'medication_safety',
    launchKind: 'tool',
    registryId: 'drug-check',
    maturity: 'demo',
    stages: ['physician_assessment', 'results_review'],
    roles: ['physician', 'triage_nurse', 'charge_nurse', 'admin'],
    requiresIdentity: true,
    baseScore: 72,
  },
  {
    id: 'lab-interp',
    toolId: 'lab-interp',
    label: 'Lab interpreter',
    category: 'lab_interpretation',
    launchKind: 'tool',
    registryId: 'lab-interp',
    maturity: 'demo',
    stages: ['results_review', 'physician_assessment'],
    roles: ['physician', 'triage_nurse', 'charge_nurse', 'admin'],
    baseScore: 75,
  },
  {
    id: 'patient-summary',
    toolId: 'patient-summary-ai',
    label: 'Case summary',
    category: 'summary_handoff',
    launchKind: 'tool',
    registryId: 'patient-summary-ai',
    maturity: 'demo',
    stages: ['physician_assessment', 'results_review', 'referral_boarding_transfer', 'discharge_workflow'],
    roles: ['physician', 'charge_nurse', 'ed_manager', 'triage_nurse', 'admin'],
    requiresIdentity: true,
    baseScore: 68,
  },
  {
    id: 'handoff-brief',
    toolId: 'handoff-brief',
    label: 'Handoff brief',
    category: 'summary_handoff',
    launchKind: 'copilot',
    maturity: 'demo',
    stages: ['referral_boarding_transfer', 'discharge_workflow', 'observation_reassessment'],
    roles: ['physician', 'charge_nurse', 'ed_manager', 'triage_nurse', 'admin'],
    baseScore: 74,
  },
  {
    id: 'reassessment-vitals',
    toolId: 'reassessment-vitals',
    label: 'Repeat vitals',
    category: 'reassessment_deterioration',
    launchKind: 'workflow',
    maturity: 'live',
    stages: ['observation_reassessment', 'deterioration_concern', 'waiting_intake'],
    overlayStages: ['deterioration_concern'],
    roles: CLINICAL_ROLES,
    flagTriggers: [PatientFlag.ReassessmentDue, PatientFlag.DeteriorationRisk],
    baseScore: 92,
  },
  {
    id: 'sepsis-protocol',
    toolId: 'sepsis-bundle',
    label: 'Sepsis bundle',
    category: 'checklist_protocol',
    launchKind: 'checklist',
    maturity: 'live',
    stages: ['deterioration_concern', 'physician_assessment', 'observation_reassessment'],
    overlayStages: ['deterioration_concern'],
    roles: CLINICAL_ROLES,
    flagTriggers: [PatientFlag.SepsisAlert],
    baseScore: 95,
  },
  {
    id: 'stroke-protocol',
    toolId: 'stroke-code',
    label: 'Stroke protocol',
    category: 'checklist_protocol',
    launchKind: 'checklist',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment', 'deterioration_concern'],
    roles: CLINICAL_ROLES,
    flagTriggers: [PatientFlag.StrokeCode, PatientFlag.DeterioratingNeuro],
    baseScore: 94,
  },
  {
    id: 'referral-summary',
    toolId: 'referral-summary',
    label: 'Referral summary',
    category: 'referral_transfer',
    launchKind: 'copilot',
    maturity: 'demo',
    stages: ['referral_boarding_transfer'],
    roles: ['physician', 'charge_nurse', 'ed_manager', 'admin'],
    baseScore: 86,
  },
  {
    id: 'escalate-patient',
    toolId: 'escalate-patient',
    label: 'Escalate case',
    category: 'operational_escalation',
    launchKind: 'workflow',
    maturity: 'live',
    stages: ['deterioration_concern', 'observation_reassessment', 'waiting_intake'],
    overlayStages: ['deterioration_concern'],
    roles: ALL_STAFF.filter((role) => role !== 'read_only_viewer' && role !== 'public_display'),
    flagTriggers: [PatientFlag.HighRisk, PatientFlag.LWBSRisk, PatientFlag.LongWait],
    baseScore: 88,
  },
  {
    id: 'ems-handoff',
    toolId: 'ems-handoff',
    label: 'EMS handoff',
    category: 'checklist_protocol',
    launchKind: 'checklist',
    maturity: 'live',
    stages: ['arrival', 'waiting_intake', 'triage_handoff'],
    roles: ['ems_user', 'triage_nurse', 'registration_clerk', 'charge_nurse', 'admin'],
    flagTriggers: [PatientFlag.EMSArrival],
    baseScore: 87,
  },
  {
    id: 'protocols',
    toolId: 'protocols',
    label: 'Protocols',
    category: 'checklist_protocol',
    launchKind: 'protocol',
    registryId: 'protocols',
    maturity: 'live',
    stages: ['triage_handoff', 'physician_assessment', 'deterioration_concern'],
    roles: CLINICAL_ROLES,
    baseScore: 65,
  },
  {
    id: 'copilot-case',
    toolId: 'copilot-case',
    label: 'Case copilot',
    category: 'differential_support',
    launchKind: 'copilot',
    maturity: 'live',
    stages: [
      'arrival',
      'waiting_intake',
      'triage_handoff',
      'physician_assessment',
      'observation_reassessment',
      'results_review',
      'deterioration_concern',
      'referral_boarding_transfer',
      'discharge_workflow',
    ],
    roles: ALL_STAFF.filter((role) => role !== 'read_only_viewer' && role !== 'public_display'),
    baseScore: 60,
  },
]);

export function getOrchestrationToolById(id: string): OrchestrationToolDefinition | undefined {
  return ORCHESTRATION_TOOL_CATALOG.find((tool) => tool.id === id || tool.toolId === id);
}