import type {
  FacilityZone,
  SurveillanceAlert,
  SurveillanceAlertRule,
  SurveillanceCamera,
  SurveillanceHealthMetric,
  SurveillanceIncidentLink,
  SurveillanceIntegrationContract,
  SurveillanceIotDevice,
  SurveillanceKpiArtifact,
  SurveillanceNexusSnapshot,
} from './surveillance.types';

export const SURVEILLANCE_SOURCE = Object.freeze({
  source: 'backend-demo-surveillance-nexus',
  sourceLabel: 'Backend demo surveillance / IoT nexus',
  demo: true,
});

const GENERATED_AT = '2026-06-22T12:00:00.000Z';

const ZONES: FacilityZone[] = [
  {
    id: 'zone-ed-triage',
    name: 'ED Triage Vestibule',
    shortCode: 'ED-TRI',
    facilityId: 'facility-hospital-18',
    facilityLabel: 'Emergency Department 18',
    floorId: 'floor-ed-l1',
    zoneType: 'clinical',
    privacyTier: 'restricted',
    geofence: {
      coordinateSystem: 'hospital-svg',
      polygon: [
        { x: 120, y: 80 },
        { x: 280, y: 80 },
        { x: 280, y: 180 },
        { x: 120, y: 180 },
      ],
    },
    linkedCameraIds: ['cam-ed-triage-01', 'cam-ed-triage-02'],
    linkedIotDeviceIds: ['iot-ed-door-01', 'iot-ed-env-01'],
    activeAlertCount: 1,
    welfareSafeMode: false,
  },
  {
    id: 'zone-track-paddock',
    name: 'Paddock Restricted Lane',
    shortCode: 'PAD-A',
    facilityId: 'facility-racetrack-main',
    facilityLabel: 'Main Racetrack',
    zoneType: 'paddock',
    privacyTier: 'welfare_safe',
    linkedCameraIds: ['cam-pad-01'],
    linkedIotDeviceIds: ['iot-pad-beacon-01', 'iot-pad-gate-01'],
    activeAlertCount: 0,
    welfareSafeMode: true,
  },
  {
    id: 'zone-track-start',
    name: 'Starter Gate & Stretch',
    shortCode: 'STR-01',
    facilityId: 'facility-racetrack-main',
    facilityLabel: 'Main Racetrack',
    zoneType: 'track',
    privacyTier: 'operational',
    linkedCameraIds: ['cam-start-01', 'cam-start-02'],
    linkedIotDeviceIds: ['iot-start-beacon-01'],
    activeAlertCount: 1,
    welfareSafeMode: false,
  },
  {
    id: 'zone-facilities-plant',
    name: 'Facilities Plant Room',
    shortCode: 'FAC-PL',
    facilityId: 'facility-racetrack-main',
    facilityLabel: 'Main Racetrack',
    zoneType: 'back_of_house',
    privacyTier: 'restricted',
    linkedCameraIds: ['cam-fac-01'],
    linkedIotDeviceIds: ['iot-fac-temp-01', 'iot-fac-door-01'],
    activeAlertCount: 0,
    welfareSafeMode: false,
  },
];

const CAMERAS: SurveillanceCamera[] = [
  {
    id: 'cam-ed-triage-01',
    name: 'ED Triage Overhead',
    model: 'Axis P3245-V',
    manufacturer: 'Axis',
    streamProtocol: 'onvif',
    status: 'online',
    zoneId: 'zone-ed-triage',
    zoneLabel: 'ED Triage Vestibule',
    facilityId: 'facility-hospital-18',
    floorId: 'floor-ed-l1',
    x: 160,
    y: 120,
    recordingEnabled: true,
    privacyMaskApplied: true,
    lastHealthCheckAt: GENERATED_AT,
    healthScore: 96,
    firmwareVersion: '10.12.65',
    integrationAdapter: 'hospital-vms-adapter',
    linkedIncidentIds: ['inc-ed-crowd-01'],
  },
  {
    id: 'cam-ed-triage-02',
    name: 'ED Arrival Door',
    model: 'Hanwha XNV-8080R',
    manufacturer: 'Hanwha',
    streamProtocol: 'rtsp',
    status: 'degraded',
    zoneId: 'zone-ed-triage',
    zoneLabel: 'ED Triage Vestibule',
    facilityId: 'facility-hospital-18',
    floorId: 'floor-ed-l1',
    x: 240,
    y: 100,
    recordingEnabled: true,
    privacyMaskApplied: true,
    lastHealthCheckAt: GENERATED_AT,
    healthScore: 72,
    firmwareVersion: '2.21.03',
    integrationAdapter: 'hospital-vms-adapter',
    linkedIncidentIds: [],
  },
  {
    id: 'cam-pad-01',
    name: 'Paddock Welfare Lane',
    model: 'Bosch FLEXIDOME',
    manufacturer: 'Bosch',
    streamProtocol: 'adapter',
    status: 'online',
    zoneId: 'zone-track-paddock',
    zoneLabel: 'Paddock Restricted Lane',
    facilityId: 'facility-racetrack-main',
    x: 420,
    y: 210,
    recordingEnabled: true,
    privacyMaskApplied: true,
    lastHealthCheckAt: GENERATED_AT,
    healthScore: 98,
    firmwareVersion: '8.70.0129',
    integrationAdapter: 'trackmind-welfare-safe-vms',
    linkedIncidentIds: [],
  },
  {
    id: 'cam-start-01',
    name: 'Starter Gate Wide',
    model: 'Avigilon H5A',
    manufacturer: 'Avigilon',
    streamProtocol: 'onvif',
    status: 'online',
    zoneId: 'zone-track-start',
    zoneLabel: 'Starter Gate & Stretch',
    facilityId: 'facility-racetrack-main',
    x: 80,
    y: 40,
    recordingEnabled: true,
    privacyMaskApplied: false,
    lastHealthCheckAt: GENERATED_AT,
    healthScore: 94,
    firmwareVersion: '7.16.0.23',
    integrationAdapter: 'trackmind-raceday-vms',
    linkedIncidentIds: ['inc-race-gate-01'],
  },
  {
    id: 'cam-start-02',
    name: 'Stretch Turnover',
    model: 'Avigilon H5A',
    manufacturer: 'Avigilon',
    streamProtocol: 'onvif',
    status: 'online',
    zoneId: 'zone-track-start',
    zoneLabel: 'Starter Gate & Stretch',
    facilityId: 'facility-racetrack-main',
    x: 200,
    y: 60,
    recordingEnabled: true,
    privacyMaskApplied: false,
    lastHealthCheckAt: GENERATED_AT,
    healthScore: 91,
    firmwareVersion: '7.16.0.23',
    integrationAdapter: 'trackmind-raceday-vms',
    linkedIncidentIds: [],
  },
  {
    id: 'cam-fac-01',
    name: 'Plant Room Entry',
    model: 'Axis M3067-P',
    manufacturer: 'Axis',
    streamProtocol: 'rtsp',
    status: 'maintenance',
    zoneId: 'zone-facilities-plant',
    zoneLabel: 'Facilities Plant Room',
    facilityId: 'facility-racetrack-main',
    x: 520,
    y: 300,
    recordingEnabled: false,
    privacyMaskApplied: false,
    lastHealthCheckAt: GENERATED_AT,
    healthScore: 0,
    firmwareVersion: '10.12.65',
    integrationAdapter: 'facilities-vms-adapter',
    linkedIncidentIds: [],
  },
];

const IOT_DEVICES: SurveillanceIotDevice[] = [
  {
    id: 'iot-ed-door-01',
    name: 'ED Triage Access Reader',
    deviceClass: 'access_control',
    status: 'online',
    zoneId: 'zone-ed-triage',
    zoneLabel: 'ED Triage Vestibule',
    facilityId: 'facility-hospital-18',
    signalStrength: 88,
    lastSeenAt: GENERATED_AT,
    freshness: 'live',
    telemetryLabel: 'Door secured',
    integrationAdapter: 'hospital-access-adapter',
    linkedIncidentIds: [],
  },
  {
    id: 'iot-ed-env-01',
    name: 'ED Vestibule Environmental',
    deviceClass: 'environmental',
    status: 'online',
    zoneId: 'zone-ed-triage',
    zoneLabel: 'ED Triage Vestibule',
    facilityId: 'facility-hospital-18',
    battery: 100,
    signalStrength: 76,
    lastSeenAt: GENERATED_AT,
    freshness: 'live',
    telemetryLabel: 'Temp 22.1°C · RH 44%',
    integrationAdapter: 'hospital-iot-adapter',
    linkedMedicalIotDeviceId: 'med-iot-ed-env-01',
    linkedIncidentIds: [],
  },
  {
    id: 'iot-pad-beacon-01',
    name: 'Paddock Welfare Beacon',
    deviceClass: 'beacon',
    status: 'online',
    zoneId: 'zone-track-paddock',
    zoneLabel: 'Paddock Restricted Lane',
    facilityId: 'facility-racetrack-main',
    battery: 91,
    signalStrength: 82,
    lastSeenAt: GENERATED_AT,
    freshness: 'live',
    telemetryLabel: 'Horse movement nominal',
    integrationAdapter: 'trackmind-welfare-iot',
    linkedIncidentIds: [],
  },
  {
    id: 'iot-pad-gate-01',
    name: 'Paddock Gate Controller',
    deviceClass: 'access_control',
    status: 'online',
    zoneId: 'zone-track-paddock',
    zoneLabel: 'Paddock Restricted Lane',
    facilityId: 'facility-racetrack-main',
    signalStrength: 90,
    lastSeenAt: GENERATED_AT,
    freshness: 'live',
    telemetryLabel: 'Gate closed · authorized only',
    integrationAdapter: 'trackmind-security-adapter',
    linkedIncidentIds: [],
  },
  {
    id: 'iot-start-beacon-01',
    name: 'Starter Gate Beacon',
    deviceClass: 'beacon',
    status: 'degraded',
    zoneId: 'zone-track-start',
    zoneLabel: 'Starter Gate & Stretch',
    facilityId: 'facility-racetrack-main',
    battery: 34,
    signalStrength: 61,
    lastSeenAt: GENERATED_AT,
    freshness: 'stale',
    telemetryLabel: 'Low battery · race-day watch',
    integrationAdapter: 'trackmind-raceday-iot',
    linkedIncidentIds: ['inc-race-gate-01'],
  },
  {
    id: 'iot-fac-temp-01',
    name: 'Plant Room Temperature',
    deviceClass: 'sensor',
    status: 'online',
    zoneId: 'zone-facilities-plant',
    zoneLabel: 'Facilities Plant Room',
    facilityId: 'facility-racetrack-main',
    battery: 100,
    signalStrength: 74,
    lastSeenAt: GENERATED_AT,
    freshness: 'live',
    telemetryLabel: 'Temp 28.4°C',
    integrationAdapter: 'facilities-bms-adapter',
    linkedIncidentIds: [],
  },
  {
    id: 'iot-fac-door-01',
    name: 'Plant Room Door Sensor',
    deviceClass: 'access_control',
    status: 'online',
    zoneId: 'zone-facilities-plant',
    zoneLabel: 'Facilities Plant Room',
    facilityId: 'facility-racetrack-main',
    signalStrength: 79,
    lastSeenAt: GENERATED_AT,
    freshness: 'live',
    telemetryLabel: 'Door closed',
    integrationAdapter: 'facilities-bms-adapter',
    linkedIncidentIds: [],
  },
];

const HEALTH_METRICS: SurveillanceHealthMetric[] = [
  {
    id: 'health-vms',
    label: 'VMS ingest health',
    status: 'degraded',
    score: 82,
    detail: '1 camera degraded in ED triage lane',
    checkedAt: GENERATED_AT,
    domain: 'hospital_ops',
  },
  {
    id: 'health-iot-gateway',
    label: 'IoT gateway connectivity',
    status: 'online',
    score: 94,
    detail: 'All gateways responding within SLA',
    checkedAt: GENERATED_AT,
    domain: 'facilities',
  },
  {
    id: 'health-raceday',
    label: 'Race-day surveillance posture',
    status: 'degraded',
    score: 78,
    detail: 'Starter gate beacon battery low',
    checkedAt: GENERATED_AT,
    domain: 'race_day',
  },
  {
    id: 'health-welfare',
    label: 'Welfare-safe stream policy',
    status: 'online',
    score: 100,
    detail: 'Paddock privacy masks enforced',
    checkedAt: GENERATED_AT,
    domain: 'equine_welfare',
  },
  {
    id: 'health-audit',
    label: 'Audit export pipeline',
    status: 'online',
    score: 97,
    detail: 'Surveillance audit chain verified',
    checkedAt: GENERATED_AT,
    domain: 'audit',
  },
];

const ALERT_RULES: SurveillanceAlertRule[] = [
  {
    id: 'rule-restricted-access',
    name: 'Restricted zone access breach',
    severity: 'high',
    enabled: true,
    trigger: 'access_control.unauthorized_entry',
    zoneIds: ['zone-ed-triage', 'zone-facilities-plant'],
    requiresApproval: false,
    welfareSafe: false,
    linkedIntegration: 'security',
  },
  {
    id: 'rule-welfare-paddock',
    name: 'Paddock welfare movement anomaly',
    severity: 'medium',
    enabled: true,
    trigger: 'beacon.movement.anomaly',
    zoneIds: ['zone-track-paddock'],
    requiresApproval: true,
    welfareSafe: true,
    linkedIntegration: 'equine_welfare',
  },
  {
    id: 'rule-raceday-gate',
    name: 'Race-day gate readiness',
    severity: 'critical',
    enabled: true,
    trigger: 'beacon.battery.low OR gate.not_ready',
    zoneIds: ['zone-track-start'],
    requiresApproval: true,
    welfareSafe: false,
    linkedIntegration: 'race_day',
  },
  {
    id: 'rule-facilities-temp',
    name: 'Facilities temperature threshold',
    severity: 'medium',
    enabled: true,
    trigger: 'sensor.temperature.threshold',
    zoneIds: ['zone-facilities-plant'],
    requiresApproval: false,
    welfareSafe: false,
    linkedIntegration: 'facilities',
  },
];

const ALERTS: SurveillanceAlert[] = [
  {
    id: 'alert-ed-door-01',
    ruleId: 'rule-restricted-access',
    title: 'After-hours ED vestibule access',
    detail: 'Access reader event outside scheduled window',
    severity: 'high',
    status: 'open',
    zoneId: 'zone-ed-triage',
    iotDeviceId: 'iot-ed-door-01',
    incidentId: 'inc-ed-crowd-01',
    triggeredAt: GENERATED_AT,
    lastObservedAt: GENERATED_AT,
  },
  {
    id: 'alert-start-beacon-01',
    ruleId: 'rule-raceday-gate',
    title: 'Starter gate beacon low battery',
    detail: 'Battery at 34% — race-day readiness at risk',
    severity: 'critical',
    status: 'acknowledged',
    zoneId: 'zone-track-start',
    iotDeviceId: 'iot-start-beacon-01',
    incidentId: 'inc-race-gate-01',
    triggeredAt: GENERATED_AT,
    lastObservedAt: GENERATED_AT,
  },
];

const INCIDENT_LINKS: SurveillanceIncidentLink[] = [
  {
    id: 'inc-ed-crowd-01',
    incidentType: 'security',
    incidentLabel: 'ED vestibule crowd control',
    status: 'open',
    linkedCameraIds: ['cam-ed-triage-01'],
    linkedIotDeviceIds: ['iot-ed-door-01'],
    zoneId: 'zone-ed-triage',
    openedAt: GENERATED_AT,
    auditRecordId: 'audit-surv-001',
  },
  {
    id: 'inc-race-gate-01',
    incidentType: 'race_day',
    incidentLabel: 'Starter gate readiness hold',
    status: 'investigating',
    linkedCameraIds: ['cam-start-01'],
    linkedIotDeviceIds: ['iot-start-beacon-01'],
    zoneId: 'zone-track-start',
    openedAt: GENERATED_AT,
    auditRecordId: 'audit-surv-002',
  },
];

const INTEGRATION_CONTRACTS: SurveillanceIntegrationContract[] = [
  {
    adapterId: 'hospital-vms-adapter',
    label: 'Hospital VMS adapter',
    domain: 'hospital_ops',
    status: 'ready',
    contractVersion: '1.0.0',
    endpointHint: '/api/surveillance/adapters/hospital-vms',
    requiresApproval: false,
  },
  {
    adapterId: 'trackmind-raceday-vms',
    label: 'TrackMind race-day VMS',
    domain: 'race_day',
    status: 'ready',
    contractVersion: '1.0.0',
    endpointHint: '/api/surveillance/adapters/raceday-vms',
    requiresApproval: true,
  },
  {
    adapterId: 'trackmind-welfare-safe-vms',
    label: 'Welfare-safe video adapter',
    domain: 'equine_welfare',
    status: 'ready',
    contractVersion: '1.0.0',
    endpointHint: '/api/surveillance/adapters/welfare-vms',
    requiresApproval: true,
  },
  {
    adapterId: 'facilities-bms-adapter',
    label: 'Facilities BMS adapter',
    domain: 'facilities',
    status: 'ready',
    contractVersion: '1.0.0',
    endpointHint: '/api/surveillance/adapters/facilities-bms',
    requiresApproval: false,
  },
  {
    adapterId: 'trackmind-security-adapter',
    label: 'Security operations adapter',
    domain: 'security',
    status: 'ready',
    contractVersion: '1.0.0',
    endpointHint: '/api/surveillance/adapters/security',
    requiresApproval: false,
  },
  {
    adapterId: 'surveillance-audit-adapter',
    label: 'Surveillance audit export',
    domain: 'audit',
    status: 'ready',
    contractVersion: '1.0.0',
    endpointHint: '/api/surveillance/adapters/audit-export',
    requiresApproval: true,
  },
];

const KPI_ARTIFACTS: SurveillanceKpiArtifact[] = [
  { id: 'cameras_online', label: 'Cameras online', value: 4, unit: '/6', trend: 'flat', domain: 'security' },
  { id: 'iot_online', label: 'IoT devices online', value: 6, unit: '/7', trend: 'down', domain: 'facilities' },
  { id: 'zones_covered', label: 'Mapped zones', value: 4, domain: 'facilities' },
  { id: 'open_alerts', label: 'Open surveillance alerts', value: 1, trend: 'up', domain: 'security' },
  { id: 'health_score', label: 'Platform health score', value: 90, unit: '%', trend: 'flat', domain: 'audit' },
  { id: 'welfare_safe_zones', label: 'Welfare-safe zones', value: 1, domain: 'equine_welfare' },
  { id: 'raceday_ready', label: 'Race-day readiness', value: 'Hold', domain: 'race_day' },
];

export function buildSurveillanceNexusSnapshot(): SurveillanceNexusSnapshot {
  return {
    ...SURVEILLANCE_SOURCE,
    generatedAt: GENERATED_AT,
    zones: ZONES,
    cameras: CAMERAS,
    iotDevices: IOT_DEVICES,
    healthMetrics: HEALTH_METRICS,
    alertRules: ALERT_RULES,
    alerts: ALERTS,
    incidentLinks: INCIDENT_LINKS,
    integrationContracts: INTEGRATION_CONTRACTS,
    kpiArtifacts: KPI_ARTIFACTS,
  };
}
